"""Month 10: Sounds & Songs -- curriculum data"""
M10 = {
    "name": "Sounds & Songs",
    "toolkit_label": "2--3 Years &middot; Month 10",
    "weeks": {
        1: {"title": "Listening Games", "subtitle": "Ears are scientists too"},
        2: {"title": "Rhymes & Rhythm", "subtitle": "The music that words make"},
        3: {"title": "Letter Sounds", "subtitle": "The sounds that become reading"},
        4: {"title": "Words in Songs", "subtitle": "Language carried on melody"},
    },
    "days": {
        1:  {"title":"Sound Hunt","emoji":"👂","skill":"Auditory Attention","materials":"Quiet house",
             "milestone":"Milestone: Conscious auditory attention -- deliberately listening to identify specific sounds -- develops the phonological awareness foundation that reading requires. Children who listen well read better.",
             "setup":["Sit quietly together","Close eyes"],
             "play":["Listen silently for 30 seconds","How many sounds can you hear?","Name each one: clock, traffic, birds, breathing","Rank them: loudest to softest"],
             "say":['"Eyes closed. Just listen. What do you hear?"','"Name every sound you can find."','"Which sound is the softest? The furthest away?"'],
             "if_happens":"Child starts making sounds instead of listening",
             "avoid":'"Quiet -- we are listening, not making sounds."',
             "better":'"You made a sound! Now listen to everything else around YOUR sound."',
             "why":"Conscious auditory attention -- the deliberate noticing of environmental sounds -- is the foundation of phonological awareness, which in turn is the strongest single predictor of reading acquisition. The skill being built here is not hearing (passive) but listening (active): intentionally directing attention to auditory input and discriminating between sources. Research shows that training this skill before age 4 significantly supports early reading.",
             "tool":"Ears Open",
             "phrases":['"Your ears can find sounds your eyes cannot see."','"Listening is the hardest thing -- silence helps."'],
             "skills":"Auditory attention, phonological awareness foundation, sound discrimination."},
        2:  {"title":"Loud and Soft","emoji":"🔊","skill":"Volume Perception","materials":"None",
             "milestone":"Milestone: Discriminating between loud and soft sounds -- and being able to control voice volume on demand -- is a social skill and an auditory processing skill that develops between 2 and 4 years.",
             "setup":["Take turns making sounds at different volumes"],
             "play":["Make the loudest sound possible","Make the softest sound possible (a whisper)","Try voice levels: 1 (whisper), 3 (talking), 5 (shouting)","Match: make your voice as loud as this (clap) -- as soft as this (rustle)"],
             "say":['"Volume 5 -- SHOUT!"','"Volume 1 -- whisper... can you hear me?"','"Match my volume -- exactly the same as mine."'],
             "if_happens":"Child only wants to shout",
             "avoid":'"Stop shouting -- indoor voice."',
             "better":'"Wow, your volume 5 is impressive! I wonder if your volume 1 is equally impressive. Let me try to hear your quietest whisper."',
             "why":"Volume modulation -- the ability to control vocal intensity intentionally -- is a social-linguistic skill that children develop gradually. Practising deliberate volume control builds the neural pathway between the intention to be quiet and the motor output of quiet speech. Reframing whisper as equally impressive to shouting removes the social-compliance framing and replaces it with a skill-mastery framing.",
             "tool":"Volume Dial",
             "phrases":['"You have a volume dial in your voice."','"Turn it up. Now turn it all the way down."'],
             "skills":"Volume modulation, vocal control, auditory calibration."},
        3:  {"title":"Fast and Slow Sounds","emoji":"🎶","skill":"Tempo Perception","materials":"Clapping or music",
             "milestone":"Milestone: Perceiving and matching tempo -- fast vs slow -- develops the temporal processing skills that underpin rhythm perception, phonological processing, and eventually reading fluency.",
             "setup":["Clap hands -- you set the tempo"],
             "play":["Clap fast, fast, fast","Clap slow... slow... slow...","Child matches: clap the same speed","Try running: fast music, slow music"],
             "say":['"Clap as fast as I clap -- match me!"','"Now slow... your clap has to wait for mine."','"What does fast feel like? What does slow feel like?"'],
             "if_happens":"Child defaults to one speed regardless",
             "avoid":'"Match me -- you are going too fast."',
             "better":'"You have a favourite speed! Now the challenge: go HALF as fast as you naturally want to. That is the hard part."',
             "why":"Temporal processing -- the ability to perceive and reproduce time intervals and rhythmic patterns -- is a core component of phonological awareness. Research shows that children with strong temporal processing skills develop reading more easily because they can distinguish the fine timing differences between phonemes (the rapid temporal structure of speech). Clapping and movement activities directly train temporal processing.",
             "tool":"Tempo Follower",
             "phrases":['"Your hands can follow time."','"Fast and slow are just different distances between beats."'],
             "skills":"Tempo perception, temporal processing, rhythmic entrainment."},
        4:  {"title":"Echo Echo","emoji":"🔁","skill":"Auditory Memory","materials":"None",
             "milestone":"Milestone: Repeating back a sound sequence -- echo games -- builds phonological working memory: the ability to hold and reproduce sound sequences in the mind. This is the core mechanism of language learning.",
             "setup":["You make a sound pattern -- child echoes it"],
             "play":["Clap a rhythm: clap-clap-pause-clap","Child echoes exactly","Increase complexity: 3, then 4, then 5 beats","Try with voice sounds: ba-ba-ba-boo"],
             "say":['"Echo everything I do -- exactly."','"ba-ba-BA -- now you."','"I will make it harder -- are you ready?"'],
             "if_happens":"Child cannot reproduce more than 2 beats",
             "avoid":'"Listen more carefully -- there were 3 claps."',
             "better":'"2 is great -- your echo memory holds 2 right now. Let us practise 2 perfectly. Then we go to 3."',
             "why":"Phonological working memory -- the ability to hold sound sequences in mind long enough to process and reproduce them -- is one of the strongest predictors of language acquisition and reading skill. Echo games directly and powerfully train this capacity. Research shows that improving phonological working memory through sound games before age 4 produces measurable improvements in vocabulary acquisition and pre-reading skills.",
             "tool":"Echo Maker",
             "phrases":['"Hold the sound in your mind -- then give it back."','"Your memory is growing one beat at a time."'],
             "skills":"Phonological working memory, auditory recall, sequential processing."},
        5:  {"title":"Sound Walk","emoji":"🚶","skill":"Environmental Acoustics","materials":"Any walk",
             "milestone":"Milestone: Categorising sounds by their source -- natural, mechanical, human -- develops auditory categorisation skills that transfer to phoneme categorisation in reading.",
             "setup":["Take a walk -- any environment","Categories: human, nature, machine"],
             "play":["Listen and categorise each sound","Human: voices, footsteps, singing","Nature: wind, birds, leaves, water","Machine: cars, phones, appliances"],
             "say":['"That sound -- what made it? Human, nature, or machine?"','"Listen for the next sound -- what category?"','"Which category has the most sounds here?"'],
             "if_happens":"Child gets the categories confused",
             "avoid":'"No -- a car is a machine."',
             "better":'"Hmm -- a car is driven by a human but is it a machine or a human that makes the sound? What do you think? Either answer is interesting."',
             "why":"Auditory categorisation -- grouping sounds by their source type -- develops the categorical auditory perception that phonics instruction requires. When children learn to group sounds by shared properties, they are building the same cognitive operation they will use to group phonemes by shared features (voiced, voiceless, stop, fricative). The grey area cases (a car driven by a human) are particularly valuable for building cognitive flexibility.",
             "tool":"Sound Sorter",
             "phrases":['"What made that sound? That tells you the category."','"Every sound has a maker."'],
             "skills":"Auditory categorisation, sound source attribution, categorical perception."},
        6:  {"title":"Make Your Own Instrument","emoji":"🥁","skill":"Musical Making","materials":"Containers, rice, rubber bands",
             "milestone":"Milestone: Making a simple instrument and playing it introduces the concepts of vibration (sound is made by things moving) and resonance (different materials make different sounds).",
             "setup":["Rice in a sealed container: a shaker","Rubber band over a box: a plucker","Pot and wooden spoon: a drum"],
             "play":["Make each instrument","Play each one -- compare the sounds","Which is highest? Lowest? Loudest?","Play a simple rhythm together"],
             "say":['"What makes this sound different from that sound?"','"The rubber band vibrates -- that is what makes the sound."','"Play your instrument with mine -- find the rhythm."'],
             "if_happens":"Child hits instruments randomly with no rhythm",
             "avoid":'"Play a rhythm -- not just random hits."',
             "better":'"What a sound! Now I will play a pattern -- you join in when you find the beat."',
             "why":"Making and playing simple instruments introduces the physics of sound production through direct experience: the child makes the vibration, the child hears the sound. The connection between physical action and acoustic result is the foundational physics of acoustics. Understanding that sound is vibration is one of the most counterintuitive physical insights and having made the vibration yourself is the most powerful way to encounter it.",
             "tool":"Vibration Maker",
             "phrases":['"Sound is things vibrating."','"You made the sound -- you made the vibration."'],
             "skills":"Sound physics, musical making, rhythm production."},
        7:  "reflection",
        8:  {"title":"Nursery Rhyme Time","emoji":"🎵","skill":"Phonological Awareness","materials":"Nursery rhymes",
             "milestone":"Milestone: Nursery rhymes are the most effective phonological awareness training available for young children. Their rhyme and rhythm draw attention to the sound structure of words, which is the primary prerequisite for reading.",
             "setup":["Any nursery rhyme both know","Sit together"],
             "play":["Recite or sing together","Emphasise the rhyming words","Ask: which words rhyme?","Make up a silly new verse"],
             "say":['"Jack and Jill went up the hill -- which two words rhyme?"','"Jill and hill -- they sound the same at the end!"','"Make up a new line -- what rhymes with hill?"'],
             "if_happens":"Child cannot identify the rhyming words",
             "avoid":'"Listen -- Jack and Jill -- hill, fill, mill -- those rhyme."',
             "better":'"Say HILL slowly. Now say FILL slowly. What sounds the same? The ending: ILL ILL. They share an ILL."',
             "why":"Rhyme awareness -- the ability to identify and produce words that share ending sounds -- is one of the most studied and most important phonological awareness skills. Meta-analyses of hundreds of studies confirm that early rhyme awareness is a strong predictor of reading acquisition. Nursery rhymes are optimally designed for this because their rhyming pairs are embedded in meaningful, memorable contexts.",
             "tool":"Rhyme Ears",
             "phrases":['"Rhyming words share the same ending sound."','"If they end the same way, they are rhyme partners."'],
             "skills":"Rhyme awareness, phonological awareness, pre-reading."},
        9:  {"title":"Clap the Syllables","emoji":"👏","skill":"Syllable Awareness","materials":"None",
             "milestone":"Milestone: Syllable segmentation -- breaking words into beats -- is a phonological awareness skill that develops around age 3 and is a prerequisite for phoneme awareness and spelling.",
             "setup":["Choose simple words: cat, butter, elephant"],
             "play":["Clap each syllable: cat = 1 clap","butter = 2 claps: but-ter","elephant = 3 claps: e-le-phant","Try everyone's names"],
             "say":['"How many claps for cat? Clap as you say it: cat -- one!"','"Butterfly: but-ter-fly -- how many?"','"[Child name] -- how many claps is your name?"'],
             "if_happens":"Child claps for each letter rather than syllable",
             "avoid":'"Not each letter -- each beat."',
             "better":'"Say your name in slow motion and clap the big parts -- the natural pauses. Like humming it."',
             "why":"Syllable segmentation is a critical phonological awareness skill that develops before phoneme awareness and acts as a bridge to it. Children who can segment words into syllables learn letter-sound correspondences more easily because they can divide the word into manageable units before identifying the individual sounds within each unit. Name-clapping is particularly engaging because children care deeply about their own names.",
             "tool":"Syllable Clapper",
             "phrases":['"Every word has a beat count."','"Clap the word to find out."'],
             "skills":"Syllable segmentation, phonological awareness, word structure."},
        10: {"title":"What Rhymes With Cat?","emoji":"🐱","skill":"Rhyme Production","materials":"None",
             "milestone":"Milestone: Producing a rhyme -- not just identifying one -- requires active phonological manipulation: isolating the onset and substituting a new one while keeping the rime. This is a significant phonological achievement.",
             "setup":["Start with easy words: cat, hat, bat"],
             "play":["What rhymes with cat? Hat, bat, rat, sat...","Try mat, fat, that","What rhymes with dog? Log, fog, bog, hog","Silly words count too: zog, mog, brog"],
             "say":['"Cat -- what rhymes with cat? What ends the same?"','"Hat rhymes -- good! What else?"','"Silly words count if they rhyme: zat, gat -- do they rhyme with cat?"'],
             "if_happens":"Child says words that do not rhyme",
             "avoid":'"That does not rhyme."',
             "better":'"Interesting: cat... [their word]... do they end the same? Say them slowly. Cat ends: -at. Does yours end -at?"',
             "why":"Rhyme production requires the child to segment a word into its onset (the beginning consonant or consonant cluster) and rime (the vowel and everything after), then substitute a new onset while preserving the rime. This onset-rime segmentation is a phonological operation directly preparatory for initial consonant substitution in spelling (c-at, h-at, r-at). Accepting nonsense words is important: the phonological operation is the same.",
             "tool":"Rhyme Maker",
             "phrases":['"Change just the beginning -- keep the -at ending."','"Even silly rhymes count."'],
             "skills":"Rhyme production, onset-rime segmentation, phonological manipulation."},
        11: {"title":"S is for Snake","emoji":"🐍","skill":"Letter-Sound Correspondence","materials":"None",
             "milestone":"Milestone: Learning that letters represent sounds -- not meanings -- is one of the most foundational literacy concepts. Children who understand this alphabetic principle learn to read dramatically more easily.",
             "setup":["Choose 3 letters that make distinctive sounds: s, m, b"],
             "play":["S says sss -- like a snake: sss","M says mmm -- like yummy food: mmm","B says buh -- like a pop: buh","Find things that start with each sound"],
             "say":['"S says sss -- what starts with that sound? Sssnake, ssun, sssock..."','"Listen: which starts with sss -- cat or sun?"','"You know the sounds -- that is reading starting."'],
             "if_happens":"Child confuses letter name with letter sound (says the letter name instead of sound)",
             "avoid":'"The SOUND not the name."',
             "better":'"Good -- you know the letter name! That is great. Now the SOUND -- what does S whisper? sss..."',
             "why":"The alphabetic principle -- understanding that letters systematically represent sounds -- is the single most important literacy concept to develop before formal reading instruction. Many children learn letter names without understanding the sound relationship. Teaching letter sounds directly (using the phoneme, not the letter name) ensures the child builds the correct alphabetic representation. Starting with continuous sounds (s, m, f) is recommended because they can be elongated and isolated.",
             "tool":"Sound of the Letter",
             "phrases":['"Letters are costumes that sounds wear."','"The letter is just the picture -- the sound is what matters."'],
             "skills":"Letter-sound correspondence, alphabetic principle, phonemic awareness."},
        12: {"title":"What Sound Does It Start With?","emoji":"🔤","skill":"Initial Phoneme Identification","materials":"Picture cards or objects",
             "milestone":"Milestone: Identifying the first sound in a word -- initial phoneme awareness -- is a key pre-reading skill that typically develops between 3 and 4 years with explicit practice.",
             "setup":["5-6 common objects or pictures"],
             "play":["Hold up an object: cup","What sound does cup start with? kuh","Try: dog, sun, man, ball, feet","Sort into groups by initial sound"],
             "say":['"Cup -- what is the very first sound? kuh? cuh?"','"Stretch it out: kkkup. What is the first sound?"','"These all start with the same sound: what is it?"'],
             "if_happens":"Child names the first letter instead of the first sound",
             "avoid":'"The sound -- not the letter name."',
             "better":'"Good -- and what sound does that letter make? Cup starts with the kuh sound."',
             "why":"Initial phoneme identification -- isolating the first sound in a word -- is one of the most direct measures of phonemic awareness. Meta-analyses consistently show it is the strongest individual predictor of reading acquisition. The stretch technique (kkkup) makes the initial phoneme more acoustically salient and helps children isolate it from the rest of the word.",
             "tool":"First Sound Stretcher",
             "phrases":['"Stretch the word -- what sound do you hear first?"','"The first sound is the beginning of the word."'],
             "skills":"Initial phoneme awareness, phonological analysis, pre-reading."},
        13: {"title":"Word Families","emoji":"👨‍👩‍👧","skill":"Pattern Phonics","materials":"None",
             "milestone":"Milestone: Word families -- hat, mat, cat, bat -- introduce the concept that words can be systematically related through shared patterns. This pattern recognition is the foundation of decoding strategies in reading.",
             "setup":["Start with the -at family"],
             "play":["cat, hat, bat, mat, rat, sat","All end the same: -at","Change the beginning: c-at, h-at, b-at","Can we make more? flat? chat? What about nonsense: zat?"],
             "say":['"Cat, hat, bat -- they are a family. What do they share?"','"They share the -at ending. Change the beginning and you make a new word."','"How many family members can we find?"'],
             "if_happens":"Child runs out of ideas quickly",
             "avoid":'"Think harder -- there are more."',
             "better":'"Let us go through the alphabet -- if we put each letter before -at, which ones make real words? A... B-at! C-at! D...at? Dat? Is dat a word?"',
             "why":"Word family instruction -- grouping words by shared patterns -- teaches the rime unit (the vowel + following consonants in a syllable) as a stable, reusable chunk. This rimes-as-units approach to reading is more efficient than letter-by-letter decoding for English because many English words share rimes. Research shows that word family instruction significantly speeds up early decoding acquisition.",
             "tool":"Word Family Tree",
             "phrases":['"Same ending, different beginning -- same family."','"Changing the first sound makes a new word."'],
             "skills":"Rime units, word family patterns, decoding strategy."},
        14: "reflection",
        15: {"title":"Favourite Song","emoji":"🎤","skill":"Music and Memory","materials":"A loved song",
             "milestone":"Milestone: Memorising and performing a favourite song builds phonological memory, vocabulary, and emotional connection to language -- all foundational literacy factors.",
             "setup":["Choose a favourite song together","Sing it through once"],
             "play":["Sing it all the way through","Try singing it slower -- enunciate every word","What does [specific word] mean?","Change one word -- what happens?"],
             "say":['"Let us sing every word -- clearly."','"What does this word mean in the song?"','"What if I change this word? Does the meaning change?"'],
             "if_happens":"Child only remembers parts and fills the rest with mumbling",
             "avoid":'"You have to know all the words."',
             "better":'"Sing the parts you know -- BOLD. Mumble the parts you are learning -- quiet. Let us find out exactly which parts you know."',
             "why":"Singing memorised songs builds phonological memory -- the specific memory system for sound sequences. Research shows that children who know more songs at age 3 have larger vocabularies at age 5, because songs provide multiple exposures to vocabulary in a phonologically rich, memorable context. Changing a word demonstrates semantic meaning -- the child can feel that something is wrong when the meaning breaks.",
             "tool":"Song Words",
             "phrases":['"Songs are vocabulary that comes with a tune attached."','"Every word in a song has a meaning -- find them."'],
             "skills":"Phonological memory, vocabulary, semantic awareness."},
        16: {"title":"Body Percussion","emoji":"🥁","skill":"Rhythm Embodiment","materials":"None",
             "milestone":"Milestone: Body percussion -- making rhythms by clapping, tapping, stomping -- builds rhythmic fluency through kinesthetic encoding, which supports both musical ability and phonological awareness.",
             "setup":["Stand together with space to move"],
             "play":["Create a body rhythm: stamp, stamp, clap","Increase complexity: stamp, clap, tap knee, clap","Create a 4-beat pattern together","Perform it at two different tempos"],
             "say":['"Stamp, stamp, clap -- can you do that?"','"Now with me: stamp, clap, tap knee, clap -- GO!"','"Same pattern, twice as fast -- ready?"'],
             "if_happens":"Child cannot maintain the 4-beat pattern",
             "avoid":'"Concentrate -- you keep losing the pattern."',
             "better":'"3 beats first. Master 3. Then we add the 4th. Ready for 3? Stamp, stamp, clap -- go!"',
             "why":"Body percussion activities build rhythmic fluency through proprioceptive and motor encoding. Research in music education shows that body percussion is more effective than instrument playing for developing basic rhythmic competence in young children because the body-as-instrument removes the additional tool-handling cognitive load. The dual-tempo task builds temporal flexibility -- the ability to shift between rhythmic speeds.",
             "tool":"Body Beat",
             "phrases":['"Your body is a drum kit."','"The beat lives in your body."'],
             "skills":"Rhythmic fluency, body percussion, temporal flexibility."},
        17: {"title":"Alphabet Song","emoji":"🔤","skill":"Alphabet Knowledge","materials":"None",
             "milestone":"Milestone: Knowing the alphabet song is a prerequisite for alphabet knowledge, which is consistently one of the strongest predictors of early reading success.",
             "setup":["Sit together","Sing the alphabet slowly"],
             "play":["Sing the alphabet song through once","Identify your child name letters","Point to letters in the environment","Which letters do you see most today?"],
             "say":['"Let us sing through all 26 -- slowly."','"Which letter is in your name? [Sing to that letter and point]."','"Look around -- what letters can you find?"'],
             "if_happens":"Child runs through at full speed and cannot isolate individual letters",
             "avoid":'"Slow down -- I want to hear each letter."',
             "better":'"Impressive speed! Now the challenge: I will point to stop. Wherever I stop, you tell me which letter you are on."',
             "why":"Alphabet knowledge -- knowing the names and forms of all 26 letters -- is the strongest predictor of reading at school entry among measurable pre-literacy skills. The alphabet song is the most efficient delivery mechanism for letter names because the melody acts as a mnemonic scaffold. Connecting letters to the child name creates a personally meaningful anchor for the abstract symbol system.",
             "tool":"Name Letters",
             "phrases":['"Your name uses letters from the whole alphabet."','"Each letter has a sound and a shape."'],
             "skills":"Alphabet knowledge, letter recognition, literacy motivation."},
        18: {"title":"Make Up a Song","emoji":"🎼","skill":"Creative Music","materials":"None",
             "milestone":"Milestone: Composing an original song -- however simple -- builds musical creativity, phonological awareness (manipulating sounds deliberately), and the composer identity that motivates future musical engagement.",
             "setup":["Think of a simple topic: today, a pet, a food"],
             "play":["Make up a 2-line song about the topic together","It does not have to rhyme","Repeat it to memorise it","Add a verse"],
             "say":['"Let us make up a song about breakfast -- what do we eat?"','"Give me a line -- any words in any order -- then we find a tune."','"We made a song that never existed before."'],
             "if_happens":"Child says they cannot make up a song",
             "avoid":'"Just try -- any words."',
             "better":'"Describe breakfast in 5 words. Those ARE the first line. Ready? Go."',
             "why":"Original song composition at age 3 produces a qualitatively different musical experience than performance: the child is the author, not the interpreter. This authorial identity -- I make music, not just sing music -- is one of the most powerful foundations for lifelong musical engagement. Even a 2-line silly song meets the definition of composition and produces the authorial cognitive and motivational experience.",
             "tool":"Song Author",
             "phrases":['"You made a song that has never been sung before."','"There are no wrong words in your song -- it is yours."'],
             "skills":"Musical creativity, phonological play, authorial identity."},
        19: {"title":"Rhyming Stories","emoji":"📚","skill":"Literary Phonology","materials":"A rhyming picture book",
             "milestone":"Milestone: Rhyming books integrate phonological awareness (noticing rhymes) with narrative comprehension -- the dual language-literacy activation that produces the strongest literary development.",
             "setup":["A rhyming book: Dr Seuss, Julia Donaldson, Roald Dahl poems"],
             "play":["Read with exaggerated rhyme emphasis","Pause before the rhyming word -- let child complete","After reading: find the rhyme pairs","Make up a new rhyming verse together"],
             "say":['"The cat came back... wearing a very tall... (pause)"','"HAT -- did you know it was coming? How?"','"What other rhymes could we use for that verse?"'],
             "if_happens":"Child says random non-rhyming words to fill the gap",
             "avoid":'"No -- it has to rhyme."',
             "better":'"[Their word] -- does that rhyme with [previous rhyme word]? Say them together: cat... [their word]. Does the ending sound the same?"',
             "why":"Completing rhymes in rhyming texts is one of the most engaging and effective phonological awareness activities because it combines prediction (what comes next?), phonological decision (what rhymes?), and meaning (does it make sense?). All three processes are active simultaneously. The literary context also builds the motivation to engage with text -- the child wants to know what comes next.",
             "tool":"Complete the Rhyme",
             "phrases":['"Your brain knew what came next -- it heard the pattern."','"Rhyming stories make your reading brain."'],
             "skills":"Rhyme completion, phonological prediction, narrative comprehension."},
        20: {"title":"Song Vocabulary Hunt","emoji":"🔍","skill":"Vocabulary Expansion","materials":"A familiar song",
             "milestone":"Milestone: Finding and defining unusual vocabulary in songs -- what does topsy-turvy mean? -- builds vocabulary breadth that is one of the strongest predictors of reading comprehension.",
             "setup":["A song with interesting vocabulary: traditional songs have many"],
             "play":["Sing through once","Stop at an interesting word: what does [word] mean?","Discuss and demonstrate","Use the word in a new sentence"],
             "say":['"Stop -- what does that word mean? I want to know if you know."','"Let us figure it out from the song -- what is happening around the word?"','"Use it in a sentence about today."'],
             "if_happens":"Child does not know and shrugs",
             "avoid":'"It means [definition] -- remember that."',
             "better":'"I do not know either -- let us use what is happening in the song to guess. What is happening right before the word?"',
             "why":"Vocabulary knowledge -- knowing the meanings of words -- is the most powerful predictor of reading comprehension in both early and later schooling. Songs are unusually rich vocabulary delivery systems because they expose children to formal register vocabulary in a memorable, emotionally engaging context. The context-based definition strategy (figuring out from what is happening around the word) builds the text-inference skill that reading comprehension demands.",
             "tool":"Word Detective",
             "phrases":['"Use what is around the word to guess the meaning."','"New words make your reading stronger."'],
             "skills":"Vocabulary, context inference, reading comprehension foundation."},
        21: "reflection",
        22: {"title":"Sound Story","emoji":"🎭","skill":"Sound Effects","materials":"A simple story",
             "milestone":"Milestone: Adding sound effects to a story integrates narrative comprehension with phonological creativity -- the child must choose appropriate sounds that match the story events.",
             "setup":["A simple story -- you or a book","Child is the sound effects maker"],
             "play":["Tell the story -- child adds sounds for events","The door opened: creeeak","The thunder: BOOM","The baby laughed: hehehe","Record a version with all sound effects"],
             "say":['"You are the sound effects department -- make a sound for everything I describe."','"The wind: what sound?"','"The sound you chose was PERFECT."'],
             "if_happens":"Child does the same sound for everything",
             "avoid":'"That is not the right sound for that."',
             "better":'"Wind and rain have different sounds -- whisper both and see which feels more right for each."',
             "why":"Sound effect selection requires the child to create a phonological representation of a non-vocal sound that is appropriate to the narrative event. This is a form of phonological creativity that builds both sound awareness and narrative-sound correspondence. The child must understand the story event well enough to represent it acoustically -- which requires both comprehension and creative phonological output.",
             "tool":"Sound Storyteller",
             "phrases":['"The right sound makes the story come alive."','"You hear the story in your mind -- what sound is in that picture?"'],
             "skills":"Sound effects, phonological creativity, narrative comprehension."},
        23: {"title":"Tongue Twisters","emoji":"👅","skill":"Phonological Fluency","materials":"None",
             "milestone":"Milestone: Tongue twisters train phonological fluency -- the ability to produce rapid sound sequences accurately -- which underlies clear speech, expressive reading, and phonological awareness.",
             "setup":["Start slow: Peter Piper, She sells seashells"],
             "play":["Say slowly: She sells seashells by the seashore","Speed up gradually","Laugh at mistakes -- that is the point","Make up your own tongue twister: [sound] [word] [word] [word]"],
             "say":['"Say this slowly: she sells seashells..."','"Faster! Even faster!"','"We all mess it up -- that is the fun part."'],
             "if_happens":"Child gets frustrated at making mistakes",
             "avoid":'"Do not worry -- everyone messes up tongue twisters."',
             "better":'"The mistakes are the game! The faster we try, the more we mess up. I want to hear yours go wrong. Ready?"',
             "why":"Tongue twisters are challenging because they require rapid articulatory switching between similar phonemes. The errors that occur when speaking fast reveal the phonological structure of speech -- the specific places where sounds compete. This metalinguistic awareness (noticing the sound structure of language) is a component of phonological awareness that directly supports reading. Normalising and celebrating errors removes the shame that would otherwise suppress practice.",
             "tool":"Fast Talker",
             "phrases":['"Mistakes in tongue twisters are the sound of learning."','"The faster you try, the more your mouth learns."'],
             "skills":"Phonological fluency, articulatory precision, metalinguistic awareness."},
        24: {"title":"Poetry Time","emoji":"📜","skill":"Literary Language","materials":"A simple poem",
             "milestone":"Milestone: Exposure to poetry at this age -- its rhythm, imagery, and condensed language -- builds literary language sensitivity that distinguishes strong readers from weak ones throughout schooling.",
             "setup":["A short poem -- any age-appropriate poem will do"],
             "play":["Read it once straight through","Read it again, emphasising rhythm","Ask: what pictures does this poem make in your mind?","Memorise the first two lines together"],
             "say":['"Listen to the music of these words..."','"What do you see in your mind when I say that?"','"Let us memorise two lines -- say them with me."'],
             "if_happens":"Child says poems are boring",
             "avoid":'"Give it a chance -- it gets better."',
             "better":'"Tell me what a poem would sound like if you made it. What would it be about?"',
             "why":"Literary language -- the elevated, condensed, rhythm-driven language of poetry -- builds a different kind of linguistic sensitivity than conversational language. Children exposed to poetry develop stronger metaphor comprehension, richer vocabulary, and greater sensitivity to the emotional and aesthetic qualities of language. These are not just literary skills -- they are reading comprehension skills that differentiate proficient from struggling readers.",
             "tool":"Poem Picture",
             "phrases":['"What pictures does the poem make in your mind?"','"Poems say more with fewer words."'],
             "skills":"Literary language, imagery comprehension, poetic sensitivity."},
        25: {"title":"Alliteration Adventure","emoji":"🎯","skill":"Initial Sound Awareness","materials":"None",
             "milestone":"Milestone: Alliteration -- the repetition of initial sounds -- draws explicit attention to the initial phonemes of words, building the initial phoneme awareness that is most directly predictive of reading.",
             "setup":["Start with a tongue-in-cheek alliterative phrase"],
             "play":["Seven silly seals sat singing","Which sound repeats?","Make your own: five [sound] words all starting with the same sound","Try your name: [name] loves [alliterative words]"],
             "say":['"Seven silly seals sat singing -- which sound keeps coming back?"','"S! All start with sss."','"Your turn: make a silly sentence where EVERY word starts with B."'],
             "if_happens":"Child uses the same word repeatedly instead of different words",
             "avoid":'"Different words -- not the same word."',
             "better":'"Big big big -- all Bs! Now find a DIFFERENT B word. What other B words do you know?"',
             "why":"Alliteration activities are among the most effective phonological awareness exercises because they require sustained attention to initial phonemes across multiple words simultaneously. The child must both generate words AND monitor that each starts with the target sound -- a dual-processing task. Research confirms that alliteration awareness at age 3-4 predicts reading accuracy at age 6-7.",
             "tool":"Same Start Sound",
             "phrases":['"All start with the same sound -- that is alliteration."','"Find the sound that starts every word."'],
             "skills":"Alliteration, initial phoneme awareness, phonological monitoring."},
        26: {"title":"Sing About Your Day","emoji":"🌟","skill":"Narrative Song","materials":"None",
             "milestone":"Milestone: Singing about real events -- turning the day into a song -- integrates narrative sequencing, phonological awareness, and personal language into a uniquely bonding daily ritual.",
             "setup":["End of day -- review together"],
             "play":["Make up a song about what happened today","Each event gets a line","No tune needed -- just rhythmic speaking is fine","Sing it together twice"],
             "say":['"Let us sing today. What happened first?"','"We woke up and had... (sing it)"','"Now you add the next thing that happened."'],
             "if_happens":"Child wants to go to bed and not do the activity",
             "avoid":'"We have to do it -- it is just 5 minutes."',
             "better":'"We can do 1 minute -- just one thing from today, sung in any way. Even just humming the memory."',
             "why":"The daily narrative song is one of the most powerfully integrative activities in this curriculum: it combines episodic memory consolidation (reviewing the day), narrative sequencing (events in order), phonological activity (the song format), and bonding (sharing the day together). Research on autobiographical memory consolidation shows that evening review significantly strengthens next-day retention of day events.",
             "tool":"Day Song",
             "phrases":['"Today had a tune -- let us find it."','"The day is a story you sang."'],
             "skills":"Narrative sequencing, autobiographical memory, daily ritual."},
        27: {"title":"Concert for the Family","emoji":"🎪","skill":"Performance","materials":"Songs learned this month",
             "milestone":"Milestone: Performing songs for an audience builds performance confidence, the sharing of creative work, and the experience of a positive audience response that motivates future musical engagement.",
             "setup":["Gather family (or just parent and child)","Prepare 3 songs to perform"],
             "play":["Announce the concert: Welcome to our show","Perform the songs one by one","Take a bow after each one","Audience claps and responds"],
             "say":['"Welcome to our concert! Tonight we will perform three songs."','"Please clap at the end of each song."','"Take a bow -- you performed!"'],
             "if_happens":"Child is too shy to perform",
             "avoid":'"You have to perform -- we practised."',
             "better":'"We can perform together -- I am your partner. You are never alone on this stage."',
             "why":"Performance experience -- sharing prepared musical work with a responsive audience -- produces a unique motivational state: the felt sense that one's creative effort is valued by others. This performance motivation is a powerful long-term driver of musical practice. Even one positive performance experience at age 3 can establish a performing identity that persists for decades.",
             "tool":"Performer Heart",
             "phrases":['"You performed -- your songs were real music for real people."','"The audience heard what you made."'],
             "skills":"Performance confidence, creative sharing, musical identity."},
        28: "reflection",
        29: {"title":"Song and Rhyme Book","emoji":"📗","skill":"Literary Documentation","materials":"Paper, crayons, stapler",
             "milestone":"Milestone: A personal song and rhyme book -- containing the music your child knows and loves -- is a literary artefact that builds reading motivation by demonstrating that books contain things the child values.",
             "setup":["Fold pages, staple","Title: My Songs and Rhymes"],
             "play":["Each page: one song or rhyme","Child draws a picture for it","Parent writes the first two lines","Read it together when finished"],
             "say":['"Which songs should go in our book?"','"Draw a picture for this song -- what does it make you see?"','"You have a songbook that is yours."'],
             "if_happens":"Child wants to add every song they know and never stop",
             "avoid":'"We can only fit so many."',
             "better":'"Excellent! Pick your absolute 5 favourites. The rest we save for volume 2."',
             "why":"A personal songbook serves as a literacy motivation artefact: a book that contains content the child specifically values and chose. Research on early literacy motivation shows that children who associate books with personally meaningful content develop stronger reading motivation than those for whom books are only school or parent-chosen. The child as curator of their own literary content is a powerful reading motivation strategy.",
             "tool":"My Book My Songs",
             "phrases":['"This book has YOUR favourite songs -- you chose them."','"Every book started with someone deciding what mattered."'],
             "skills":"Literacy motivation, song curation, book ownership."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 10 Complete: Sound Champion!",
        "summary": "Ten months! This month your child listened deeply, learned rhymes, identified letter sounds, clapped syllables, performed songs, and built the phonological foundation that reading will grow from.",
        "skills_built": ["Auditory attention and sound discrimination", "Rhyme awareness and production", "Syllable clapping and segmentation", "Initial letter sounds and alliteration", "Musical performance and creative song-making"],
        "month_next_teaser": "Next month: Strong and Capable. Your child will practise independence skills -- dressing, pouring, zipping, helping -- building the I can do it confidence that school entry requires.",
    },
    "reflection_activities": {
        7:  {"activity": "Sound Count", "desc": "Close your eyes for 60 seconds. How many sounds can you identify? Count and compare to Day 1."},
        14: {"activity": "Rhyme Challenge", "desc": "How many words rhyme with cat? Set a record. Beat it next week."},
        21: {"activity": "Letter Sound Quiz", "desc": "Point to 5 things in the room. What sound does each start with? How many can you do in 60 seconds?"},
        28: {"activity": "Concert Rehearsal", "desc": "Choose your 3 best songs from this month. Practise them for tomorrow's concert."},
    },
}
