"""Months 11 and 12 curriculum data"""

M11 = {
    "name": "Strong & Capable",
    "toolkit_label": "2--3 Years &middot; Month 11",
    "weeks": {
        1: {"title": "I Can Do It Myself", "subtitle": "The words that change everything"},
        2: {"title": "Try, Try Again", "subtitle": "Persistence as a learnable skill"},
        3: {"title": "Self-Care Skills", "subtitle": "Dressing, pouring, zipping -- real competence"},
        4: {"title": "Helping Out", "subtitle": "Contribution as identity"},
    },
    "days": {
        1:  {"title":"I Did It!","emoji":"✊","skill":"Self-Efficacy","materials":"None",
             "milestone":"Milestone: Self-efficacy -- the belief that one is capable of achieving things through effort -- is one of the strongest predictors of life outcomes. It is built through authentic achievement experiences, not praise.",
             "setup":["Choose a small challenge together"],
             "play":["Set a challenge: stack 5 blocks without falling","Attempt it -- fail, try again","When it succeeds: I DID IT!","Notice the feeling: what does that feel like?"],
             "say":['"Set a challenge -- try to stack 5 blocks."','"Try again -- you almost had it."','"I DID IT! Notice that feeling -- that is what achievement feels like."'],
             "if_happens":"Child gives up immediately",
             "avoid":'"Keep trying -- do not give up."',
             "better":'"OK -- step back. Make the challenge smaller. Stack 3 blocks first. Achieve 3. Then we go to 5."',
             "why":"Self-efficacy develops through mastery experiences -- actually achieving something through effort. Albert Bandura's research established that self-efficacy is domain-specific and built incrementally through progressively challenging experiences. The key is calibrating the challenge so failure is possible but not overwhelming. Making the challenge smaller (from 5 to 3 blocks) is not lowering the bar -- it is calibrating the bar correctly.",
             "tool":"Achievement Feeling",
             "phrases":['"Notice the feeling in your body when you do it."','"That feeling is what trying hard produces."'],
             "skills":"Self-efficacy, mastery experience, challenge calibration."},
        2:  {"title":"Try a New Food","emoji":"🥝","skill":"Courage","materials":"One new food",
             "milestone":"Milestone: Food neophobia -- reluctance to try new foods -- peaks between 2 and 5 years. Small, structured exposures without pressure build the courage to try new things in all domains.",
             "setup":["One small piece of a new food","Zero pressure -- participation is the goal"],
             "play":["Look at the food: describe it","Smell it","Touch it","MAYBE taste it -- entirely optional","Celebrate any engagement"],
             "say":['"Look at this new food -- describe what you see."','"Smell it -- what does it remind you of?"','"You do not have to taste it. Smelling is brave enough."'],
             "if_happens":"Child refuses all contact",
             "avoid":'"Just touch it -- it will not hurt you."',
             "better":'"You looked at it. That counts. Same food tomorrow -- maybe a different level of brave."',
             "why":"Food exposure research shows that repeated non-pressured exposure to new foods -- even without eating -- gradually reduces neophobia. The critical variables are: no pressure, consistent exposure, and positive association (parent enjoys it, parent is not anxious). Celebrating smell, touch, and look as valid forms of bravery removes the all-or-nothing eating pressure and builds the graduated approach tolerance that eventually produces eating.",
             "tool":"Brave and Curious",
             "phrases":['"Looking is the first brave step."','"Being curious about new things is a kind of courage."'],
             "skills":"Courage, food tolerance, approach behaviour, graduated exposure."},
        3:  {"title":"Buttons!","emoji":"🧥","skill":"Fine Motor Independence","materials":"A shirt or jacket with large buttons",
             "milestone":"Milestone: Buttoning a button requires bilateral coordination, pinch grip, visual-motor integration, and spatial reasoning -- all channelled into a self-care task. It typically develops between 2.5 and 4 years.",
             "setup":["A garment with 2-3 large buttons","Sit together with good lighting"],
             "play":["Parent demonstrates slowly: hold button in one hand, guide through hole with other","Child tries the first button","Celebrate any progress: edge of button through = success","Two buttons is a very good day"],
             "say":['"Hold the button -- now push it through the hole."','"You got the edge through -- that is the hardest part!"','"Two buttons! Your hands just got smarter."'],
             "if_happens":"Child cannot get button through and throws garment down",
             "avoid":'"Try again -- you can do it."',
             "better":'"The button won this time. The button will not win forever. Your hands are practising. Let us try one more and then stop for today."',
             "why":"Buttoning is one of the most challenging fine motor self-care tasks because it requires bilateral manipulation of a small object through a restricted space. The motor planning required (three-stage sequence: hold, align, push through) is cognitively demanding alongside the physical difficulty. Normalising the difficulty and attributing improvement to practice rather than innate ability builds growth mindset around physical skill acquisition.",
             "tool":"Hands Getting Smarter",
             "phrases":['"Every try makes your hands a little smarter."','"Buttons are hard for everyone -- even grown-ups at first."'],
             "skills":"Fine motor, bilateral coordination, self-care, persistence."},
        4:  {"title":"Pour Yourself","emoji":"🥛","skill":"Independence","materials":"Small pitcher, cup",
             "milestone":"Milestone: Pouring from a small pitcher into a cup develops fine motor control, spatial reasoning, and the identity of I can do this myself -- one of the most motivating feelings in early childhood.",
             "setup":["Small pitcher with a little water","Wide-mouthed cup","Mat under everything"],
             "play":["Child pours their own cup of water","Go slowly: tip slowly, watch the level","Stop before it overflows","Celebrate: you poured for yourself"],
             "say":['"Hold the pitcher with two hands."','"Tip slowly... watch the water level... stop!"','"You just poured for yourself. You can do this every day now."'],
             "if_happens":"Child pours too fast and spills",
             "avoid":'"Too fast -- you spilled."',
             "better":'"Spill! That is useful information -- too fast. How slow should the tip be? Show me the slowest possible pour."',
             "why":"Pouring is one of the practical independence milestones that dramatically changes the child sense of capability. The practical consequence (I can get my own water) is motivating in a way that abstract skill exercises are not. Treating the spill as information (too fast = spill) rather than failure maintains the growth orientation and builds the self-correcting habit that underlies all skill mastery.",
             "tool":"Self-Serve",
             "phrases":['"You can do this for yourself -- every day."','"Every skill you learn is one more freedom."'],
             "skills":"Fine motor independence, spatial awareness, self-care."},
        5:  {"title":"Zip It Up","emoji":"🧲","skill":"Fine Motor","materials":"A jacket with a zip",
             "milestone":"Milestone: Zipping requires locating a small metal tooth, inserting it precisely, holding both sides of the zip, and pulling -- a four-step fine motor sequence that most children master between 3 and 4 years.",
             "setup":["A jacket with a zip","Demonstrate very slowly"],
             "play":["Locate the bottom of the zip: find the metal box","Insert the zip tooth -- demonstrate","Hold both sides and pull up","Celebrate any progress: zip 5cm up is a win"],
             "say":['"Find the bottom -- the little metal box."','"Insert the tooth -- this is the hard part."','"PULL UP -- keep going!"'],
             "if_happens":"Child cannot get the tooth inserted and screams",
             "avoid":'"Look -- it goes in here."',
             "better":'"The tooth is tricky -- even I find it hard. Let me hold one side and you do the insert. Team zip."',
             "why":"Zipping is a complex fine motor task that is more cognitively demanding than it appears because the insertion step requires precise alignment under tension. Teaching it as a team task (one person holds, one inserts) provides scaffolded practice that builds competence in each component before the full sequence is required. This is the zone of proximal development principle applied to fine motor skill.",
             "tool":"Team Skills",
             "phrases":['"Some skills need two people at first."','"Learning something hard is a team effort sometimes."'],
             "skills":"Fine motor, bilateral coordination, self-care independence."},
        6:  {"title":"Tie My Shoes (Start)","emoji":"👟","skill":"Sequential Motor Task","materials":"Shoes with laces or a practice lacing board",
             "milestone":"Milestone: Shoe tying is typically mastered between ages 4 and 6, but introducing the bunny ears concept at age 3 builds the sequential motor planning that enables mastery when the fine motor skills mature.",
             "setup":["Shoe with laces or lacing practice board","Sit at child eye level"],
             "play":["Demonstrate the first step: cross and through (make an X and pull through)","That is the only step today","Practise just that step 5 times","Celebrate: you know Step 1 of shoe tying"],
             "say":['"Cross the laces: X."','"Now one goes under and through."','"That is Step 1. You know Step 1. That is real progress."'],
             "if_happens":"Child wants to skip to the full knot immediately",
             "avoid":'"No -- master step 1 first."',
             "better":'"Great ambition! Here is the full knot. Try it -- you will see why we start with step 1. Then we practise step 1 until it is automatic."',
             "why":"Teaching shoe tying in stages -- single step at a time -- uses the task analysis method from occupational therapy. Breaking a multi-step sequential motor task into individual components and mastering each before adding the next produces faster and more durable acquisition than attempting the full sequence from the start. Celebrating partial mastery (you know Step 1) builds the incremental confidence that sustains practice.",
             "tool":"One Step at a Time",
             "phrases":['"Step 1 is the whole job today."','"Mastering one step is real progress."'],
             "skills":"Sequential motor learning, self-care readiness, task analysis."},
        7:  "reflection",
        8:  {"title":"Try Again","emoji":"🔄","skill":"Persistence","materials":"Any challenging task from this week",
             "milestone":"Milestone: Persistence -- returning to a task after failure -- is one of the most powerful predictors of achievement. It is trainable through explicit practice and positive reframing of failure.",
             "setup":["Return to something that was hard earlier this week"],
             "play":["Try it again: buttons, puzzle, block tower","If it fails: say TRY AGAIN as a positive signal","Keep track: how many tries before success?","Celebrate the number of tries, not just the success"],
             "say":['"Let us try again -- we left this unfinished."','"How many tries will it take? Let us count."','"6 tries! That is 6 things you learned about how NOT to do it."'],
             "if_happens":"Child succeeds on the first try",
             "avoid":'"Good -- now move on."',
             "better":'"First try success! That means your practice from before stored in your muscles. Make it harder now."',
             "why":"Counting tries rather than only celebrating success reframes effort itself as the achievement. Thomas Edison's famous quote (I have not failed, I have found 10,000 ways that do not work) is a scientifically accurate description of the learning process. Children who develop the habit of counting their tries develop a growth orientation toward difficulty that is one of the most durable educational advantages.",
             "tool":"Try Counter",
             "phrases":['"How many tries so far? Each one is information."','"The tries are the learning -- the success is just the end of the tries."'],
             "skills":"Persistence, growth mindset, effort valuation."},
        9:  {"title":"The Challenge Jar","emoji":"🫙","skill":"Self-Chosen Challenge","materials":"Paper strips, a jar",
             "milestone":"Milestone: Self-chosen challenges -- selected from a jar -- develop autonomy, which is one of the three basic psychological needs (autonomy, competence, relatedness) that drive intrinsic motivation.",
             "setup":["Write 5 challenges on paper strips (child contributes ideas)","Put in a jar"],
             "play":["Child draws a challenge","Attempts it","If too hard: choose again (no penalty)","Track over the week: which challenges were mastered?"],
             "say":['"Draw your challenge."','"You chose this one -- let us try."','"Too hard today? That is fine -- put it back for another day."'],
             "if_happens":"Child only picks easy challenges",
             "avoid":'"Pick a harder one."',
             "better":'"You mastered the easy ones! Put them aside -- they are too easy now. Only the unmastered ones remain. Good -- those are next."',
             "why":"The challenge jar structures self-selection of appropriate challenges, which preserves autonomy (child chooses) while building competence (challenges are real). The no-penalty return option removes the fear of choosing a challenge too hard -- which eliminates the risk-aversion that otherwise causes children to consistently under-challenge themselves. Gradually removing mastered challenges naturally increases average difficulty.",
             "tool":"Your Challenge, Your Choice",
             "phrases":['"You chose this challenge -- that makes it yours to master."','"No penalty for trying and coming back later."'],
             "skills":"Autonomy, challenge calibration, growth mindset."},
        10: {"title":"Hard Things Hall of Fame","emoji":"🏆","skill":"Reflection","materials":"Paper, crayons",
             "milestone":"Milestone: Explicitly reviewing and celebrating hard things mastered -- a personal Hall of Fame -- builds the identity of someone who conquers hard things, which is a growth mindset foundation.",
             "setup":["Paper for each one","Draw or dictate"],
             "play":["Think of 3 hard things mastered this month","Draw each one","Write the name under it","Display them: this is your Hall of Fame"],
             "say":['"What is a hard thing you have learned to do?"','"Draw it -- this is your Hall of Fame."','"Every person who is good at anything has a Hall of Fame of hard things behind them."'],
             "if_happens":"Child says they have not mastered anything hard",
             "avoid":'"Yes you have -- think harder."',
             "better":'"What could you not do at the start of this year that you can do now? Even one tiny thing."',
             "why":"The Hall of Fame activity is a growth mindset intervention: it makes prior mastery visible and attributable to effort. Research by Carol Dweck shows that growth mindset develops most effectively when children connect past difficulty with past mastery through their own narrative. Simply telling children they can do hard things is far less effective than showing them the evidence of hard things they have already done.",
             "tool":"Hard Things Champion",
             "phrases":['"You have already done hard things -- look at the evidence."','"Every hard thing you did made you stronger for the next one."'],
             "skills":"Growth mindset, self-reflection, achievement identity."},
        11: {"title":"Getting Dressed Alone","emoji":"👕","skill":"Self-Care","materials":"Simple clothing",
             "milestone":"Milestone: Independent dressing -- putting on a shirt, pants, and socks without help -- is a developmental milestone that typically emerges between 2.5 and 4 years. Each item requires spatial reasoning (which way is front?) and fine motor skill.",
             "setup":["Lay out simple clothes: shirt and pants","Allow enough time -- this will take a while"],
             "play":["Child dresses themselves completely","Parent only watches -- no rushing","Celebrate each item on correctly","If inside-out: accept it (they dressed themselves)"],
             "say":['"You are going to dress yourself today -- all by yourself."','"Which goes on first? You decide."','"You dressed yourself. That is independence."'],
             "if_happens":"Child puts things on inside-out or backward",
             "avoid":'"That is inside-out -- fix it."',
             "better":'"You dressed yourself completely! The tag is showing -- do you want to change it or leave it? Both are fine."',
             "why":"Accepting inside-out and backward clothing (unless the child cares) is a critical principle of independence development. When adults correct every imperfection in a child self-care attempt, the implicit message is: your independent effort is not good enough, let me redo it. This undermines the autonomy and competence that independent dressing is supposed to build. The child who dressed incorrectly but independently accomplished far more than the child who was dressed perfectly by an adult.",
             "tool":"Dressed by Yourself",
             "phrases":['"Inside-out and done by yourself is better than perfect and done by me."','"Independence first -- corrections optional."'],
             "skills":"Dressing independence, spatial reasoning, fine motor, autonomy."},
        12: {"title":"Make the Bed","emoji":"🛏️","skill":"Household Contribution","materials":"Child's bed",
             "milestone":"Milestone: Making the bed -- however imperfectly -- is a contribution to household order that builds responsibility and the identity of someone who takes care of their space.",
             "setup":["Child's bed in the morning","Demonstrate: pillow first, then pull up covers"],
             "play":["Child makes the bed: pillow, flat sheet, duvet","No corrections -- just admire the effort","Ask: how does the room feel with the bed made vs not made?","Make it a daily habit"],
             "say":['"You are making your bed today."','"Pillow first. Then straighten the cover. You decide what looks right."','"How does the room feel with a made bed in it?"'],
             "if_happens":"Child makes it very messily",
             "avoid":'"Let me fix it -- it is still messy."',
             "better":'"Your version of made. That is yours. I will not touch it."',
             "why":"Bed-making research is surprisingly robust: adults who make their beds regularly report higher productivity and wellbeing. The causal mechanism is likely that completing a small task immediately after waking creates early-morning momentum. For children, the key benefit is the identity formation: I am someone who takes care of my space. Imperfect but self-directed bed-making builds this identity more effectively than perfect but parent-corrected bed-making.",
             "tool":"My Space, My Responsibility",
             "phrases":['"Your bed, your way."','"Taking care of your space is taking care of yourself."'],
             "skills":"Household responsibility, spatial awareness, routine, identity."},
        13: {"title":"Clean Up Time","emoji":"🧹","skill":"Environmental Order","materials":"A messy space",
             "milestone":"Milestone: Tidying up and putting things back in their places builds executive function (planning: where does this go?), spatial reasoning (does it fit here?), and the sense of environmental agency.",
             "setup":["A moderately messy space: toys out, books scattered"],
             "play":["Race: can we clean up in 5 minutes?","Sort: where does each thing live?","Parent and child work together","Survey the result: same room, different feeling"],
             "say":['"Race! Can we put everything away in 5 minutes?"','"Where does this live? It needs to go home."','"Look at this room now. What changed? Same room -- different feeling."'],
             "if_happens":"Child refuses to help clean up",
             "avoid":'"You have to help -- you made the mess."',
             "better":'"I am starting with the blocks. You can join when you want. But I will need help with the books."',
             "why":"Framing clean-up as objects going home (each thing has a home) converts a compliance task into a spatial reasoning game. Children who understand storage systems as homes for objects clean more consistently because the task has a completion criterion (everything is home) that is satisfying rather than arbitrary. The before-after survey (same room, different feeling) builds environmental agency -- the sense that your actions change the quality of your space.",
             "tool":"Everything Has a Home",
             "phrases":['"Find where it lives and take it home."','"When things are in their places, the room breathes better."'],
             "skills":"Executive function, spatial reasoning, environmental agency, routine."},
        14: "reflection",
        15: {"title":"Wash Your Hands","emoji":"🧼","skill":"Health Independence","materials":"Soap, water",
             "milestone":"Milestone: Thorough independent hand washing -- soap, 20 seconds, rinse, dry -- is a health skill and an independence milestone that children can achieve by age 3 with practice.",
             "setup":["Bathroom sink accessible","Demonstrate once"],
             "play":["Child washes hands: wet, soap, rub 20 seconds, rinse, dry","Count 20 together (or sing Happy Birthday twice)","Do both sides and between fingers","Check: are they clean? (smell test)"],
             "say":['"Wet, soap, rub for 20 -- count with me."','"Between your fingers too -- that is where germs hide."','"Smell test -- clean hands smell like nothing."'],
             "if_happens":"Child rushes through in 3 seconds",
             "avoid":'"That was not 20 seconds -- do it again."',
             "better":'"3 second hands! That is the fastest wash I have ever seen. Now let us do the slowest -- I will time you. Let us see how long 20 seconds actually feels."',
             "why":"Handwashing is one of the most evidence-based public health behaviours available. Teaching it as a skill to be learned (time it, check it, improve it) rather than a rule to be obeyed builds intrinsic health motivation. The smell test (clean hands smell like nothing) gives the child an independent quality check that removes dependence on adult confirmation -- building self-monitoring capacity.",
             "tool":"Self-Check",
             "phrases":['"Clean hands pass the smell test."','"Your health is something you can take care of yourself."'],
             "skills":"Health independence, self-monitoring, hygiene routine."},
        16: {"title":"Spread the Butter","emoji":"🍞","skill":"Food Independence","materials":"Bread, soft butter, butter knife",
             "milestone":"Milestone: Spreading -- using a knife or blunt spreader -- develops the pushing and lateral hand motion that transfers to pencil use, while building food independence.",
             "setup":["Bread, soft butter, blunt butter knife","Table setup"],
             "play":["Spread butter on bread","Technique: scoop, place, push across","Get coverage: no dry patches","Eat what you made"],
             "say":['"Scoop the butter -- not too much."','"Place it on the bread and push it flat."','"Cover the whole bread -- all the way to the edges."'],
             "if_happens":"Child presses too hard and tears the bread",
             "avoid":'"Lighter -- you are tearing it."',
             "better":'"The bread tore -- that means too much pressure. Like spreading a cloud -- very light."',
             "why":"Spreading requires a specific lateral hand motion -- pushing in one direction while maintaining even pressure -- that is directly related to the horizontal writing stroke. The self-feeding outcome (I made my own food) provides strong intrinsic motivation for practising and refining the skill. The cloud metaphor provides a concrete sensory cue for the appropriate force level.",
             "tool":"Light Touch",
             "phrases":['"Spreading is like moving something gently -- not digging."','"Your hand made your food."'],
             "skills":"Fine motor, lateral hand motion, food independence, pre-writing."},
        17: {"title":"Carry Your Backpack","emoji":"🎒","skill":"Physical Independence","materials":"Child's backpack",
             "milestone":"Milestone: Carrying a personal backpack -- packed by the child -- builds physical independence, spatial planning (what fits, what does not), and the identity of a capable person who manages their own belongings.",
             "setup":["Child packs their own backpack","3-4 items they choose"],
             "play":["Child selects and packs: what is needed for today?","Put it on and carry it","Walk somewhere together -- child carries the whole way","Unpack at the destination"],
             "say":['"What do you need today? You pack it."','"Your bag, you carry it."','"You carried your own things all the way."'],
             "if_happens":"Child asks parent to carry it after 2 minutes",
             "avoid":'"You carry it -- it is your bag."',
             "better":'"It is heavy! Let us take one thing out -- what can you leave behind? Now carry the lighter version."',
             "why":"Physical self-management -- carrying your own things, managing your own belongings -- is a foundational independence skill for school readiness. Children who arrive at school expecting others to manage their physical environment struggle more with transitions. The packing task also builds planning (what will I need?) and prioritisation (what is most important?) skills.",
             "tool":"My Things, My Carry",
             "phrases":['"You packed it, you carry it."','"Managing your belongings is a kind of freedom."'],
             "skills":"Physical independence, planning, belongings management."},
        18: {"title":"Put On Your Shoes","emoji":"👟","skill":"Self-Care Sequence","materials":"Shoes",
             "milestone":"Milestone: Putting on shoes independently -- including distinguishing left from right -- is a 4-step sequential task that most children achieve between 2.5 and 4 years.",
             "setup":["Child's shoes","Sit on a low surface"],
             "play":["Step 1: which foot goes in which shoe? (left-right check)","Step 2: loosen the shoe fully","Step 3: push foot in","Step 4: fasten (velcro, or first step of tying)"],
             "say":['"Left shoe goes on the left foot -- how do you know which is which?"','"Loosen it first -- make it easy to get your foot in."','"You put on your own shoes. That is real."'],
             "if_happens":"Child puts left shoe on right foot",
             "avoid":'"Wrong foot -- switch."',
             "better":'"Put both shoes on the floor in front of you. They make a gentle curve -- like a smile. The curve tells you which is left and which is right."',
             "why":"Left-right shoe discrimination is a spatial reasoning task that many children find genuinely difficult at first. The smile trick (shoes placed together make a smile facing you, which tells you the correct orientation) is a visual mnemonic that works independently of left-right language. Teaching children to use environmental cues for self-correction builds the metacognitive habit of seeking information from the environment rather than relying on memory.",
             "tool":"Shoe Smile",
             "phrases":['"Put them together -- they make a smile. The smile faces up."','"Solving the left-right puzzle is real problem-solving."'],
             "skills":"Self-care sequence, left-right discrimination, spatial reasoning."},
        19: {"title":"Brush Your Teeth","emoji":"🦷","skill":"Health Routine","materials":"Toothbrush, toothpaste",
             "milestone":"Milestone: Independent tooth brushing -- reaching all four quadrants, timing for 2 minutes -- builds both the health habit and the self-monitoring capacity that underpins all future self-care.",
             "setup":["Toothbrush and toothpaste appropriate for the age","Mirror"],
             "play":["Child brushes: front top, front bottom, sides, inside","Use a timer: 2 minutes (or count to 120)","Check in mirror: any bits left?","Parent checks after -- make it a game, not a correction"],
             "say":['"All four sections: front top, front bottom, both sides."','"2 minutes -- let us count or time it."','"Open -- let me check. You got most of it -- your back teeth were tricky."'],
             "if_happens":"Child will not open for the check",
             "avoid":'"Open -- I have to check."',
             "better":'"I will make the funniest face while checking. Open and look at my face. ROAR!"',
             "why":"Tooth brushing is one of the most important daily health habits children develop and one that requires external accountability for quality until the child is around age 7-8. Making the parent check a playful event (funny face) rather than an inspection removes the power-struggle dimension that turns tooth brushing into a daily battle. The child who enjoys the check cooperates consistently.",
             "tool":"Brush and Check",
             "phrases":['"Check the mirror after -- your eyes are the quality control."','"The check is a game, not a test."'],
             "skills":"Health routine, self-monitoring, quadrant awareness."},
        20: {"title":"Sort the Laundry","emoji":"🧺","skill":"Household Contribution","materials":"Mixed clean laundry",
             "milestone":"Milestone: Sorting laundry -- matching pairs of socks, separating by person or type -- is a categorisation task that builds both mathematical classification and the contribution identity.",
             "setup":["A basket of mixed clean laundry","Focus on socks first -- most accessible"],
             "play":["Sort socks: find the pairs","Sort by person: these are Papa's, these are mine","Help fold (however imperfectly)","Put away in the right drawer"],
             "say":['"Find the matching socks -- which two go together?"','"Whose sock is this? Put it in their pile."','"You just helped the whole family."'],
             "if_happens":"Child throws socks rather than sorting",
             "avoid":'"Stop throwing -- we are sorting."',
             "better":'"OK, throw them to me and I will sort! You are the launcher, I am the sorter. Then swap."',
             "why":"Sorting laundry is a genuine contribution to household functioning that children at this age can meaningfully accomplish. Unlike adult-directed tasks with hidden adult corrections, a correctly matched pair of socks stays matched. This real contribution builds the identity of someone who helps -- which research shows is more motivating than praise-based incentives for household participation.",
             "tool":"Real Helper",
             "phrases":['"You did a real job that the family needed."','"Real helping feels different from pretend helping."'],
             "skills":"Categorisation, spatial matching, household contribution, identity."},
        21: "reflection",
        22: {"title":"Set the Table","emoji":"🍽️","skill":"Sequencing + Contribution","materials":"Plates, cups, cutlery",
             "milestone":"Milestone: Setting the table requires sequencing (plate, fork, knife, cup -- in order), spatial reasoning (where does each item go?), and counting (how many people?). It is a rich cognitive and social task.",
             "setup":["Count the family members","Gather the items needed"],
             "play":["How many people are eating?","Set one place first: plate, fork, knife, cup","Set the rest the same way","Adjust if anyone is missing"],
             "say":['"How many places do we need?"','"One plate per person. Now one fork per person."','"You set the table. Dinner starts because of you."'],
             "if_happens":"Child misses a place or puts items wrong",
             "avoid":'"You missed one -- and the fork goes on the left."',
             "better":'"Count the chairs and count the plates -- are they the same? Fix what is different. Then we eat."',
             "why":"Table setting is one of the richest practical life tasks for this age group because it simultaneously requires counting (how many?), spatial layout (each item at its place), and sequencing (what comes first?). The correction strategy (count and compare) teaches error detection through self-monitoring rather than adult correction -- building metacognitive self-checking behaviour.",
             "tool":"My Table",
             "phrases":['"You prepared the space for everyone to eat."','"Contribution is setting the table before you sit down."'],
             "skills":"Sequencing, counting, spatial layout, household contribution."},
        23: {"title":"Water the Plants","emoji":"🌿","skill":"Caretaking Responsibility","materials":"Plants, small watering can",
             "milestone":"Milestone: Regular plant watering builds caretaking responsibility -- the understanding that living things depend on consistent care -- and the habit of attending to the needs of others.",
             "setup":["The plant from Month 9 or any household plant","Small watering can"],
             "play":["Check soil first: dry or still wet?","Water only if dry","How much? Enough to moisten, not flood","Record: did the plant look different after?"],
             "say":['"Check the soil first -- does it need water today?"','"Only water what is dry -- too much hurts plants too."','"You are the plant caretaker. The plant counts on you."'],
             "if_happens":"Child overenthusiastically waters everything",
             "avoid":'"Too much -- stop!"',
             "better":'"All that water! Let us watch what happens. Too much water is actually bad for plants -- we will see the evidence."',
             "why":"Plant caretaking builds the ecological ethic (living things need care) and the responsibility habit (consistent, appropriate care is more valuable than irregular intense care). Letting children see the consequences of overwatering builds the empirical habit of observing outcomes and connecting them to actions -- one of the most useful scientific and life skills available.",
             "tool":"Consistent Care",
             "phrases":['"The plant depends on you -- not sometimes, but every day."','"Caring for something alive teaches you care."'],
             "skills":"Caretaking, ecological responsibility, observational feedback."},
        24: {"title":"Wash the Dishes","emoji":"🍽️","skill":"Functional Contribution","materials":"Plastic dishes, basin, soapy water",
             "milestone":"Milestone: Washing dishes -- scrubbing, rinsing, placing to dry -- is a functional household contribution that involves sequencing, sensory engagement, and fine motor skill in a meaningful real-world context.",
             "setup":["A basin with warm soapy water","Plastic cups and plates only -- safe items"],
             "play":["Wash: soap and scrub","Rinse: clean water","Place to dry: same orientation for all","Check: are they actually clean?"],
             "say":['"Soap makes the grease let go -- scrub in circles."','"Rinse until the soap bubbles are gone."','"You cleaned things that were dirty. The family uses these tomorrow."'],
             "if_happens":"Child splashes more than washes",
             "avoid":'"Stop splashing -- wash."',
             "better":'"Splash time is over. Now -- can you wash ONE dish so well that it squeaks? Listen for the squeak."',
             "why":"The squeaky clean test (rubbing a wet finger on clean glass squeaks) provides a sensory quality criterion that children can apply independently. This self-monitoring criterion transforms an adult-directed task into a self-directed one. The child is now working to meet their own standard rather than an adult's instruction -- which produces significantly stronger engagement and better learning.",
             "tool":"Squeak Test",
             "phrases":['"Clean things squeak when you rub them."','"You know when it is done -- your ears tell you."'],
             "skills":"Fine motor, household contribution, self-monitoring, sensory feedback."},
        25: {"title":"My Helper Day","emoji":"🌟","skill":"Contribution Identity","materials":"None",
             "milestone":"Milestone: A designated helper day -- where the child has real responsibilities -- builds the contribution identity that is associated with stronger sense of purpose and social connection in later life.",
             "setup":["Declare today Helper Day","Child has 3 real jobs"],
             "play":["Job 1: set the table","Job 2: water the plants","Job 3: sort the socks","Receive genuine thanks for each job"],
             "say":['"Today you are our real helper -- three real jobs."','"Job 1 done! That actually helped us."','"The family worked better today because you helped."'],
             "if_happens":"Child is tired and does not want to help",
             "avoid":'"You have to -- it is your helper day."',
             "better":'"You get to choose: which of the three jobs do you want to do TODAY? The other two are for tomorrow."',
             "why":"Regular contribution to family functioning builds the helper identity -- the self-concept of someone who contributes to their community. Research shows that children who have regular, genuine household responsibilities develop stronger intrinsic motivation, empathy, and civic sense than those who do not. The key is genuine contribution (not pretend jobs) and genuine thanks (not performative praise).",
             "tool":"Real Contribution",
             "phrases":['"The family works better when you help."','"Your work is real work."'],
             "skills":"Contribution identity, responsibility, community sense."},
        26: {"title":"Teach Someone","emoji":"👩‍🏫","skill":"Teaching as Learning","materials":"A skill the child has mastered",
             "milestone":"Milestone: Teaching a skill you have learned -- explaining it, demonstrating it, supporting someone else -- produces deeper learning consolidation than any other review strategy.",
             "setup":["Choose a skill the child has recently mastered: pouring, sorting, a song","Choose a teacher: parent pretends not to know"],
             "play":["Child is the teacher","Parent is the student who does not know how","Child explains and demonstrates","Parent asks questions: why? what next?"],
             "say":['"I do not know how to pour water -- can you teach me?"','"Tell me each step -- I will do exactly what you say."','"What a good teacher. I learned it."'],
             "if_happens":"Child cannot explain the steps",
             "avoid":'"You know this -- explain it."',
             "better":'"Show me with your hands first -- then explain. The showing helps you find the words."',
             "why":"The protege effect -- learning more deeply by teaching -- is a well-established educational phenomenon. Teaching requires the learner to organise their knowledge, identify gaps (what they cannot explain), and find language for procedural knowledge. Children who teach a skill they have recently learned show significantly better retention and transfer than those who practise the skill alone. The show-then-explain sequence externalises the implicit procedural knowledge before verbalization.",
             "tool":"Teacher Mode",
             "phrases":['"You understand something best when you can teach it."','"Teaching shows you what you know and what you do not know."'],
             "skills":"Teaching, knowledge consolidation, metacognition."},
        27: {"title":"My Can-Do List","emoji":"📋","skill":"Competence Catalogue","materials":"Paper, crayons",
             "milestone":"Milestone: A personally owned list of capabilities -- things I can do -- builds the competence self-concept that motivates continued learning and protects against learned helplessness.",
             "setup":["Paper and crayons","Think through this month and the whole year"],
             "play":["Draw or dictate: things I can do now that I could not do last year","Aim for 10 things","Read them back: each one is a real achievement","Display the list"],
             "say":['"What can you do now that you could not do last year?"','"Draw each one -- this is your Can-Do list."','"Ten things. Ten things you worked to learn."'],
             "if_happens":"Child says they cannot think of anything",
             "avoid":'"Think harder -- there must be something."',
             "better":'"Last year you could not walk up stairs without holding both rails. This year? Hands-free! That is one. What else?"',
             "why":"The competence self-concept -- the belief that one is capable -- is built from an accurate, owned inventory of genuine capabilities. Children with strong competence self-concepts approach new challenges with less anxiety and more persistence. Making the inventory explicit (a list, a display) creates an external reference that the child can return to in moments of self-doubt.",
             "tool":"Competence Catalogue",
             "phrases":['"You have more capabilities than you remember."','"The list is evidence of who you are now."'],
             "skills":"Competence self-concept, growth mindset, capability inventory."},
        28: "reflection",
        29: {"title":"Independence Stars","emoji":"⭐","skill":"Celebration","materials":"Gold star stickers or drawings",
             "milestone":"Milestone: Celebrating independence milestones -- ritualising achievement of self-care skills -- builds the milestone-awareness that motivates future growth.",
             "setup":["Review this month's skills","Prepare a celebratory context"],
             "play":["Name each independence skill mastered this month","Give it a star or draw it","Read all of them aloud","Who else in the family can you teach?"],
             "say":['"This month you learned to: (list them all)."','"That is a star for each one."','"You are more capable today than you were 30 days ago."'],
             "if_happens":"Child minimises their achievements",
             "avoid":'"You should be proud."',
             "better":'"Let me tell you what I observed: (specific description). That is not my interpretation -- that is what I saw. What you do with that observation is up to you."',
             "why":"Specific behavioural description (I saw you button your jacket with no help -- that is something you could not do last month) is more effective than evaluative praise (I am so proud) for building accurate self-assessment. Children who receive specific descriptions develop more accurate self-models than those who receive global evaluative praise, which tends to produce either inflation or dismissal.",
             "tool":"Specific Achievement",
             "phrases":['"Here is exactly what I observed."','"Your growth is real and specific."'],
             "skills":"Achievement awareness, accurate self-assessment, motivation."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 11 Complete: Independence Champion!",
        "summary": "This month your child learned to button, zip, pour, spread, set the table, sort laundry, wash hands, make the bed, and help around the house. These are the practical skills of a capable person.",
        "skills_built": ["Fine motor self-care: buttons, zips, shoes, spreading", "Health routines: handwashing, tooth brushing", "Household contribution: table setting, laundry, dishes", "Persistence: try, try again", "Competence identity: I can do hard things"],
        "month_next_teaser": "Final month: Ready and Growing -- School Readiness. Everything from 11 months comes together. Your child is ready for what comes next.",
    },
    "reflection_activities": {
        7:  {"activity": "I Did It Board", "desc": "Draw 3 things you managed to do independently this week. Put them on the fridge."},
        14: {"activity": "Try Again Count", "desc": "Which challenge required the most tries before success this week? Celebrate the number of tries."},
        21: {"activity": "Helper Tally", "desc": "How many times did you help the family this week? Tally mark for each one."},
        28: {"activity": "Can-Do Preview", "desc": "What can you do now that you are going to teach someone tomorrow?"},
    },
}


M12 = {
    "name": "Ready & Growing",
    "toolkit_label": "2--3 Years &middot; Month 12",
    "weeks": {
        1: {"title": "School-Ready Skills", "subtitle": "Everything you have built is ready"},
        2: {"title": "Big Kid Feelings", "subtitle": "Facing what comes next with confidence"},
        3: {"title": "Making Friends", "subtitle": "Taking the skills to new relationships"},
        4: {"title": "Celebrating the Journey", "subtitle": "A year of extraordinary growth"},
    },
    "days": {
        1:  {"title":"Sit and Listen","emoji":"🎓","skill":"Sustained Attention","materials":"A 5-minute story or activity",
             "milestone":"Milestone: The ability to sit, attend, and follow a structured activity for 5+ minutes is one of the most important school-readiness skills. It requires inhibitory control, sustained attention, and working memory.",
             "setup":["A story or short structured activity","Set a clear frame: 5 minutes, then free play"],
             "play":["5-minute story with a clear beginning, middle, end","Child sits and listens -- no toys","Ask 2 questions after","Celebrate: 5 minutes of focused attention"],
             "say":['"For 5 minutes: just sit and listen. Then you can do anything."','"After the story: what happened first?"','"5 minutes of attention -- that is a real skill."'],
             "if_happens":"Child cannot sit for 5 minutes",
             "avoid":'"Sit still -- I said sit."',
             "better":'"OK, 2 minutes first. We build up to 5. Ready? 2 minutes -- the story is short."',
             "why":"Sustained attention capacity -- the ability to maintain focus on a task for a specified period -- is one of the three most consistent school-readiness predictors (along with self-regulation and vocabulary). Building attention in gradual increments (2 minutes, then 3, then 5) follows the evidence-based approach of attention training research. The post-story questions activate comprehension monitoring -- the habit of listening actively rather than passively.",
             "tool":"Attention Builder",
             "phrases":['"5 minutes of your full attention -- that is a gift you give the teacher."','"Listening completely is harder than it looks."'],
             "skills":"Sustained attention, listening comprehension, sitting tolerance."},
        2:  {"title":"Follow Instructions","emoji":"📋","skill":"Instruction Following","materials":"None",
             "milestone":"Milestone: Following 2-3 step instructions -- stand up, touch your toes, sit down -- is a key school-readiness skill. It requires holding the sequence in working memory while executing each step.",
             "setup":["Two-step instruction: stand up and touch your nose"],
             "play":["Give 2-step: stand up, clap twice","3-step: stand, spin, sit","4-step: stand, hop, clap, sit","Swap: child gives instructions, parent follows"],
             "say":['"Ready: stand up and touch your nose. Go."','"Three steps: stand, spin, sit. Do you have them? Go."','"Now YOU give me a 3-step instruction."'],
             "if_happens":"Child loses the sequence midway",
             "avoid":'"You forgot -- it was stand, spin, sit."',
             "better":'"Sequence forgotten! That happens. Try this: say the steps to yourself before you start. Ready? Say them."',
             "why":"Multi-step instruction following requires phonological working memory (holding the verbal sequence) and executive sequencing (executing steps in order). Research shows that 3-step instruction following at school entry predicts academic success in the first year of primary school. Self-rehearsal of the sequence (saying steps before executing) is one of the most effective working memory strategies for young children.",
             "tool":"Rehearse Then Do",
             "phrases":['"Say the steps before you do them."','"Your memory carries the instructions -- say them to keep them."'],
             "skills":"Multi-step instruction, working memory, executive sequencing."},
        3:  {"title":"Wait My Turn","emoji":"⏰","skill":"School-Ready Patience","materials":"A game or activity",
             "milestone":"Milestone: Waiting for a turn in a group context -- raising a hand, waiting to be called -- is a specific social-cognitive skill that children need to practise before entering a classroom.",
             "setup":["Role play a classroom: parent is teacher, child is student"],
             "play":["Teacher asks a question: raise your hand to answer","Wait to be called: even if you know the answer","When called: stand up and answer","Practise not shouting out"],
             "say":['"When you know the answer, put your hand up -- wait for me to call you."','"I see your hand -- wait just 3 more seconds."','"Yes? What is your answer?"'],
             "if_happens":"Child shouts out without raising hand",
             "avoid":'"I said raise your hand."',
             "better":'"That is the answer! Next time: hand up first -- and I promise I will call you fast. Deal?"',
             "why":"The raise-your-hand convention is one of the most culturally specific school behaviours children need to learn and one that is almost never taught at home. Practising it explicitly removes the cognitive and social novelty of the behaviour so that when the child encounters it in a real classroom, the habit is already formed. The promise to call quickly removes the frustration that causes children to shout out.",
             "tool":"Hand Up, Wait",
             "phrases":['"Hand up means: I have something to say -- and I am waiting to be heard."','"Waiting to be called is a kind of respect."'],
             "skills":"School convention, turn-taking in group context, impulse control."},
        4:  {"title":"My Name in Print","emoji":"✍️","skill":"Name Writing","materials":"Paper, thick crayon",
             "milestone":"Milestone: Writing one's own name -- recognising it in print and being able to copy it -- is a key literacy milestone and an identity-literacy connection that motivates all future reading and writing.",
             "setup":["Write the child name in large clear print","Paper and thick crayon"],
             "play":["Look at the letters: name each one","Trace over the letters","Copy the name next to the model","Use the name everywhere: sign drawings, label belongings"],
             "say":['"These letters spell your name -- see: [spell it]."','"Trace over my writing -- feel the shape of each letter."','"Now copy it next to mine."'],
             "if_happens":"Child cannot copy and becomes frustrated",
             "avoid":'"Try again -- look at the model."',
             "better":'"Tracing is the training wheels of writing. Keep tracing until the shape is in your hand. Then you will copy without looking."',
             "why":"Name writing is the most motivating writing task for young children because the name belongs to them -- it is their identity in print. Research shows that children who can write their own name at school entry have stronger print motivation and faster literacy acquisition than those who cannot. The tracing-to-copying progression is an evidence-based motor skill scaffolding sequence.",
             "tool":"My Name Is Mine",
             "phrases":['"Your name in your own handwriting."','"This is how you sign your work."'],
             "skills":"Name writing, literacy identity, fine motor, print motivation."},
        5:  {"title":"Raise Your Hand","emoji":"✋","skill":"Classroom Participation","materials":"None",
             "milestone":"Milestone: Active classroom participation -- contributing verbally in a group setting -- requires confidence, impulse control, and the social courage to speak in front of others.",
             "setup":["Role play classroom again","This time with multiple questions"],
             "play":["Teacher asks questions (from the year's topics)","Child raises hand, waits, answers","Celebrate both trying and knowing","Try: ask a question, not just answer"],
             "say":['"If you know the answer, show me your hand."','"You raised your hand. You are ready."','"You can also raise your hand to ask a question -- you do not have to know the answer."'],
             "if_happens":"Child becomes shy in classroom context",
             "avoid":'"Come on -- answer the question."',
             "better":'"In our classroom, there are no wrong answers. I will never laugh at a wrong answer. Try anything."',
             "why":"Classroom participation anxiety -- the reluctance to raise one's hand in a group setting -- is one of the most common and educationally costly early school experiences. Children who do not participate miss the learning that comes from active engagement and also develop patterns of learned passivity. The no-wrong-answer frame and no-laughing guarantee remove the two most common fears that suppress participation.",
             "tool":"Safe to Raise",
             "phrases":['"There are no wrong answers in our classroom."','"Raising your hand says: I am here and I want to participate."'],
             "skills":"Classroom participation, social courage, active learning."},
        6:  {"title":"Show and Tell","emoji":"🌟","skill":"Oral Presentation","materials":"One object to present",
             "milestone":"Milestone: Show and Tell -- presenting a chosen object to an audience and answering questions -- is a micro-version of the public speaking, object examination, and question-answering that defines academic participation.",
             "setup":["Child chooses one object to present","Parent is the audience"],
             "play":["Child presents: what it is, where it came from, why it matters to me","Audience asks 2-3 questions","Child answers","Switch: parent presents, child is questioner"],
             "say":['"Tell me everything about this object -- I am your audience."','"Why did you choose this one?"','"Questions from the audience: when did you get it?"'],
             "if_happens":"Child says a few words and stops",
             "avoid":'"Tell me more -- what else can you say?"',
             "better":'"Good start. Now I have questions: 1 -- where did it come from? 2 -- what do you do with it?"',
             "why":"Show and Tell is an oral language performance task that builds vocabulary (finding words for an object), narrative organisation (telling the object's story), and public speaking confidence. Research on oral language development shows that structured opportunities to speak about personally chosen objects significantly develop vocabulary breadth and coherence -- the most powerful literacy predictors.",
             "tool":"My Story Object",
             "phrases":['"Every object has a story -- tell me the story of this one."','"Questions make the presentation better.."'],
             "skills":"Oral presentation, vocabulary, narrative organisation, public speaking."},
        7:  "reflection",
        8:  {"title":"Big Kid Feelings","emoji":"💪","skill":"Emotional Readiness","materials":"None",
             "milestone":"Milestone: Understanding that transitions bring mixed feelings -- excited AND nervous -- and that both feelings are valid prepares children for the emotional complexity of school entry.",
             "setup":["Talk about school or a big change","No pressure -- just exploration"],
             "play":["Ask: what excites you about being a big kid?","Ask: what feels scary or nervous?","Both feelings are OK: name them","Make a plan for the nervous feeling"],
             "say":['"What excites you about getting bigger?"','"Is there anything that feels nervous or scary?"','"Excited AND nervous -- both can be true at the same time."'],
             "if_happens":"Child only says it will be fun (denies nervousness)",
             "avoid":'"Are you sure? Most children feel nervous."',
             "better":'"Exciting! And if any nervous sneaks in later, you know what to do -- name it and tell me."',
             "why":"Transition emotions are typically mixed (approach-avoidance): both excited and apprehensive. Children who can name and accept both emotional valences -- rather than suppressing the negative one -- show better adjustment to school entry. The plan for nervous feeling (what will you do if you feel scared?) builds coping self-efficacy: the belief that one can manage the negative feeling when it arrives.",
             "tool":"Mixed Feelings Are Fine",
             "phrases":['"You can be excited AND nervous at the same time."','"Having a plan for scared makes scared smaller."'],
             "skills":"Emotional complexity, transition preparation, coping self-efficacy."},
        9:  {"title":"Goodbye Gets Easier","emoji":"👋","skill":"Separation Tolerance","materials":"None",
             "milestone":"Milestone: Practising goodbye -- short separations with a clear return promise -- builds the separation tolerance that eases school transitions and all future attachment transitions.",
             "setup":["Practice a short separation at home: parent goes to another room"],
             "play":["Parent says goodbye clearly: I am going to the kitchen for 5 minutes","Child stays in another room","Parent returns exactly on time","Extend: 10 minutes, then 20"],
             "say":['"I am going to the kitchen for 5 minutes. I will be back."','"While I am gone: [specific activity]."','"I am back -- exactly like I said. I always come back."'],
             "if_happens":"Child cries or follows",
             "avoid":'"Stop -- I am just in the kitchen."',
             "better":'"I hear that you want me close. I am going to the kitchen and coming back in 2 minutes -- very fast. I always come back."',
             "why":"Separation anxiety at school entry is predicted by earlier separation experiences. Children who have practised short separations with reliable returns develop what attachment researchers call secure base behaviour -- the confident expectation that the attachment figure will return. The ritual of a clear goodbye (not sneaking away) and a reliable, on-time return is the specific practice that builds separation tolerance.",
             "tool":"I Always Come Back",
             "phrases":['"I always come back -- every single time."','"Goodbye is not forever -- it is just for now."'],
             "skills":"Separation tolerance, secure attachment, transition confidence."},
        10: {"title":"New Place Practice","emoji":"🏫","skill":"Environmental Flexibility","materials":"Any new or unfamiliar space",
             "milestone":"Milestone: Feeling OK in a new environment -- exploring, asking questions, orienting -- requires environmental flexibility that is built through graduated exposure to novel spaces.",
             "setup":["Visit somewhere slightly unfamiliar: a different park, a library, a neighbour's house"],
             "play":["Enter the new space together","Child explores: what is here? What can I do?","Ask: what is the same as usual? What is different?","Find one thing you like about the new space"],
             "say":['"New place -- let us explore together."','"What is the same as [familiar place]? What is different?"','"Find one thing you like about this place."'],
             "if_happens":"Child clings and will not explore",
             "avoid":'"Go ahead -- I am right here."',
             "better":'"We explore together. I go too. When you feel ready, you can go a bit further than me. Not yet -- together first."',
             "why":"Environmental flexibility -- the capacity to function effectively in new environments -- is built through graduated exposure: new environments with trusted adults present, then new environments briefly alone, then new environments independently. The familiar-unfamiliar comparison (what is the same?) activates existing schemas and reduces the novelty-induced anxiety that restricts exploration.",
             "tool":"Same and New",
             "phrases":['"New places always have some familiar things if you look."','"Exploring together is the first step."'],
             "skills":"Environmental flexibility, novelty tolerance, spatial orientation."},
        11: {"title":"Ask for Help","emoji":"🙋","skill":"Help-Seeking","materials":"None",
             "milestone":"Milestone: Knowing when and how to ask for help -- without shame or excessive dependence -- is one of the most practically important school-readiness skills.",
             "setup":["Create a situation where help is genuinely needed","Role play the help-seeking conversation"],
             "play":["Situation: you cannot reach something, you do not understand something, you feel sad","Practise asking: excuse me, I need help with...","Practice receiving help gracefully: thank you","Also practise: deciding when to try alone first"],
             "say":['"Excuse me -- I need some help with this."','"Try first alone -- if you cannot after two tries, then ask."','"Thank you -- that was exactly what I needed."'],
             "if_happens":"Child either never asks or always asks",
             "avoid":"'You ask too much -- try first.' or 'You should have asked -- stop struggling.'",
             "better":'"Two-try rule: try twice alone. If it does not work, asking is smart. If it does work, you did not need help -- and that feels great."',
             "why":"Help-seeking and independent problem-solving are not opposites -- they are complementary skills. The two-try rule provides a concrete, developmentally appropriate criterion for when asking becomes appropriate. Children who have this rule consistently applied develop accurate self-assessment of their own capability boundaries and neither over-depend nor unnecessarily struggle. Both over-dependence and under-asking are academic risks.",
             "tool":"Two-Try Rule",
             "phrases":['"Try twice -- then asking is the smart choice."','"Asking for help is a skill, not a weakness."'],
             "skills":"Help-seeking, self-assessment, independence calibration."},
        12: {"title":"When I Do Not Know","emoji":"🤷","skill":"Intellectual Humility","materials":"None",
             "milestone":"Milestone: Saying I do not know -- without shame -- and asking to find out is one of the most important learning dispositions a child can have. It is the prerequisite for all genuine inquiry.",
             "setup":["Have a genuine question neither of you knows the answer to"],
             "play":["Ask each other something you do not know","Practise saying: I do not know -- let us find out","Find out together (look it up, ask someone)","Celebrate the discovery"],
             "say":['"I do not know -- and that is a great place to start."','"Let us find out -- how do we find out?"','"We did not know. Now we do. That is how learning works."'],
             "if_happens":"Child pretends to know when they do not",
             "avoid":'"You do not know -- admit it."',
             "better":'"That is an interesting answer! I wonder if we can check -- let us find out if that is true."',
             "why":"Intellectual humility -- the willingness to acknowledge uncertainty and seek information -- is one of the most valuable academic dispositions. Children who learn to say I do not know comfortably become better learners because they remain curious rather than defensive. The find-out-together response to I do not know models the inquiry process and makes not-knowing a beginning rather than an endpoint.",
             "tool":"I Do Not Know Yet",
             "phrases":['"I do not know YET -- that is the start of learning."','"Finding out is better than pretending to know."'],
             "skills":"Intellectual humility, inquiry habit, learning disposition."},
        13: {"title":"Morning Routine Practice","emoji":"🌅","skill":"Self-Management","materials":"Morning routine items",
             "milestone":"Milestone: An independent morning routine -- wake, dress, wash, eat, pack -- is a multi-step sequential self-management achievement that signals genuine executive function development.",
             "setup":["Plan the morning routine together","List the steps in order"],
             "play":["Child executes the routine with minimal prompting","Parent only observes","Note which steps were done independently","Celebrate: X of Y steps done independently"],
             "say":['"You know the steps -- let us see how many you can do without reminders."','"I will watch and count the steps you did alone."','"[X] steps independently! The rest will come."'],
             "if_happens":"Child needs reminders for every step",
             "avoid":'"You should know this by now."',
             "better":'"You needed reminders for 4 steps. Which one do you think you could do without a reminder tomorrow? Pick one. Just one."',
             "why":"Routine independence develops incrementally. Asking the child to identify one step they could do independently tomorrow is a self-directed improvement strategy that preserves autonomy (they chose the step) while building routine competence incrementally. The counting of independent steps provides positive evidence of progress rather than deficit framing.",
             "tool":"One More Step",
             "phrases":['"Which step can you own tomorrow?"','"Independence in routines builds one step at a time."'],
             "skills":"Morning routine, executive sequencing, self-management."},
        14: "reflection",
        15: {"title":"Friend at the Park","emoji":"🌳","skill":"Peer Initiation","materials":"Park visit",
             "milestone":"Milestone: Approaching an unknown peer, initiating play, and sustaining it for a few minutes is the full social initiation cycle that predicts school-entry peer acceptance.",
             "setup":["A park or playground where other children may be","No pressure -- observation is fine too"],
             "play":["Observe other children playing","Identify who looks approachable","Child approaches: hi, can I play?","If successful: play for 5 minutes together","If not: that is OK too -- debrief warmly"],
             "say":['"Who looks like they might want a new friend?"','"Walk over and just say: hi, can I play too?"','"They said yes! You did it."'],
             "if_happens":"Child is rejected",
             "avoid":'"That is rude of them -- let us find better friends."',
             "better":'"They said no -- that is one outcome. It does not mean anything about you. Let us try someone else, or play our own game."',
             "why":"Social rejection from peers is inevitable and learning to process it without catastrophising is a crucial social resilience skill. The normalisation of rejection as one outcome (not a judgment of worth) and the immediate alternative (try someone else, or play your own game) prevents the shame spiral that causes children to stop initiating social contact after rejection. The real social learning here is: rejection is survivable.",
             "tool":"Rejection Is Survivable",
             "phrases":['"They said no -- that is one outcome and it is OK."','"Try again or play your own game -- both are good options."'],
             "skills":"Social initiation, rejection resilience, peer interaction."},
        16: {"title":"Sharing Circle","emoji":"🔵","skill":"Group Sharing","materials":"A talking object (stone, small ball)",
             "milestone":"Milestone: Group circle sharing -- each person speaks in turn while others listen -- is the foundational classroom participation structure. Practising it at home builds the habit before it is required in school.",
             "setup":["3+ family members if possible","A talking stone: whoever holds it speaks"],
             "play":["Pass the stone: each person shares one thing from their day","Only the person holding the stone speaks","Everyone else listens -- no interrupting","Questions only after the person finishes"],
             "say":['"Only the person holding the stone speaks."','"Everyone else: listening ears on."','"After [person] finishes, we will pass the stone and then you can respond."'],
             "if_happens":"Child interrupts others",
             "avoid":'"No interrupting -- wait your turn."',
             "better":'"Stone is with [person] -- your thought is important and it is coming. Hold it for 30 seconds."',
             "why":"Sharing circles are used in classrooms, therapy, and community settings worldwide because the talking object externalises the turn-taking rule into a physical object. Children who understand and follow the talking object rule require less individual behavioral management in circle time because the rule is in the object, not in the adult. This shift from adult-rule to environmental-rule is a key step in internalising social structures.",
             "tool":"Talking Stone",
             "phrases":['"The stone decides who speaks."','"Listening is what you do when someone else has the stone."'],
             "skills":"Group turn-taking, active listening, classroom circle readiness."},
        17: {"title":"Introduce Yourself","emoji":"👋","skill":"Social Language","materials":"None",
             "milestone":"Milestone: A confident, clear self-introduction -- name, age, something I like -- is a social language script that reduces social anxiety in new environments.",
             "setup":["Role play a first meeting: parent is a new person"],
             "play":["Practice: hi, my name is [name]. I am [age] years old. I like [thing].","Shake hands (optional)","Practice with eye contact","Try variations: at a party, at school, at a neighbour's house"],
             "say":['"Practise with me: Hi, my name is..."','"Eye contact makes people feel like you mean it."','"Now more confident: louder, clearer, eyes up."'],
             "if_happens":"Child mumbles or looks down",
             "avoid":'"Speak up and look at me."',
             "better":'"Let me turn away. Now introduce yourself to my back. Make your voice big enough that I can hear you from here."',
             "why":"The loud-enough-to-be-heard-from-behind exercise physically trains voice projection without the self-consciousness of direct eye-contact demand. This is a vocal confidence exercise borrowed from theatre training. The social introduction script (name, age, one thing I like) is a manageable, practisable micro-performance that gives children a reliable entry into new social situations. Familiarity with the script significantly reduces social entry anxiety.",
             "tool":"Clear Introduction",
             "phrases":['"Your name and one thing about you -- that is all it takes to meet someone."','"A clear voice says: I am here."'],
             "skills":"Social language, voice projection, self-introduction."},
        18: {"title":"Group Game Practice","emoji":"🎮","skill":"Group Play Skills","materials":"A simple group game",
             "milestone":"Milestone: Participating in a structured group game -- following rules, waiting for turns, winning and losing gracefully -- is a social-cognitive skill bundle required for school-based group activities.",
             "setup":["Simple game: Snakes and Ladders, Simon Says, or any group game","2-4 players"],
             "play":["Explain rules clearly before starting","Play the game -- follow all rules","If you win: celebrate modestly","If you lose: name the feeling and move on"],
             "say":['"The rules are the rules -- they are the same for everyone."','"You won! Celebrate, but gently -- the other person lost."','"You lost -- how does that feel? And the game can be played again."'],
             "if_happens":"Child cheats or changes rules to win",
             "avoid":'"That is cheating -- play fairly."',
             "better":'"You changed the rule -- I noticed. If we play with different rules for different people, it stops being fair. Want to restart with the same rules for all?"',
             "why":"Rule-governed group games develop what researchers call institutional rules cognition -- the understanding that rules are agreed social conventions that apply equally to all participants. Children who understand this concept transition more smoothly to classroom rules and institutional settings. The framing of cheating as making the game unequal (rather than wrong) activates fairness reasoning rather than compliance pressure.",
             "tool":"Same Rules for Everyone",
             "phrases":['"Rules make the game fair for all."','"Winning with different rules for yourself is not really winning."'],
             "skills":"Rule-following, fair play, winning and losing gracefully."},
        19: {"title":"When I Need Space","emoji":"🌿","skill":"Self-Advocacy","materials":"None",
             "milestone":"Milestone: Knowing when you need space, saying so clearly, and taking it without guilt or crisis is one of the most important self-advocacy skills for school environments.",
             "setup":["Discuss: what does needing space feel like?"],
             "play":["Identify the feelings that signal need for space: overwhelmed, crowded, too loud","Practise the phrase: I need some quiet time please","Find the quiet space in your home -- or classroom equivalent","Practice taking the space and returning"],
             "say":['"What does needing space feel like for you?"','"Practise saying: I need some quiet time please."','"Take the space -- come back when you are ready."'],
             "if_happens":"Child cannot articulate when they need space",
             "avoid":'"You should know when you need a break."',
             "better":'"Let us find your signal together. When you start to feel like running away, or your voice gets louder, or you stop talking -- that is probably the need-space feeling arriving."',
             "why":"Self-advocacy -- knowing and articulating your own needs in social contexts -- is particularly important for school environments where children are often in close proximity to others for extended periods. Children who can say I need quiet time please are far less likely to hit, bite, or shut down as a response to overwhelm, because they have a verbal alternative. Teaching this in low-stakes home contexts builds the habit before it is needed.",
             "tool":"I Need Space",
             "phrases":['"I need some quiet time please -- that is self-advocacy."','"Taking space is not escaping -- it is self-management."'],
             "skills":"Self-advocacy, self-awareness, regulation in social context."},
        20: {"title":"Kind Words Practice","emoji":"💬","skill":"Social Kindness","materials":"None",
             "milestone":"Milestone: A repertoire of kind social phrases -- congratulations, that was kind, are you OK, I like your... -- is one of the most concrete and teachable social skills that predicts peer acceptance.",
             "setup":["Role play various social scenarios"],
             "play":["Friend completes something: say congratulations or well done","Friend shares with you: say thank you -- that was really kind","Friend is hurt: say are you OK? Can I help?","Practice 5 different scenarios"],
             "say":['"What kind thing could you say right now?"','"That phrase made the other person feel seen."','"Kind words are a skill -- the more you practise, the more natural they feel."'],
             "if_happens":"Child says they feel fake saying kind things",
             "avoid":'"You have to say it anyway."',
             "better":'"Feeling fake at first is normal -- it is a new habit. Your smile does not feel fake even though you learned it. Kind words work the same way."',
             "why":"Social scripts -- specific phrases for specific social situations -- are not inauthentic; they are linguistic tools that enable social functioning. The smile analogy is neurologically accurate: smiling is a learned social signal that becomes genuinely felt through repeated use (facial feedback hypothesis). Kind phrases work the same way: repeated use creates the neural associations that make them feel natural and genuinely motivated.",
             "tool":"Kind Word Bank",
             "phrases":['"Kind words open every door."','"Your word bank grows with every kind thing you say."'],
             "skills":"Social phrases, peer acceptance, kindness habit."},
        21: "reflection",
        22: {"title":"Letter to Future Me","emoji":"✉️","skill":"Temporal Self-Awareness","materials":"Paper, crayons, envelope",
             "milestone":"Milestone: Writing a letter to your future self -- I hope by then you can... -- builds temporal self-awareness and growth aspiration, connecting the current self to the future self.",
             "setup":["Paper and envelope","Explain: this letter is for future you"],
             "play":["Draw or dictate a letter to yourself in one year","What do you hope to be able to do?","What do you love right now that you want to remember?","Seal it -- open in one year"],
             "say":['"This is from you, to you, one year from now."','"What do you want future you to know?"','"Seal it -- we open it next year."'],
             "if_happens":"Child wants to open it immediately",
             "avoid":'"No -- we have to wait."',
             "better":'"The magic is in the waiting. Write something so interesting that waiting will be worth it."',
             "why":"Temporal self-concept -- the understanding that you are the same person across time, and that your future self is worth caring about -- is a foundational aspect of identity development. Children with strong temporal self-concept show better delayed gratification, longer-term planning, and greater emotional regulation. A letter to future self makes the temporal identity concrete and personally meaningful.",
             "tool":"Future You",
             "phrases":['"Future you is still you -- worth writing to."','"What you are today is the foundation of what you will be."'],
             "skills":"Temporal self-awareness, future orientation, identity continuity."},
        23: {"title":"Our Year in Stories","emoji":"📚","skill":"Autobiographical Narrative","materials":"Any notes or photos from the year",
             "milestone":"Milestone: Co-constructing the story of a year with a caregiver consolidates autobiographical memory, narrative identity, and the child understanding of themselves as a developing person.",
             "setup":["Any photos, drawings, or memories from the year","Sit together for a memory review"],
             "play":["Month by month: what do you remember from Month 1? Month 3?","What was hardest? What was best?","What are you most different from 12 months ago?","Tell the year as a story: once upon a time, in Month 1..."],
             "say":['"What do you remember from the beginning of the year?"','"What changed the most? What is the same?"','"Tell me this year as a story -- beginning, middle, and now."'],
             "if_happens":"Child only remembers recent things",
             "avoid":'"Try to remember the earlier months."',
             "better":'"Let me start -- in Month 1 we did [activity]. What do you remember from around that time?"',
             "why":"Co-constructing autobiographical narrative with a caregiver is one of the most powerful memory consolidation and identity-building activities available. Research by Robyn Fivush shows that children who engage in elaborative reminiscing with parents develop stronger autobiographical memories, more cohesive self-narratives, and better emotional wellbeing. The joint narrative structure (parent starts, child continues) scaffolds the memory retrieval process.",
             "tool":"Year Story",
             "phrases":['"A year is a story -- and you are the main character."','"The further back we remember, the stronger our story."'],
             "skills":"Autobiographical memory, narrative identity, temporal self-concept."},
        24: {"title":"Thank You Letter","emoji":"💌","skill":"Gratitude","materials":"Paper, crayons, envelope",
             "milestone":"Milestone: Writing a thank-you letter -- expressing gratitude to a specific person for a specific thing -- builds gratitude practice and the relationship maintenance behaviour that sustains long-term social wellbeing.",
             "setup":["Think of someone to thank: a family member, a neighbour, a friend","Paper and crayons"],
             "play":["Who deserves a thank-you?","What specific thing are you grateful for?","Write or dictate and draw","Deliver it"],
             "say":['"Who helped you or was kind to you this year?"','"Write or draw: I am grateful for you because..."','"Delivering it is the most important part."'],
             "if_happens":"Child cannot think of anyone",
             "avoid":'"Surely you can think of someone."',
             "better":'"Think about the people who made this year easier for you. Even one small kindness is worth a thank-you."',
             "why":"Gratitude practice -- specifically, expressing gratitude to others rather than privately feeling it -- is one of the most well-replicated wellbeing interventions across all age groups. The action of writing and delivering a thank-you letter combines gratitude (positive psychological effect for the giver), relationship maintenance (positive social effect for the recipient), and expressive writing (literacy benefit). This triple benefit makes it one of the most valuable activities in this curriculum.",
             "tool":"Gratitude in Action",
             "phrases":['"Saying thank you is a gift to the person and to yourself."','"Gratitude makes the world kinder."'],
             "skills":"Gratitude, relationship maintenance, expressive writing."},
        25: {"title":"What I Am Good At","emoji":"🏆","skill":"Strength Awareness","materials":"Paper, crayons",
             "milestone":"Milestone: Identifying personal strengths -- things you are genuinely good at -- builds the competence self-concept that is one of the strongest foundations for academic confidence and resilience.",
             "setup":["Paper, time, and warmth","Parent and child do it together"],
             "play":["Each person: 5 things they are genuinely good at","Parent goes first -- models vulnerability and honesty","Child lists their 5","Share with each other: I did not know you thought you were good at that"],
             "say":['"I will go first: I am good at making you laugh. I am good at cooking. I am good at..."','"Now you: 5 things you genuinely do well."','"That strength is real -- I have seen it."'],
             "if_happens":"Child can only say nice things said by others, not their own strengths",
             "avoid":'"No -- what do YOU think you are good at?"',
             "better":'"Start with: what do you enjoy doing most? Usually that thing you love is also something you are getting good at."',
             "why":"Strength awareness is distinct from performance praise. Knowing your own strengths -- the skills and qualities you genuinely possess -- provides a stable, internally validated competence foundation that is not dependent on external validation. Research on positive psychology and character strengths consistently shows that strength-based self-knowledge is associated with stronger wellbeing, motivation, and resilience across the lifespan.",
             "tool":"Strength Spotter",
             "phrases":['"Your strengths belong to you -- not to what others say."','"Knowing what you are good at is knowledge, not bragging."'],
             "skills":"Strength awareness, internal competence, positive self-concept."},
        26: {"title":"Family Celebration Dinner","emoji":"🍽️","skill":"Milestone Ritual","materials":"Special meal together",
             "milestone":"Milestone: Marking a significant achievement with a celebratory ritual builds the sense that effort and growth deserve recognition -- which motivates continued growth.",
             "setup":["Prepare a special meal together","Declare: this is our celebration dinner"],
             "play":["Set the table specially: flowers, candles if safe, best dishes","Each person shares one thing they are proud of from the year","Toast: to the year we had","Share the meal with special conversation"],
             "say":['"This dinner is for celebrating the year."','"Each person: one thing you are proud of."','"To this family. To this year. To everything we did."'],
             "if_happens":"Child says they are not proud of anything",
             "avoid":'"Of course you are -- you worked so hard."',
             "better":'"I will tell you one thing I am proud of about you -- and then you tell me if you agree."',
             "why":"Rituals of celebration -- marked, structured events that acknowledge achievement -- create episodic memories of accomplishment that become part of the child identity narrative. Research on ritual and wellbeing shows that people who create meaningful personal and family rituals report higher life satisfaction and stronger family cohesion. The specificity of the pride statement (one thing I am proud of) prevents vague over-inflation.",
             "tool":"Celebration Ritual",
             "phrases":['"We mark this moment because it matters."','"Achievement deserves a dinner."'],
             "skills":"Achievement ritual, family bonding, pride and celebration."},
        27: {"title":"What Comes Next?","emoji":"🚀","skill":"Future Orientation","materials":"None",
             "milestone":"Milestone: Discussing what comes next -- with curiosity and confidence rather than anxiety -- builds a future orientation that motivates continued learning and growth.",
             "setup":["Sit together","A curious, forward-looking conversation"],
             "play":["What are you excited about in the next year?","What do you want to learn?","What do you want to try?","What might be hard? And how will you handle it?"],
             "say":['"The next year: what excites you most?"','"What do you want to learn? Anything at all."','"What might be hard -- and what is your plan?"'],
             "if_happens":"Child is anxious about what comes next",
             "avoid":'"It will be fine -- do not worry."',
             "better":'"There is something that worries you -- and we can make a plan for that exact thing. Tell me what it is."',
             "why":"Future orientation -- the tendency to think forward with curiosity and planning rather than anxiety -- is one of the most protective psychological orientations available. Children who develop positive future orientation show stronger academic motivation, better goal-setting behaviour, and greater resilience under adversity. The plan-for-the-hard-thing question builds adaptive coping: preparing for difficulty rather than hoping it will not arrive.",
             "tool":"Future Planning",
             "phrases":['"Excited and ready -- those are your feelings for what comes next."','"Make a plan for the hard part -- then it is smaller."'],
             "skills":"Future orientation, aspiration, adaptive coping planning."},
        28: "reflection",
        29: {"title":"12-Month Achievement Book","emoji":"📗","skill":"Portfolio Documentation","materials":"Paper, all month materials if available",
             "milestone":"Milestone: A 12-month achievement book -- documenting the year's growth -- is the ultimate self-referential learning artefact. Seeing one's own development across 12 months builds the narrative identity of a growing, capable person.",
             "setup":["Gather materials from all 12 months if available","Fold and staple a larger book: 12 pages"],
             "play":["One page per month: a drawing, a note, a sticker","Write or dictate: what I learned in Month [X]","Read through the whole book when finished","Share with someone you love"],
             "say":['"Each page is one month of your life and learning."','"What do you want to say about Month 3? Month 7?"','"12 months. All in this book. You did all of this."'],
             "if_happens":"Child wants to rush and have it done",
             "avoid":'"Take your time -- this is important."',
             "better":'"Let us do 3 months today and 3 months tomorrow -- then it is done properly. Which 3 first?"',
             "why":"Portfolio documentation -- curating and presenting one's own learning across a period of time -- is one of the most evidence-based assessment and motivation practices in education. Children who help create their own learning portfolios develop stronger metacognitive awareness of their own development, stronger intrinsic motivation, and more sophisticated understanding of themselves as learners. The act of choosing what to include makes it personal and owned.",
             "tool":"My Year Portfolio",
             "phrases":['"Every page you made is a chapter of your year."','"This book is the story of who you grew into."'],
             "skills":"Self-documentation, metacognition, learning portfolio, narrative identity."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 12 Complete: You Did It -- A Whole Year!",
        "summary": "Twelve months. Three hundred and sixty-five days. You showed up, played, practised, laughed, failed, tried again, and grew. Your child grew. And so did you as their parent. That is the whole thing.",
        "skills_built": ["School-readiness: attention, instruction-following, turn-taking", "Social confidence: initiation, introduction, group participation", "Emotional readiness: mixed feelings, separation, I need space", "Independence: morning routine, self-care, household contribution", "Identity: strengths, gratitude, future orientation"],
        "month_next_teaser": "A year of TotWise Lab. Your child is not the same child who started Month 1. Neither are you. The work you did together will carry both of you further than you can see from here.",
    },
    "reflection_activities": {
        7:  {"activity": "School-Ready Check", "desc": "Which of this week's skills felt most natural? Which still needs practice? Make a plan for the one that needs practice."},
        14: {"activity": "Feelings Inventory", "desc": "What feeling is the strongest this week? Name it, locate it in the body, and choose one tool for it."},
        21: {"activity": "Social Skills Review", "desc": "Think about three different social situations you navigated this week. What did you do well in each?"},
        28: {"activity": "Year Highlights", "desc": "What are the three best memories of this whole year? Where were you? Who was there? What happened?"},
    },
}
