"""Month 4: Feelings & Faces -- curriculum data"""
M4 = {
    "name": "Feelings & Faces",
    "toolkit_label": "2--3 Years &middot; Month 4",
    "weeks": {
        1: {"title": "Name the Feeling", "subtitle": "Putting words to the biggest experiences"},
        2: {"title": "Faces Tell Stories", "subtitle": "Reading emotions in faces and voices"},
        3: {"title": "Calm-Down Toolkit", "subtitle": "Tools your child can use independently"},
        4: {"title": "Feeling Together", "subtitle": "Empathy -- the bridge between two hearts"},
    },
    "days": {
        1:  {"title":"Happy and Sad","emoji":"😊","skill":"Emotional Vocabulary","materials":"Mirror (optional)",
             "milestone":"Milestone: Naming emotions is the single most powerful tool for regulation. Research shows that when children label what they feel, the intensity of the feeling decreases -- this is called affect labelling.",
             "setup":["Sit together facing each other","Make happy face, then sad face"],
             "play":["Make a big happy face -- exaggerate it","Make a very sad face","Ask: which one are you right now?","Share something that makes you each feel happy or sad"],
             "say":['"This is my happy face!"','"This is my sad face -- see my frown?"','"Which feeling is in you right now?"'],
             "if_happens":"Child says everything is fine but clearly is not",
             "avoid":'"You do not look fine -- tell me what is wrong."',
             "better":'"I see something in your face. You do not have to tell me yet. I will wait."',
             "why":"Affect labelling -- naming a feeling -- activates the prefrontal cortex and reduces amygdala activation. This is the neurological basis of why naming helps. At 2-3 years, children are learning that internal states have words, which is one of the most significant cognitive achievements of early childhood. Modelling your own emotions while naming them teaches both vocabulary and emotional authenticity simultaneously.",
             "tool":"Name It to Tame It",
             "phrases":['"I can see you feel something."','"It is OK to feel that."'],
             "skills":"Emotional vocabulary, self-awareness, affect labelling."},
        2:  {"title":"Angry Body","emoji":"😠","skill":"Anger Recognition","materials":"None",
             "milestone":"Milestone: Learning that anger has physical signals -- hot face, tight fists, fast heartbeat -- gives children early access to a regulation strategy: noticing the feeling before it escalates.",
             "setup":["Stand up with space to move"],
             "play":["Show what angry looks like in your face","Show what angry feels like in your fists and body","Show what angry looks like in your whole posture","Then: shake it out and release"],
             "say":['"When I am angry, my face gets tight -- like this."','"My fists want to squeeze."','"Now we shake it all out -- brrr!"'],
             "if_happens":"Child starts acting out anger and hits you",
             "avoid":'"Do NOT hit me -- stop that."',
             "better":'"Ouch -- that hurt. I know you are angry. Angry feet can stomp. Angry hands can squeeze a pillow. Not me."',
             "why":"Teaching children the physical signals of anger gives them early access to the awareness that precedes regulation. The body sends signals -- tight fists, hot cheeks, clenched jaw -- before the emotion becomes overwhelming. Learning to recognise these signals is the foundation of all anger management. The shake-it-out practice also provides proprioceptive discharge that physically releases accumulated tension.",
             "tool":"Angry Body Scan",
             "phrases":['"Where do you feel the angry? Is it in your chest?"','"What does angry feel like in your fists?"'],
             "skills":"Anger recognition, body awareness, impulse awareness."},
        3:  {"title":"Scared and Safe","emoji":"😨","skill":"Fear and Safety","materials":"A cosy blanket",
             "milestone":"Milestone: Distinguishing scary feelings from actual danger is a key achievement. Children who learn that scary feelings are survivable develop resilience and manage anxiety better throughout life.",
             "setup":["Wrap up in a blanket together","Create a cosy safe spot"],
             "play":["Talk about something a little scary (the dark, a large dog)","Name the scared feeling: heart goes fast, tummy feels funny","Show what safe feels like: warm, calm, close to someone trusted","Make the safe spot together -- declare it a safe base"],
             "say":['"Sometimes things feel scary. That is OK."','"What does scared feel like in your body?"','"This is our safe spot. Nothing bad happens here."'],
             "if_happens":"Child becomes genuinely upset talking about fears",
             "avoid":'"It is not scary -- there is nothing to be afraid of."',
             "better":'"That IS scary to you. Scary feelings are real. And right now you are safe -- I am right here."',
             "why":"Validating fear while simultaneously providing safety helps children develop a crucial distinction: feeling scared versus being in danger. Many adults struggle with anxiety precisely because they cannot make this distinction. At 2-3 years, the brain threat-detection system is very sensitive. Teaching children to notice the scared feeling AND assess their actual safety builds emotional regulation from the earliest age.",
             "tool":"Safe and Scared Together",
             "phrases":['"Scared is just a feeling. You are safe."','"I will not let anything happen to you."'],
             "skills":"Fear regulation, safety awareness, secure attachment."},
        4:  {"title":"Surprised!","emoji":"😲","skill":"Emotion Range","materials":"A surprise item hidden behind back",
             "milestone":"Milestone: Recognising surprise as distinct from fear or excitement develops emotional granularity -- the ability to distinguish between similar feelings, which leads to more precise emotional communication.",
             "setup":["Hide something small behind your back","Put on your biggest surprise face first"],
             "play":["Reveal the item dramatically -- SURPRISE!","Make the biggest surprised face together","Talk about: surprised feels different from scared","Play: cover eyes, reveal something -- practise surprise"],
             "say":['"SURPRISE! Look what I have!"','"Surprise face -- eyes wide, mouth open, like this!"','"Is surprised a good feeling or a bad one? Or both?"'],
             "if_happens":"Child is startled and cries from real fright",
             "avoid":'"It is just a surprise -- do not cry!"',
             "better":'"Oh, that surprised you too much -- that was a big one. Here, look -- it is just [item]. Are you OK?"',
             "why":"Surprise is a transitional emotion -- it can shift quickly to delight or to distress depending on context. Teaching children to recognise and name surprise builds emotional granularity: the ability to identify fine differences between emotional states. Research shows that people with higher emotional granularity have better mental health outcomes, because precision in emotional labelling enables more precise regulation strategies.",
             "tool":"Surprise to Delight",
             "phrases":['"Surprise turned into happy -- did you feel that shift?"','"Your face said: wait, what?"'],
             "skills":"Emotional granularity, surprise regulation, emotional vocabulary."},
        5:  {"title":"Excited!","emoji":"🤩","skill":"Excitement Regulation","materials":"Something your child is excited about",
             "milestone":"Milestone: Excitement is one of the hardest emotions to regulate because it feels good. Teaching children to enjoy and then channel excitement is a key pre-school readiness skill.",
             "setup":["Think of something exciting for your child","Both of you let yourselves get excited"],
             "play":["Jump up and down excited together","Then: slow to a calm deep breath","Practice going from excited to calm 3 times","Celebrate: you can feel excited AND come back down"],
             "say":['"I am SO excited -- ahh!"','"Now let us bring it down... big breath... there."','"You felt excited and then calmed down. That is SO hard and you did it."'],
             "if_happens":"Child cannot come down from excitement and escalates",
             "avoid":'"Calm down -- stop it now."',
             "better":'"I can see the excited is really big right now. Let us put our feet flat on the floor. Feel the floor? Good. Now one breath."',
             "why":"Excitement dysregulation is one of the main reasons young children melt down at parties and holiday events. Teaching children to voluntarily move from excited to calm builds nervous system flexibility. The floor-grounding technique works because proprioceptive input activates the parasympathetic nervous system -- a physical interruption of the arousal cycle.",
             "tool":"Excitement Ladder",
             "phrases":['"Excitement can go up the ladder and come back down."','"You are learning to ride the excitement wave."'],
             "skills":"Excitement regulation, nervous system flexibility, self-calming."},
        6:  {"title":"Disgusted and Delighted","emoji":"🤢","skill":"Emotional Contrast","materials":"Two foods: one liked, one disliked",
             "milestone":"Milestone: Experiencing the contrast between disgust and delight teaches children that the body gives reliable signals about preferences -- foundational for later decision-making and boundary-setting.",
             "setup":["Prepare two foods: a favourite and a disliked one","Have napkins ready"],
             "play":["Try the liked food -- make the delight face together","Try the disliked food -- make the disgust face","Talk about what each feeling feels like in the body","Validate: it is OK not to like things"],
             "say":['"Mmm -- delighted! My whole face is happy."','"Ugh -- disgusted. My nose wrinkles, my tummy says no."','"You do not have to like it. Disgust is your body telling you something."'],
             "if_happens":"Child refuses to taste the disliked food",
             "avoid":'"Just try it -- one bite."',
             "better":'"You do not have to taste it. Can you just smell it and make the face? Your body knows already."',
             "why":"Disgust is one of the six primary emotions identified by Ekman and is closely linked to the body self-protective boundaries. Teaching children to honour disgust responses -- without forcing them to override body signals -- builds the self-trust that becomes the foundation of healthy boundaries in both childhood and adult social situations.",
             "tool":"Body Knows",
             "phrases":['"Your body already knows what it likes."','"Disgust is a message worth listening to."'],
             "skills":"Emotional contrast, body trust, preference awareness."},
        7:  "reflection",
        8:  {"title":"Mirror Mirror","emoji":"🪞","skill":"Facial Expression Reading","materials":"Mirror",
             "milestone":"Milestone: Recognising emotions in a mirror builds the face-emotion connection that is the basis of both self-awareness and empathy. At 2-3 years, children are developing full self-recognition.",
             "setup":["Sit in front of a mirror together"],
             "play":["Make a happy face -- see it in the mirror","Make a sad face -- see the changes","Try: surprised, angry, calm","Ask: what changed between angry and calm?"],
             "say":['"Look at your happy face -- see your smile in the mirror?"','"What changes when you make angry?"','"Your face tells your feelings even when you say nothing."'],
             "if_happens":"Child is silly with the mirror",
             "avoid":'"Stop being silly -- do the sad face."',
             "better":'"Silly face! That is a feeling too. What feeling is silly? Happy? Playful? Both?"',
             "why":"The mirror provides visual feedback linking the internal feeling state to a facial expression the child can observe. This creates the proprioceptive-visual loop: the child feels their face making an expression and sees that expression simultaneously, which strengthens the face-emotion schema. Children with strong face-emotion schemas are better at reading emotions in others.",
             "tool":"Face Reader",
             "phrases":['"Your face is a feelings map."','"I can read your face like a book."'],
             "skills":"Facial expression recognition, self-awareness, emotional literacy."},
        9:  {"title":"Feeling Photographs","emoji":"📸","skill":"Empathy","materials":"Family photos or magazine pictures",
             "milestone":"Milestone: Reading emotions in photographs develops mentalising -- understanding that others have inner states. This theory of mind skill emerges around age 3 and is fundamental to social competence.",
             "setup":["Gather 4-5 family photos or magazine faces"],
             "play":["Point to a face: how do they feel?","Look for clues: eyes, mouth, eyebrows","Guess together -- no wrong answers","Share a memory of feeling that same way"],
             "say":['"What is this person feeling? How can you tell?"','"Look at the eyes -- what do they say?"','"I once felt like that when..."'],
             "if_happens":"Child guesses wrong and gets frustrated",
             "avoid":'"No -- that is a sad face, not angry."',
             "better":'"Interesting! I can see why you thought that. Look at the mouth too -- what does the mouth say?"',
             "why":"Mentalising -- attributing mental states to others -- begins developing around 18 months and becomes more sophisticated throughout early childhood. Photographs allow slow examination without social pressure. Research shows that children with richer mentalising ability have better peer relationships and are less likely to engage in aggressive behaviour.",
             "tool":"Inner World Reader",
             "phrases":['"I wonder what they are thinking right now."','"Their face is telling me something."'],
             "skills":"Mentalising, empathy, emotional inference."},
        10: {"title":"Draw a Feeling","emoji":"🎨","skill":"Emotional Expression","materials":"Paper and crayons",
             "milestone":"Milestone: Drawing emotions -- even as abstract scribbles -- gives children a non-verbal channel for expression. Children who have expressive outlets for emotions show lower rates of acting out.",
             "setup":["Paper and crayons for both"],
             "play":["Ask: draw a colour that feels like happy","Then: draw a shape that feels like sad","Draw together -- no right way","Talk about the choices together"],
             "say":['"What colour is happy to you?"','"Draw your feeling -- not a picture, just the feeling itself."','"Oh -- you chose red for angry. Why does red feel angry?"'],
             "if_happens":"Child says they cannot draw feelings",
             "avoid":'"Just try -- it does not have to be good."',
             "better":'"Even a line counts. A squiggly line for wiggly feelings, a calm line for calm feelings. Show me a squiggly."',
             "why":"Abstract emotional expression through art activates right hemisphere visual-emotional processing. The non-verbal channel bypasses the verbal limitations that prevent children from expressing complex feelings in words. Even choosing a colour for a feeling creates a representational connection between the internal state and an external symbol -- which IS the definition of language.",
             "tool":"Colour Your Feeling",
             "phrases":['"What colour are you right now?"','"Draw the shape of your feeling -- big or small?"'],
             "skills":"Emotional expression, creative representation, emotional vocabulary expansion."},
        11: {"title":"Feelings in Books","emoji":"📚","skill":"Empathy via Story","materials":"A picture book",
             "milestone":"Milestone: Discussing characters feelings in stories is one of the most powerful empathy-building activities. Children who discuss books with parents show significantly stronger theory of mind development.",
             "setup":["Choose a picture book with emotional content"],
             "play":["Read the story -- pause at emotional moments","Ask: how does the character feel right now?","Ask: have you ever felt like that?","Connect: what could we say to the character?"],
             "say":['"Look at the character -- how do you think they feel?"','"I think they feel... because..."','"What would you say to them right now?"'],
             "if_happens":"Child wants to rush through without pausing",
             "avoid":'"Wait -- we need to talk about the feelings first."',
             "better":'"OK -- we read through fast. Now go back to your favourite page. How does that character feel on THAT page?"',
             "why":"Bibliotherapy -- using stories to explore emotions -- works because narratives provide safe emotional distance. The child can explore fear, anger, or sadness through a character without the direct vulnerability of personal disclosure. Research shows that rich emotional discussions during shared reading produce measurable empathy gains that persist months later.",
             "tool":"Story Empathy",
             "phrases":['"The character felt just like you did when..."','"Their feeling and your feeling are the same word."'],
             "skills":"Empathy, theory of mind, emotional literacy."},
        12: {"title":"The Feeling Body Map","emoji":"🗺️","skill":"Embodied Emotion","materials":"Large paper, crayons",
             "milestone":"Milestone: Research shows emotions have consistent body locations -- anger in chest and arms, happiness throughout the whole body. Teaching children to locate feelings in the body builds somatic awareness.",
             "setup":["Lay large paper on the floor","Trace your child's body outline"],
             "play":["Name a feeling: happy","Ask: where do you feel happy in your body?","Draw or colour that area","Do 3-4 feelings: happy, angry, scared, calm"],
             "say":['"Where is the happy? In your tummy? Your chest? Your whole body?"','"Colour that spot -- show me where angry lives."','"Every feeling has a home in the body."'],
             "if_happens":"Child colours the whole body for every feeling",
             "avoid":'"No -- happy is not everywhere."',
             "better":'"Wow, happy fills your WHOLE body! That is a big happy. Where is the BIGGEST part of the happy?"',
             "why":"Emotions are not just mental events -- they are physical experiences with consistent body locations. Teaching children to locate feelings in the body creates a somatic anchor for emotional awareness. This is the basis of somatic therapy and mindfulness-based regulation: when children can feel where the emotion lives, they can address it through body-based calming strategies.",
             "tool":"Find Your Feeling",
             "phrases":['"The feeling is in your body -- where is it right now?"','"Your body knew before your brain did."'],
             "skills":"Somatic awareness, embodied emotion, emotional self-knowledge."},
        13: {"title":"Voice Tells Feelings","emoji":"🔊","skill":"Paralinguistic Awareness","materials":"None",
             "milestone":"Milestone: 38% of emotional communication happens through tone of voice alone. Teaching children to listen to voice tone builds a critical social perception skill that most adults use unconsciously.",
             "setup":["Sit together","Demonstrate the voice game"],
             "play":["Say a simple word in different tones: happy, sad, angry, scared","'Water' -- happy voice","'Water' -- sad voice","Ask: which feeling did you hear?"],
             "say":['"Same word, different feeling -- listen!"','"What did my voice tell you?"','"My voice said one thing -- my words said another. Which one was true?"'],
             "if_happens":"Child gets confused and guesses randomly",
             "avoid":'"Listen carefully -- that was clearly sad."',
             "better":'"Let us try one at a time. Here is my happy water -- now can you do a happy water?"',
             "why":"Prosody -- the musical qualities of speech including pitch, rhythm, and intensity -- carries enormous emotional information. Children develop prosodic reading earlier than they develop verbal emotional vocabulary but do not always bring this skill into conscious awareness. Explicit prosody games help children consciously access emotional information they already process unconsciously.",
             "tool":"Listen for the Feeling",
             "phrases":['"What did the voice say underneath the words?"','"Your voice has feelings in it."'],
             "skills":"Prosodic awareness, emotional perception, social communication."},
        14: "reflection",
        15: {"title":"Big Deep Breath","emoji":"🌬️","skill":"Breath Regulation","materials":"A feather or pinwheel (optional)",
             "milestone":"Milestone: Diaphragmatic breathing activates the vagus nerve which directly signals the parasympathetic nervous system to slow heart rate and lower cortisol. This is the physiological basis of all calm-down strategies.",
             "setup":["Sit comfortably","Demonstrate belly breathing"],
             "play":["Hand on tummy -- breathe in until tummy rises","Breathe out slowly -- count to 4","Try with a feather: blow it gently","Practise 5 times -- this is the superpower"],
             "say":['"Breathe into your tummy -- feel it rise like a balloon."','"Breathe out slow... 1, 2, 3, 4..."','"This breath is your superpower."'],
             "if_happens":"Child breathes shallowly into chest, not belly",
             "avoid":'"Into your tummy -- not your chest."',
             "better":'"Put my hand here -- feel my tummy go out when I breathe in. Now put YOUR hand on YOUR tummy. Feel it?"',
             "why":"Deep diaphragmatic breathing is one of the few techniques that can voluntarily activate the parasympathetic nervous system. When stressed, shallow breathing sustains arousal. By consciously slowing and deepening the breath, we interrupt this cycle and signal safety to the brainstem. Practising while calm builds the neural pathway so the breath becomes accessible when the child is actually dysregulated.",
             "tool":"Balloon Belly",
             "phrases":['"Your breath is always with you -- always available."','"Breathe in calm, breathe out the big feelings."'],
             "skills":"Breath regulation, parasympathetic activation, self-calming."},
        16: {"title":"Squeeze and Release","emoji":"🤜","skill":"Muscle Tension Release","materials":"Stress ball or playdough",
             "milestone":"Milestone: Progressive muscle relaxation teaches children to distinguish between tension and relaxation in the body, building proprioceptive self-regulation that transfers to emotional regulation.",
             "setup":["Each person holds a ball of playdough or a soft ball"],
             "play":["Squeeze as HARD as possible for 5 seconds","Release completely -- let it all go","Feel the difference between tight and loose","Try different body parts: fists, shoulders, toes"],
             "say":['"Squeeze as hard as you can -- TIGHT TIGHT TIGHT."','"And... release! Feel the difference?"','"Tight like a rock... then loose like jelly."'],
             "if_happens":"Child over-squeezes and gets worked up",
             "avoid":'"Too hard -- gentle."',
             "better":'"Big squeeze! Now -- can you go even SLOWER? Squeeeze... and sloooow release. Like honey dripping."',
             "why":"Progressive muscle relaxation works by creating a conscious contrast between tension and relaxation. The release phase activates mechanoreceptors in the muscles that send calming signals to the central nervous system. At 2-3 years, children often have difficulty locating tension in their bodies; this exercise gives them the experience of creating and then removing tension, building proprioceptive awareness needed for self-regulation.",
             "tool":"Tight and Loose",
             "phrases":['"Tight is stress. Loose is calm. Which one do you choose?"','"Let the tension go -- your body knows how."'],
             "skills":"Muscle relaxation, proprioception, tension awareness, self-regulation."},
        17: {"title":"Count to Five","emoji":"🖐️","skill":"Cognitive Regulation","materials":"Fingers",
             "milestone":"Milestone: Counting as a pause strategy inserts a cognitive interruption between impulse and action -- an executive function technique that becomes a lifelong emotional regulation tool.",
             "setup":["Hold up your hand","Demonstrate counting on fingers"],
             "play":["When something makes you want to react fast -- count on fingers","Breathe with each number","Practise with a pretend scenario: I want the biscuit and cannot have it yet","Count together"],
             "say":['"When we feel big feelings, we count to five first."','"1... 2... 3... 4... 5... now, how do you feel?"','"The counting gives your brain a moment to think."'],
             "if_happens":"Child refuses to count when actually upset",
             "avoid":'"COUNT -- I said count to five!"',
             "better":'"I know counting is hard when the feeling is big. Let me count with you -- hold my hand. 1..."',
             "why":"Counting activates the left prefrontal cortex -- the thinking brain -- which creates a momentary dampening of the amygdala stress response. By practising counting during calm moments, the sequence becomes automatic enough to deploy during emotional moments. Holding up fingers adds a kinesthetic anchor that makes the technique accessible even when verbal processing is impaired by stress.",
             "tool":"Count and Pause",
             "phrases":['"Five fingers, five seconds, five breaths."','"The count gives your feelings time to breathe."'],
             "skills":"Impulse control, cognitive regulation, executive function."},
        18: {"title":"The Calm Jar","emoji":"🫙","skill":"Sensory Regulation","materials":"Plastic bottle, glitter glue, water",
             "milestone":"Milestone: Watching a glitter jar settle is both a metaphor for emotional regulation and a sensory regulation tool. The slow visual input activates the parasympathetic system while the metaphor teaches the concept of settling.",
             "setup":["Fill a plastic bottle halfway with warm water","Add glitter glue and a drop of dish soap","Seal the cap tightly"],
             "play":["Shake the jar vigorously -- the glitter swirls like a big feeling","Watch it settle slowly","Talk: our feelings are like the glitter -- they settle when we are still","Keep the jar as a calm-down tool"],
             "say":['"When I shake it -- the glitter goes everywhere, like feelings."','"Now we wait... watch... it is settling..."','"You can shake THIS jar instead of shaking yourself."'],
             "if_happens":"Child just wants to shake it and never watches it settle",
             "avoid":'"Watch it settle -- that is the whole point."',
             "better":'"Shake it as much as you want. I will watch for the moment one piece of glitter starts to settle. There -- did you see that one?"',
             "why":"The calm jar works through multiple mechanisms. Visual tracking of settling glitter activates parasympathetic pathways. The metaphor creates a cognitive schema for emotional regulation. The act of choosing to watch (rather than continue shaking) practises voluntary attention regulation. Having a physical object to shake gives the body an acceptable outlet for physical agitation that protects social relationships.",
             "tool":"The Calm Jar",
             "phrases":['"Shake the jar, not yourself."','"Watch until one piece of glitter settles -- just one."'],
             "skills":"Sensory regulation, visual attention, emotional metaphor."},
        19: {"title":"My Calm Spot","emoji":"🏠","skill":"Self-Regulation Environment","materials":"A blanket or cushions",
             "milestone":"Milestone: Having a designated calm spot -- a safe physical space to regulate -- is one of the most practical and evidence-backed tools for toddler emotional regulation. It teaches self-directed soothing.",
             "setup":["Choose a corner together","Make it cosy: blanket, soft toy, the calm jar"],
             "play":["Name it together: Our Peace Place","Show what we do there: breathe, squeeze something soft, count","Practise going there BEFORE you need it","Go there when big feelings start"],
             "say":['"This is your peace place -- it is yours when you need it."','"We go there to help our feelings settle -- not as a punishment."','"How does it feel in the peace place? Different from the rest of the room?"'],
             "if_happens":"Child refuses to go to calm spot when upset",
             "avoid":'"Go to your calm spot NOW."',
             "better":'"I am going to the peace place -- want to come with me? You do not have to stay. Just try it."',
             "why":"A designated regulation space works because spatial anchoring is a powerful learning mechanism. The brain creates strong context-dependent memories, so a space consistently used for calm eventually triggers a calming response on its own. This is why therapists use consistent rooms and why patients often feel calmer just entering a familiar therapeutic space. Building this association early gives children a lifelong tool.",
             "tool":"Peace Place",
             "phrases":['"The peace place is waiting for you."','"You know where to go when feelings get big."'],
             "skills":"Environment-based regulation, self-directed soothing, safe-space creation."},
        20: {"title":"Wiggle It Out","emoji":"🕺","skill":"Physical Emotional Release","materials":"Music",
             "milestone":"Milestone: Physical movement metabolises the stress hormones -- cortisol and adrenaline -- that build up during emotional arousal. Vigorous exercise is one of the most effective emotional regulation tools the body has.",
             "setup":["Clear space","Put on silly music"],
             "play":["Wiggle every part of your body","Shake your hands SUPER fast","Stomp stomp stomp it out","Then: collapse on the floor -- feel the difference"],
             "say":['"Wiggle the feelings out!"','"Shake your hands as if trying to throw the feelings off."','"Feel the difference now -- is it a little better?"'],
             "if_happens":"Child was genuinely upset and wiggling does not help",
             "avoid":'"Wiggle harder -- it is supposed to help."',
             "better":'"Sometimes the feelings are too big for wiggling. Let us just sit. You do not have to do anything. I am here."',
             "why":"Vigorous physical movement metabolises cortisol and adrenaline -- the stress hormones that create the physical experience of emotional arousal. Even 2-3 minutes of vigorous movement significantly reduces salivary cortisol. For toddlers, whose bodies hold emotion physically in ways adults often suppress, movement-based regulation is particularly natural and effective.",
             "tool":"Move the Feeling",
             "phrases":['"Shake it out -- feelings do not stick when the body moves."','"Your body is the fastest way to your feelings."'],
             "skills":"Physical emotional release, stress hormone metabolism, movement regulation."},
        21: "reflection",
        22: {"title":"When Mama is Sad","emoji":"🤗","skill":"Empathy and Caregiving","materials":"None",
             "milestone":"Milestone: Seeing a trusted adult experience and name an emotion teaches children that all humans have feelings, that feelings are safe to show, and that empathy is a natural response to others' distress.",
             "setup":["Be honest -- share a mild age-appropriate sadness"],
             "play":["Share: I feel a bit sad today because the plant I was growing did not make it","Show the feeling in your face and body","Wait -- let them respond naturally","Thank them for whatever they offer"],
             "say":['"I have a feeling today -- a sad one. I wanted to tell you."','"When I feel sad, I like a hug. Can I have one?"','"Thank you. That hug really helped me feel better."'],
             "if_happens":"Child laughs or makes light of your sadness",
             "avoid":'"This is serious -- I am actually sad."',
             "better":'"Ha -- your laugh made me smile a little. That was kind even if you did not mean it that way."',
             "why":"When parents model vulnerable emotion authentically, children learn several things: that all humans have feelings, that emotions are safe to express, and that emotional needs can be communicated and met. Children who witness appropriate parental emotional expression develop richer emotional understanding than those whose parents suppress or hide all negative emotions.",
             "tool":"It Is OK to Feel",
             "phrases":['"Grown-ups have feelings too."','"Thank you for caring about how I feel."'],
             "skills":"Empathy, caregiving instinct, emotional normalisation."},
        23: {"title":"When My Friend is Hurt","emoji":"🩹","skill":"Empathy in Action","materials":"Toy or stuffed animal",
             "milestone":"Milestone: Practising empathy responses with a toy before needing them in real situations reduces cognitive load during actual social moments, making empathic responses more automatic and accessible.",
             "setup":["Use a soft toy as the hurt friend"],
             "play":["Toy falls or cries (you voice it)","Ask: what does your friend need?","Practise: check on them, say are you OK, get a plaster","Extend: what if a friend at the park looks sad?"],
             "say":['"Oh no -- the bear fell and got hurt!"','"What should we do for the bear?"','"How do we check if someone is OK?"'],
             "if_happens":"Child hits or ignores the hurt toy",
             "avoid":'"Be gentle -- the bear is hurt."',
             "better":'"Hmm, the bear still looks sad. What else could we try? Sometimes hurt friends just need someone to sit next to them."',
             "why":"Role-playing empathy responses with toys builds empathy schemas -- cognitive scripts for how to respond when others are in distress. This reduces the cognitive demand during real social situations, making the response more fluid. Research shows that children who engage in empathy-based pretend play with caregivers before age 3 show stronger prosocial behaviour at age 5.",
             "tool":"Helper Hands",
             "phrases":['"Your hands can help someone feel better."','"Sitting next to someone is sometimes the biggest help."'],
             "skills":"Empathy in action, prosocial behaviour, perspective-taking."},
        24: {"title":"I Feel, You Feel","emoji":"💞","skill":"Shared Emotion","materials":"None",
             "milestone":"Milestone: Understanding that two people can feel the same thing simultaneously -- shared emotion -- is a foundational social bonding experience that deepens attachment and social connection.",
             "setup":["Sit closely together"],
             "play":["Parent: I feel grateful right now because I am here with you","Ask: is there any part of you that feels something too?","Share something you both feel: cosy, silly, happy, tired","Notice: we can feel the same thing at the same time"],
             "say":['"I feel something right now -- I feel cosy and happy."','"Is there a feeling in you right now?"','"We have the same feeling -- we are sharing it right now."'],
             "if_happens":"Child says they do not have a feeling",
             "avoid":'"You must feel something -- everyone has feelings."',
             "better":'"That is OK -- maybe feelings are quiet right now. Let us just sit. Sometimes quiet is a feeling too."',
             "why":"Shared emotional states are one of the most bonding human experiences. Neuroscientists call this affective synchrony. When parent and child identify and name a shared feeling together, oxytocin increases in both, deepening their attachment. The experience also teaches the child that emotions are social events as much as private ones.",
             "tool":"Same Feeling",
             "phrases":['"We share this feeling right now."','"Your feeling and my feeling are the same word."'],
             "skills":"Shared emotion, emotional bonding, affective synchrony."},
        25: {"title":"Making Someone Happy","emoji":"🎁","skill":"Altruism","materials":"Paper, crayons",
             "milestone":"Milestone: Making something for another person activates empathy, theory of mind, and the prosocial reward system. Children who practise giving show higher wellbeing than those who only receive.",
             "setup":["Paper and crayons","Think of someone to make something for"],
             "play":["Ask: what does [person] like? What would make them happy?","Draw or make a card for them","Talk about giving it later","Imagine their face when they receive it"],
             "say":['"What makes Grandma happy? Let us make something for her."','"Imagine her face when she gets this -- what does it look like?"','"You made something with your hands and your love."'],
             "if_happens":"Child wants to keep the gift",
             "avoid":'"No -- we made this for Grandma."',
             "better":'"It is so good you want to keep it -- that means it is special. Let us make one for Grandma AND one for you to keep."',
             "why":"Altruistic behaviour activates the mesolimbic reward system -- the same neural circuitry that processes pleasure. fMRI studies show that giving activates more reward-related neural activity than receiving. This means altruism is intrinsically rewarding -- but only when it is freely chosen. Letting children make the giving decision preserves the intrinsic motivation that makes generosity self-sustaining.",
             "tool":"Giving Heart",
             "phrases":['"When you make someone happy, your heart gets warm too."','"Kindness feels good in the body."'],
             "skills":"Altruism, theory of mind, prosocial motivation."},
        26: {"title":"Feelings Change","emoji":"🌤️","skill":"Emotional Impermanence","materials":"None",
             "milestone":"Milestone: Understanding that feelings change -- that sad does not last forever -- is one of the most important insights a child can develop. It builds resilience and prevents emotional identification with passing states.",
             "setup":["Sit together quietly","Think of a feeling that has already changed today"],
             "play":["Share: this morning I felt tired. Now I feel energised. The feeling changed.","Ask: can you think of a feeling you had earlier that has changed?","Discuss: feelings come and go like clouds","Feelings are visitors -- they come, they stay, they leave"],
             "say":['"Feelings are like clouds -- they float in and float out."','"Remember when you were upset this morning? That feeling is gone now."','"All feelings pass. Even the big ones."'],
             "if_happens":"Child insists they will feel sad or angry forever",
             "avoid":'"Of course it will pass -- everything passes."',
             "better":'"Right now it feels like forever -- that is how big feelings work. But this feeling WILL change. It always has before. I will be here while it does."',
             "why":"Emotional impermanence -- the understanding that feelings are transient -- is a cornerstone of resilience. Children who identify WITH their emotions (I am angry) rather than experiencing them as passing states (I feel angry right now) are more vulnerable to dysregulation. Teaching impermanence through the cloud metaphor provides a gentle, developmentally accessible framework without invalidating the current feeling.",
             "tool":"Clouds and Sky",
             "phrases":['"The sky is always there behind the clouds."','"This feeling will change -- it always does."'],
             "skills":"Emotional impermanence, resilience, identity versus state distinction."},
        27: {"title":"All Feelings Are OK","emoji":"🌈","skill":"Emotional Acceptance","materials":"None",
             "milestone":"Milestone: Unconditional emotional acceptance -- the message that all feelings are allowed -- prevents emotional suppression, which is a primary risk factor for anxiety and depression in later life.",
             "setup":["Sit together comfortably","Establish a tone of openness"],
             "play":["Go through feelings: happy, sad, angry, scared, disgusted, surprised","For each one: is this feeling OK to feel? YES","Challenge: is it OK to feel angry? Sad? Jealous?","Distinguish: all feelings are OK. Some behaviours are not."],
             "say":['"Happy -- is that OK to feel? YES."','"Angry -- is that OK to feel? YES."','"Every single feeling is OK. Hitting is not OK. But feeling angry? Always OK."'],
             "if_happens":"Child says angry or sad is a bad feeling",
             "avoid":'"No -- I said ALL feelings are OK."',
             "better":'"Hmm -- who told you angry was bad? Let us check. Can you think of a time angry helped you? Like when something was unfair?"',
             "why":"The suppression of so-called negative emotions is associated with increased physiological stress responses and psychological vulnerability. When parents accept all emotional states without judgment while setting limits on behaviour, children learn the crucial distinction between feeling and acting. This acceptance is the foundation of emotional intelligence and is more associated with later wellbeing than any other single parenting practice.",
             "tool":"All Feelings Welcome",
             "phrases":['"There is no wrong feeling."','"Your feelings are always welcome here."'],
             "skills":"Emotional acceptance, psychological safety, feeling versus behaviour distinction."},
        28: "reflection",
        29: {"title":"Our Feelings Book","emoji":"📖","skill":"Emotional Narrative","materials":"Paper, crayons, stapler",
             "milestone":"Milestone: Creating a personal feelings book integrates the month's learning into a self-referential narrative -- a book about the child's own emotional world, building emotional literacy and early literacy skills simultaneously.",
             "setup":["Fold and staple 4-5 pages of paper","Title the cover: My Feelings Book by [name]"],
             "play":["Each page: one feeling with a drawing and its name","Write or dictate one sentence: I feel __ when __","Draw a picture for each feeling","Add a page: ways I calm down"],
             "say":['"This book is about YOUR feelings -- no one else\'s."','"What feeling should go on the first page?"','"You are the author of your own feelings story."'],
             "if_happens":"Child wants you to draw everything",
             "avoid":'"You draw it -- I cannot draw for you."',
             "better":'"I will do the writing and you do the drawing. But you are the one who decides what goes on each page -- you are the boss of this book."',
             "why":"Creating a personal emotional narrative book serves multiple developmental functions. It externalises the emotional world into a tangible, revisitable object. It builds vocabulary and concepts into a self-referential memory aid. And it introduces authorship -- the idea that the child has an inner world worth documenting and sharing -- which is foundational for literacy motivation.",
             "tool":"Author of Feelings",
             "phrases":['"Your feelings are worth a whole book."','"This book knows you -- because you made it."'],
             "skills":"Emotional literacy, narrative identity, early literacy."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 4 Complete: Feelings Champion!",
        "summary": "This month your child learned to name happy, sad, angry, scared, surprised, and more. They built a calm-down toolkit, practised empathy, and learned that all feelings are welcome.",
        "skills_built": ["Emotional vocabulary: 8 or more feeling words", "Calm-down tools: breath, calm jar, squeeze, wiggle", "Empathy: reading faces, helping others, shared feeling", "Emotional acceptance: all feelings are OK", "Understanding that feelings change"],
        "month_next_teaser": "Next month: Hands and Making. Fine motor skills, creative confidence, and the deep satisfaction of making things with your own hands.",
    },
    "reflection_activities": {
        7:  {"activity": "Feeling Check-In", "desc": "Ask: what is one feeling you felt this week? Draw a face for it. No wrong answers."},
        14: {"activity": "Mirror Feelings", "desc": "Sit in front of the mirror together and make every feeling face you know. How many can you name now?"},
        21: {"activity": "Calm-Down Review", "desc": "Which calm-down tool worked best this week? Breath? Jar? Squeeze? Wiggle? Pick your favourite and practise it together."},
        28: {"activity": "Feelings Gallery", "desc": "Lay out all the drawings and colour choices from the month. Look at them together. You made all of these -- you have so many feelings."},
    },
}
