"""Month 5: Hands & Making -- curriculum data"""
M5 = {
    "name": "Hands & Making",
    "toolkit_label": "2--3 Years &middot; Month 5",
    "weeks": {
        1: {"title": "Tearing, Squeezing, Squashing", "subtitle": "The hands learn through mess and force"},
        2: {"title": "Drawing & Scribbling", "subtitle": "Every mark is a message"},
        3: {"title": "Building & Stacking", "subtitle": "Making structures that stand"},
        4: {"title": "Making for Others", "subtitle": "When creation becomes a gift"},
    },
    "days": {
        1:  {"title":"Tear the Paper","emoji":"📰","skill":"Fine Motor Force","materials":"Old newspaper or junk mail",
             "milestone":"Milestone: Tearing paper requires precise bilateral hand coordination -- one hand holds, one tears. This same coordination is needed for turning pages, opening containers, and eventually holding paper while writing.",
             "setup":["Gather old newspaper, junk mail, or old magazine","Sit at the table together"],
             "play":["Tear strips together -- long, thin strips","Then tear small pieces","Try to tear in a straight line","Make a pile -- biggest to smallest"],
             "say":['"Tear! Pull and tear!"','"Make the longest strip you can."','"Feel how strong your hands are?"'],
             "if_happens":"Child tears just one piece and loses interest",
             "avoid":'"Keep tearing -- we are not done."',
             "better":'"One piece? OK. What should we DO with this one piece? Can it become something?"',
             "why":"Tearing paper is one of the most developmentally rich fine motor activities available because it requires bilateral coordination (two hands working together in opposing directions), force modulation (not too hard or too soft), and sustained grip. These are the same hand skills needed for scissors, buttons, and writing. The resistance of paper also provides rich proprioceptive input to the hands.",
             "tool":"Strong Hands",
             "phrases":['"Your hands did that."','"Feel how strong those fingers are."'],
             "skills":"Bilateral coordination, fine motor force, hand strength."},
        2:  {"title":"Play Dough Squeeze","emoji":"🪄","skill":"Hand Strength","materials":"Play dough (bought or homemade)",
             "milestone":"Milestone: Manipulating play dough builds intrinsic hand muscle strength -- the small muscles of the palm that control precision grip. These muscles are essential for all writing tools.",
             "setup":["Give each person a ball of play dough","Sit at the table"],
             "play":["Squeeze the whole ball as hard as possible","Poke with one finger -- make holes","Roll a snake together","Flatten with the palm -- how thin?"],
             "say":['"Squeeze as hard as you can!"','"Poke with your pointing finger -- one deep hole."','"Roll a snake -- long and thin!"'],
             "if_happens":"Child eats the play dough",
             "avoid":'"Do NOT eat that -- it is not food."',
             "better":'"I know it looks like food -- it smells good too! It is not for eating though. Can you squeeze it instead of taste it?"',
             "why":"The intrinsic muscles of the hand -- the small muscles that live inside the hand rather than running up the forearm -- are specifically developed through resistance activities like squeezing play dough. These muscles control the precision grip (pencil hold), key pinch (scissors), and tripod grip (writing). Research shows that children who have regular play dough experience before age 4 show significantly better pre-writing skill development.",
             "tool":"Strong Finger Check",
             "phrases":['"Which finger is the strongest? Test them all."','"Those fingers will write words one day."'],
             "skills":"Intrinsic hand strength, precision grip, pre-writing."},
        3:  {"title":"Scrunch and Smooth","emoji":"📦","skill":"Tactile Discrimination","materials":"Tissue paper or foil",
             "milestone":"Milestone: Scrunching and smoothing develops tactile discrimination -- the ability to feel fine differences in texture and shape through touch. This hand-brain sensory channel is foundational for all manual skill.",
             "setup":["Tissue paper or foil sheets","Table or floor"],
             "play":["Scrunch into a tight ball -- smallest possible","Smooth flat again -- out all the wrinkles","Crinkle and listen to the sound","Smooth and feel the difference"],
             "say":['"Scrunch it as small as you can!"','"Now smooth it out -- every wrinkle."','"Feel the difference -- scrunched vs smooth?"'],
             "if_happens":"Child cannot smooth the wrinkles and gets frustrated",
             "avoid":'"You need to smooth it properly -- look."',
             "better":'"Wrinkles are really hard to remove -- even I cannot get them all. Try your best. The trying is the whole point."',
             "why":"Smoothing wrinkles from paper requires precise tactile feedback -- the child must feel where the paper is still raised and apply targeted pressure. This tactile-motor loop (feel, adjust, feel again) is the same feedback system used in all fine manipulation tasks. The contrast between the scrunched and smooth states also develops haptic memory -- the ability to remember how things feel.",
             "tool":"Smooth Touch",
             "phrases":['"Your fingers can feel things your eyes cannot see."','"What does smooth feel like? What does rough feel like?"'],
             "skills":"Tactile discrimination, haptic memory, fine manipulation."},
        4:  {"title":"Pinch and Roll","emoji":"🔴","skill":"Tripod Pinch","materials":"Play dough or soft clay",
             "milestone":"Milestone: The three-finger tripod pinch -- thumb, index, middle finger -- is the foundational grip for all writing tools. Practising it with dough builds the specific muscles used in pencil holding.",
             "setup":["Small pieces of play dough","Table surface"],
             "play":["Pinch off tiny balls with three fingers only","Roll each ball between thumb and index finger","Make a chain of tiny balls","Line them up: big, medium, small"],
             "say":['"Pinch with just three fingers -- thumb, pointing, middle."','"Roll it between your fingers -- round and round."','"How many can you make in a row?"'],
             "if_happens":"Child uses whole fist instead of three fingers",
             "avoid":'"Just three fingers -- use the right ones."',
             "better":'"Whole hand works great! Now try the three-finger pinch -- it is harder. Which feels different?"',
             "why":"The tripod pinch grip uses the same three-finger configuration used to hold a pencil or crayon. Practising this grip in a non-writing context (play dough is forgiving and resistance-free) builds the specific muscular patterns without the cognitive demands of mark-making. This separation of grip from function is a key principle of pre-writing skill development.",
             "tool":"Three Finger Power",
             "phrases":['"Thumb, pointing, middle -- those three are the writing team."','"That pinch will hold a pencil one day."'],
             "skills":"Tripod pinch, three-finger coordination, pre-writing grip."},
        5:  {"title":"Stamp and Press","emoji":"🖱️","skill":"Visual-Motor","materials":"Potato or sponge stamp, paint",
             "milestone":"Milestone: Stamping develops visual-motor integration -- coordinating what the eye sees with what the hand does. The clear, immediate visual feedback (the stamp mark) creates a satisfying loop that motivates practice.",
             "setup":["Set up simple stamping: cut a potato, or use a sponge","Dip in paint, press on paper"],
             "play":["Press firmly -- no sliding","Lift straight up","See the mark left behind","Make a pattern: row, circle, random"],
             "say":['"Press down hard -- do not slide."','"Lift straight up -- peek at what you made!"','"Can you make a pattern? Same stamp, again and again?"'],
             "if_happens":"Child presses too lightly and the stamp does not show",
             "avoid":'"Press harder."',
             "better":'"Almost! Try pressing down and counting to 2 before lifting. 1... 2... lift!"',
             "why":"Stamping requires the coordination of downward pressure, sustained hold, and clean lift -- a three-stage motor sequence that demands visual-motor control. The visual feedback (the print left behind) creates a direct cause-and-effect learning loop that motivates experimentation and refinement. Pattern-making adds a cognitive layer: spatial sequencing that transfers to reading (left to right) and mathematics (pattern recognition).",
             "tool":"Press and See",
             "phrases":['"Press, hold, lift -- and see what you made."','"Your hands made a mark on the world."'],
             "skills":"Visual-motor integration, press control, pattern recognition."},
        6:  {"title":"Finger Paint","emoji":"🎨","skill":"Sensory Art","materials":"Finger paints, large paper",
             "milestone":"Milestone: Finger painting integrates sensory (touch), motor (hand movement), creative (mark-making decisions), and emotional (free expression) development simultaneously. It is one of the most developmentally rich activities for this age.",
             "setup":["Cover the table","Large paper, finger paints -- at least 3 colours"],
             "play":["Use all 10 fingers freely","Try one finger vs the whole hand","Mix colours with your fingers","No product required -- the process is everything"],
             "say":['"Use as many fingers as you want!"','"What happens when red and blue meet?"','"How does the paint feel between your fingers?"'],
             "if_happens":"Child is averse to the texture and will not touch the paint",
             "avoid":'"Just try it -- it washes off."',
             "better":'"The texture feels strange -- I get that. Can you touch it with just one fingertip? That is all. Just one."',
             "why":"Tactile aversion to art materials is a sensory processing difference that should be respected rather than overridden. Pushing children to touch textures they find aversive increases sensory sensitivity and damages trust. The one-fingertip approach uses a graded desensitisation principle: starting at the level the child is comfortable with and only progressing when they are ready. The goal is a positive sensory experience, not completion of the activity.",
             "tool":"Texture Talk",
             "phrases":['"What does the paint feel like? Cold? Smooth? Slimy?"','"Your fingers are the brushes -- they are enough."'],
             "skills":"Sensory processing, tactile tolerance, expressive art."},
        7:  "reflection",
        8:  {"title":"Scribble Freely","emoji":"✏️","skill":"Mark-Making","materials":"Crayons, large paper",
             "milestone":"Milestone: Free scribbling is the earliest stage of writing development. Research by Rhoda Kellogg identified 20 basic scribble patterns that all children make before representational drawing -- and all of them are precursors to letters.",
             "setup":["Large paper -- the bigger the better","Chunky crayons or markers"],
             "play":["No direction -- just make marks","All marks are good marks","Try: slow scribble, fast scribble, tiny and huge","Narrate what you see without interpreting"],
             "say":['"Just make marks -- any marks. There is no wrong."','"Oh, that is a long line!"','"Tell me about this -- what is happening here?"'],
             "if_happens":"Child asks what to draw and cannot start",
             "avoid":'"Draw whatever you want."',
             "better":'"Start anywhere. Put the crayon on the paper and just let your hand move. Anywhere."',
             "why":"Free scribbling is not pre-drawing -- it IS drawing at this developmental stage. The 20 basic scribbles identified by early childhood researchers are the building blocks of all human written symbol systems: lines, circles, crosses, dots. Directing the scribble (draw a house) bypasses this important self-directed exploration. The key adult role is providing materials and warm witness -- not instruction.",
             "tool":"Free Mark",
             "phrases":['"Every mark you make is yours."','"Your hand knew what to do."'],
             "skills":"Mark-making, pre-writing, creative agency."},
        9:  {"title":"Draw a Circle","emoji":"⭕","skill":"Pre-Writing Shapes","materials":"Crayons, paper",
             "milestone":"Milestone: Drawing a circle -- a closed curve -- is one of the first intentional shapes children produce and a significant developmental milestone typically achieved between 2 and 3 years. Circles are the basis of many letters (o, c, g, d).",
             "setup":["Model a large circle first","Use a chunky crayon"],
             "play":["Draw a big circle together","Ask: can you make it close -- meet where it started?","Try: small circles, large circles","Name things that are circles: sun, ball, face"],
             "say":['"Round and round -- try to close it!"','"Sun circle! Ball circle! Face circle!"','"Close the circle -- bring your line home."'],
             "if_happens":"Child makes spirals instead of closed circles",
             "avoid":'"No, close the circle -- do not keep going."',
             "better":'"A beautiful spiral! Watch how I close mine -- and then you try."',
             "why":"Closing a circular shape is a visually and motorically demanding task that requires the hand to turn back on its path and terminate at the starting point. This requires spatial awareness (where did I start?), motor planning (how do I get back?), and stroke control (stop here). These are the same skills needed for forming letters. The spiral-to-circle transition is a normal developmental progression.",
             "tool":"Round and Return",
             "phrases":['"Round and round -- come back home."','"That circle is perfect because you made it."'],
             "skills":"Pre-writing circles, motor planning, stroke control."},
        10: {"title":"Draw a Face","emoji":"😊","skill":"Representational Drawing","materials":"Paper, crayons",
             "milestone":"Milestone: Drawing a face -- a circle with eyes, nose, and mouth -- is one of the most significant milestones in early representational drawing. It typically emerges between 30 and 42 months and signals that the child can translate an internal mental image to a mark.",
             "setup":["Draw a circle together","Label it: this is going to be a face"],
             "play":["Add two eyes -- where do eyes go?","Add a nose -- what shape?","Add a mouth -- smiling or not?","Name it -- whose face is it?"],
             "say":['"Where do the eyes go? Show me."','"What shape is a nose?"','"Look -- it is a face! Whose is it?"'],
             "if_happens":"Child makes random marks and says it is a face",
             "avoid":'"That does not look like a face -- eyes go here."',
             "better":'"That IS a face -- YOUR kind of face. Tell me about it -- where are the eyes in your face?"',
             "why":"Tadpole figures and face drawings -- even highly simplified ones -- demonstrate that the child has formed an internal symbolic representation of a person. This representational capacity is one of the major cognitive achievements of early childhood, underpinning language (words as symbols), reading (letters as symbols), and mathematics (numbers as symbols). The adult's role is to accept all representations as valid.",
             "tool":"Your Kind of Face",
             "phrases":['"Every face you draw is real."','"Tell me the story of this face."'],
             "skills":"Representational drawing, symbolic thinking, spatial layout."},
        11: {"title":"Trace Your Hand","emoji":"✋","skill":"Body-to-Paper Translation","materials":"Paper, crayons",
             "milestone":"Milestone: Hand tracing requires the child to hold their hand still while using the other hand to draw around it -- a complex bilateral coordination task that also creates a permanent representation of their physical self.",
             "setup":["Large paper on a flat surface","Non-dominant hand flat on paper"],
             "play":["Trace the outline of your hand","Then trace your child's hand","Compare: big hand, small hand","Decorate the traced hands"],
             "say":['"Hold very still -- I am drawing all the way around your hand."','"Look -- here is your hand on paper!"','"My hand is bigger -- can you see?"'],
             "if_happens":"Child moves their hand during tracing",
             "avoid":'"Keep still -- you keep moving."',
             "better":'"Every time you move, the line gets wiggly -- that is OK. It makes it YOUR hand tracing -- not a perfect hand tracing."',
             "why":"Hand tracing creates a fascinating mirror experience: the child sees their hand represented on paper as a two-dimensional outline. This body-to-symbolic-representation translation builds body schema (the internal map of one's own body) while creating a tangible memento. The bilateral challenge (holding one hand still, moving the other) also develops the cross-lateral inhibition that underlies handwriting.",
             "tool":"Your Hand Lives Here",
             "phrases":['"Your hand made that shape."','"That is you -- you are on the paper."'],
             "skills":"Bilateral coordination, body schema, self-representation."},
        12: {"title":"Color Inside and Outside","emoji":"🎨","skill":"Spatial Boundary Awareness","materials":"Simple coloring sheet or shapes drawn by adult",
             "milestone":"Milestone: The concept of inside vs outside a boundary -- colouring within or deliberately outside a line -- develops spatial reasoning and later becomes the foundation of understanding categories and containers in mathematics.",
             "setup":["Draw 3 large simple shapes on paper","Explain: inside and outside"],
             "play":["Colour inside one shape","Colour outside the lines on another -- deliberately","Notice the difference","Ask: which one is harder? Why?"],
             "say":['"Fill the whole inside -- like pouring colour into a bowl."','"Now colour OUTSIDE the lines -- on purpose!"','"Inside and outside are different places."'],
             "if_happens":"Child cannot stay inside and gets frustrated",
             "avoid":'"You need to stay inside the lines."',
             "better":'"Staying inside is really hard -- the lines are just a suggestion. Colour wherever your hand goes."',
             "why":"The inside/outside distinction is both a spatial and a categorical concept. Spatially, it requires the visual system to recognise a boundary and the motor system to respect or ignore it. Categorically, it is the foundation for understanding container relationships -- which are fundamental to both mathematical thinking and linguistic comprehension (in, on, under, inside, outside). No-pressure colouring actually builds better spatial awareness than perfectionist colouring.",
             "tool":"Inside Outside",
             "phrases":['"Inside and outside are both places that exist."','"Your colour goes wherever you choose."'],
             "skills":"Spatial reasoning, boundary awareness, categorical thinking."},
        13: {"title":"Draw to Music","emoji":"🎵","skill":"Cross-Sensory Expression","materials":"Music, paper, crayons",
             "milestone":"Milestone: Drawing to music integrates auditory and visual-motor processing -- a cross-sensory exercise that develops neural integration and provides an alternative expressive channel for children who are more musical than verbal.",
             "setup":["Put on different music: fast, slow, soft, loud","Paper and crayons ready"],
             "play":["Draw WHILE the music plays -- not about the music, but WITH it","Fast music: fast lines; slow music: slow curves","Change colour when the music changes","Compare drawings done to different music"],
             "say":['"What does this music make your hand want to do?"','"Draw the sound -- not a picture, just the feeling of it."','"This music and that music made different marks."'],
             "if_happens":"Child stops drawing to listen to music instead",
             "avoid":'"Keep drawing -- do not stop."',
             "better":'"You stopped to listen -- that is perfect. When you are ready, let your hand start moving again to what you hear."',
             "why":"Cross-sensory activities that pair auditory input with motor output develop synesthetic neural connections -- the linking of sensory modalities that underlies metaphor, creativity, and complex abstraction. Music-to-movement exercises also activate multiple brain regions simultaneously, producing a kind of neural exercise that single-channel activities cannot replicate. For children who are more auditory than visual, this provides a motor-creative entry point.",
             "tool":"Sound to Line",
             "phrases":['"What does loud feel like on paper?"','"Your marks are the music made visible."'],
             "skills":"Cross-sensory integration, expressive art, auditory-motor connection."},
        14: "reflection",
        15: {"title":"How High Can We Build?","emoji":"🏗️","skill":"Spatial Reasoning","materials":"Blocks, books, or boxes",
             "milestone":"Milestone: Building towers requires spatial understanding (how objects balance), cause and effect (this block will topple that one), and persistence. The joy of toppling also builds resilience -- things fall, we rebuild.",
             "setup":["Gather all available blocks, boxes, or books","Clear a flat surface"],
             "play":["Build together -- how high before it falls?","Try different bases: wide base vs narrow","Rebuild after the fall -- immediately, positively","Count the blocks as you add them"],
             "say":['"How high can we get? Add one more..."','"Oh! It fell! Again -- faster this time!"','"What made it fall? Let us try a different way."'],
             "if_happens":"Child knocks the tower down before it is built",
             "avoid":'"Stop -- let me finish building first."',
             "better":'"You are ready to knock! OK -- let me build 5 fast, then you knock, then I build 5 again. Deal?"',
             "why":"Tower building is rich with early physics concepts: gravity, centre of mass, stability. Children who build and knock towers are testing these concepts experientially -- building intuitive physics understanding that formal science education will later formalise. The repeated fall-and-rebuild cycle also normalises failure as a natural part of the learning process, building the growth mindset that is one of the best predictors of academic success.",
             "tool":"Build and Rebuild",
             "phrases":['"It fell -- let us build it again, differently."','"Every fall teaches the tower something."'],
             "skills":"Spatial reasoning, early physics, persistence, growth mindset."},
        16: {"title":"Build and Knock Down","emoji":"💥","skill":"Cause and Effect","materials":"Stacked blocks",
             "milestone":"Milestone: Deliberately toppling a structure and observing the effect is a pure cause-and-effect experiment. At 2-3 years, children are in a critical period for causal reasoning that underpins all later scientific thinking.",
             "setup":["Build a tower (parent builds)","Child is the designated knocker"],
             "play":["Parent builds -- child waits and watches","Moment of anticipation -- READY?","Child knocks it down","Celebrate the collapse together"],
             "say":['"I am building... building... almost ready..."','"READY? 3, 2, 1... GO!"','"CRASH! You caused that. Did you see how it all fell?"'],
             "if_happens":"Child cannot wait and knocks during building",
             "avoid":'"Wait -- I said wait."',
             "better":'"You cannot wait -- the knocking energy is too big! OK. I will build 3 blocks fast. You can knock when I say ready. Ready? GO."',
             "why":"The anticipation-action-effect sequence in this activity is a three-part causal reasoning exercise. Waiting (anticipation) builds inhibitory control. The action (knocking) tests cause-and-effect understanding. The effect (the collapse) provides sensory confirmation. The predictability of the collapse gives children a deeply satisfying scientific confirmation: my action caused this specific result. This causal reasoning is the foundation of all scientific thinking.",
             "tool":"Cause and Effect",
             "phrases":['"You did that. That happened because of you."','"What will happen if I do this?"'],
             "skills":"Causal reasoning, anticipatory control, scientific thinking."},
        17: {"title":"Thread the Pasta","emoji":"🍝","skill":"Precision Pinch","materials":"Dry penne or rigatoni pasta, string or shoelace",
             "milestone":"Milestone: Threading requires the precision pinch grip and the coordination of both hands working together on a fine task -- the exact skills required for buttons, zippers, and eventually writing.",
             "setup":["Dry penne pasta","Thick shoelace or stiff string with a taped end"],
             "play":["Thread the pasta onto the string","Make a necklace or bracelet","Count as you thread","Try alternating colours"],
             "say":['"Hold the pasta with three fingers -- find the hole."','"Thread it through -- look for the hole on the other side."','"You made a necklace from pasta!"'],
             "if_happens":"Child cannot find the hole and gets frustrated",
             "avoid":'"The hole is there -- look harder."',
             "better":'"The hole is really small. Hold the pasta up to the light -- can you see the hole better? Now thread."',
             "why":"Pasta threading is a classic fine motor activity because it combines the tripod pinch (holding the pasta) with precision eye-hand coordination (finding the hole) and bilateral task management (one hand holds the string, one threads). The light-through-the-hole suggestion uses visual enhancement to reduce frustration -- making the task achievable without removing the fine motor challenge.",
             "tool":"Patient Fingers",
             "phrases":['"Patient fingers find the hole."','"Slow hands, careful eyes."'],
             "skills":"Precision pinch, bilateral coordination, patience, eye-hand coordination."},
        18: {"title":"Stick and Connect","emoji":"📎","skill":"Construction","materials":"Straws and tape, or cardboard tubes",
             "milestone":"Milestone: Connecting materials to build a structure develops engineering thinking -- understanding that objects can be joined to create something new and more capable than the parts alone.",
             "setup":["Straws or cardboard tubes","Tape or play dough as connectors"],
             "play":["Connect two straws with tape","Build a square, a triangle, a house shape","Try to make it stand upright","Attach one more: what happens?"],
             "say":['"Can we connect these two? What could we use?"','"Look -- it is a shape! What shape is that?"','"Now let us make it 3D -- can we add a top?"'],
             "if_happens":"Tape is not sticking and structure falls apart",
             "avoid":'"The tape is not working -- let me do it."',
             "better":'"This material is tricky. Let us try a different connection -- what if we use play dough blobs as the joints instead?"',
             "why":"Engineering construction activities at this age build what researchers call spatial thinking with materials -- the ability to mentally simulate how physical components will connect and what structure will emerge. This is different from spatial reasoning about fixed objects. Construction also introduces the engineering cycle: design, build, test, fail, redesign -- the same cycle used in adult engineering and scientific problem-solving.",
             "tool":"Build It Better",
             "phrases":['"What if we tried it a different way?"','"Engineering means failing and trying again."'],
             "skills":"Engineering thinking, construction, problem-solving."},
        19: {"title":"A House for a Toy","emoji":"🏠","skill":"Purposive Building","materials":"Cardboard box, blocks, fabric",
             "milestone":"Milestone: Building a structure for a specific purpose -- a house for a toy -- introduces functional design. The child must consider the toy's needs (size, access) and build accordingly.",
             "setup":["Choose a small toy","Gather: boxes, blocks, fabric, anything",],
             "play":["Ask: what does [toy] need in a house?","Build together based on child's specifications","Test: does [toy] fit? Does the door work?","Decorate together"],
             "say":['"What does the bear need? A door? A bed? A window?"','"Will the bear fit through this door? Let us check."','"You are the architect -- what goes here?"'],
             "if_happens":"Child wants parent to build it all",
             "avoid":'"You build it -- I am watching."',
             "better":'"OK -- you are the director, I am the builder. You say where things go and I build it exactly the way you say."',
             "why":"Purposive building -- building for a specific function -- is a more advanced construction task than building for height or novelty. The child must hold in mind the intended user's needs while simultaneously managing the physical materials. This dual task (mental model + physical execution) is one of the earliest forms of functional design thinking. The director-builder role reversal preserves the child's autonomy while providing physical assistance.",
             "tool":"Design for Someone",
             "phrases":['"You thought of what the bear needed."','"You built something that works for someone else."'],
             "skills":"Functional design, purposive building, perspective-taking."},
        20: {"title":"Puzzle Pieces","emoji":"🧩","skill":"Spatial Problem-Solving","materials":"Simple puzzle (4-10 pieces)",
             "milestone":"Milestone: Puzzles develop spatial rotation (mentally turning pieces to see if they fit), visual discrimination (noticing shape differences), and persistence. These are among the strongest predictors of mathematical achievement.",
             "setup":["A simple, chunky puzzle appropriate for this age","Table surface"],
             "play":["Try pieces without forcing","Rotate pieces -- look at the shape of the space","Celebrate each piece placed","Celebrate the completed puzzle together"],
             "say":['"Look at the hole -- what shape is it?"','"Turn the piece -- try it the other way."','"Every piece has exactly one place where it belongs."'],
             "if_happens":"Child forces pieces and gets frustrated",
             "avoid":'"Do not force it -- if it does not fit, try another."',
             "better":'"I can hear you trying hard. If it does not go with a gentle push, it is telling you: not here. Let it go and try a different piece."',
             "why":"Puzzle solving develops spatial rotation ability -- the capacity to mentally rotate two-dimensional shapes and predict how they will fit together. This is one of the most robust predictors of mathematics achievement in later schooling. The critical skill being built is not speed but strategy: look at the space, look at the piece, rotate mentally before physically. The no-forcing rule teaches children to use cognitive rather than physical force.",
             "tool":"Look Before You Try",
             "phrases":['"Look at the space first. What shape does it need?"','"Think before you push."'],
             "skills":"Spatial rotation, visual discrimination, strategic thinking."},
        21: "reflection",
        22: {"title":"Make a Card","emoji":"💌","skill":"Purposive Creation","materials":"Paper, crayons, stickers",
             "milestone":"Milestone: Making a card for another person integrates fine motor skill, creative expression, and theory of mind (thinking about the recipient's preferences). It is one of the earliest forms of purposive social art.",
             "setup":["Paper folded in half","Crayons, stickers, whatever is available"],
             "play":["Who is the card for?","What do they like? (Draw that)","Write (or dictate) a message","Decorate with whatever feels right"],
             "say":['"What does Grandpa love? Draw that for him."','"What should the card say? I will write it."','"Look what you made for someone you love."'],
             "if_happens":"Child scribbles quickly and declares it done after 20 seconds",
             "avoid":'"That is not finished -- add more."',
             "better":'"If that is done, it is done. Simple can be beautiful. Shall we put it in an envelope?"',
             "why":"Purposive social art -- making something with a specific recipient in mind -- requires the child to exit their own perspective and consider someone else's preferences. This is a theory of mind exercise embedded in a creative task. Research shows that the act of making for others significantly increases the meaning attributed to the creation and produces stronger emotional engagement than making for oneself.",
             "tool":"Made with Love",
             "phrases":['"You thought about them while you made this."','"This card carries your love."'],
             "skills":"Theory of mind, purposive creation, social expression."},
        23: {"title":"Cook Together","emoji":"🍪","skill":"Sequential Following","materials":"Simple no-bake recipe",
             "milestone":"Milestone: Simple cooking develops sequential thinking (step 1, then step 2), measurement concepts, cause and effect (mixing creates change), and the deep satisfaction of producing something edible.",
             "setup":["Choose a 3-4 step recipe: mixing trail mix, spreading butter on bread","Lay out ingredients"],
             "play":["Work through steps together","Child does as much as possible (pouring, mixing, spreading)","Name each ingredient","Eat what you made together"],
             "say":['"First we do this... then this... then this."','"Pour it in -- you do the pouring."','"We made this together -- eat what your hands made!"'],
             "if_happens":"Child wants to eat ingredients before the cooking is done",
             "avoid":'"Do not eat yet -- wait until it is finished."',
             "better":'"I knew you could not resist -- me neither. One taste now, and then we finish and eat the whole thing."',
             "why":"Following a recipe is one of the earliest real-world applications of sequential thinking. Each step depends on the completion of the previous one, which teaches procedural logic. The sensory richness of cooking -- taste, smell, texture, temperature -- also provides multi-sensory encoding that makes the activity deeply memorable. Sharing and eating the product creates a satisfying social closure that reinforces the motivation to cook again.",
             "tool":"Step by Step",
             "phrases":['"First, then, finally -- that is cooking."','"Your hands made something you can eat."'],
             "skills":"Sequential thinking, fine motor (pouring, mixing), cause and effect."},
        24: {"title":"Wrap a Gift","emoji":"🎁","skill":"Problem-Solving","materials":"Paper, tape, a small box",
             "milestone":"Milestone: Wrapping a gift is a spatial problem-solving task -- the child must figure out how to cover an irregular 3D shape with a flat 2D material. This is the same spatial reasoning used in geometry.",
             "setup":["A small box or object","Paper slightly larger than the box, tape"],
             "play":["Try to wrap the box -- no instructions","Problem-solve together when it gets tricky","Tape as needed","Decorate the outside"],
             "say":['"Can you figure out how to cover the box with the paper?"','"What happens to the corners? Tricky!"','"Now someone has to open this -- who is it for?"'],
             "if_happens":"Child cannot manage the paper and gets frustrated",
             "avoid":'"Let me show you the right way to wrap."',
             "better":'"This is one of the hardest things -- even adults struggle with it. Let us just cover the top first. Just the top. Then the sides."',
             "why":"Gift wrapping is a 3D spatial problem with no single solution. There are multiple valid wrapping techniques and children find their own intuitive solutions when given space to problem-solve without demonstration. Seeing a parent also struggle with the corners normalises difficulty and demonstrates that persistence in the face of a genuine challenge is what matters. The social purpose (someone will open this) adds motivational value.",
             "tool":"Figure It Out",
             "phrases":['"There is no one right way to wrap a gift."','"Your way of solving it is valid."'],
             "skills":"Spatial problem-solving, persistence, 3D reasoning."},
        25: {"title":"Make a Book","emoji":"📚","skill":"Narrative + Fine Motor","materials":"Paper, stapler, crayons",
             "milestone":"Milestone: Making a book integrates storytelling (narrative), drawing (visual representation), sequencing (what comes first), and physical construction -- a holistic developmental activity that also builds early literacy identity.",
             "setup":["Fold 4 pages of paper and staple","Choose a simple story: a walk, a meal, a day"],
             "play":["Each page: one thing that happened","Draw it (parent writes words if child dictates)","Put the pages in order","Read it together"],
             "say":['"What happened first on our walk? Draw it."','"What came next? That goes on page 2."','"You are the author. I am reading YOUR book."'],
             "if_happens":"Child wants each page to be a different random thing",
             "avoid":'"The pages need to be a story -- in order."',
             "better":'"What if each page is a different thing you love? That is also a book -- a book about your favourite things."',
             "why":"Child-made books serve as concrete literacy artifacts -- objects that demonstrate that books are made by people, contain ideas that belong to someone, and can be created by anyone. Research shows that children who make their own books before formal literacy instruction develop stronger reading motivation and print awareness than those who only consume books. The physical act of construction also builds the understanding that books have structure: cover, pages, sequence.",
             "tool":"Author Within",
             "phrases":['"You made a book. You are a creator."','"Your story is worth a book."'],
             "skills":"Narrative sequencing, early literacy, fine motor construction."},
        26: {"title":"Create a Gift","emoji":"🎀","skill":"Altruistic Creation","materials":"Anything available: nature items, paper, fabric",
             "milestone":"Milestone: Freely creating a gift -- using whatever is available -- develops creative resourcefulness alongside altruism. The combination of creative constraint and social purpose produces some of the most meaningful work children do.",
             "setup":["Walk around the house or garden","Gather things that could become a gift"],
             "play":["Ask: who do you want to make something for?","Use only what is available -- no buying","Make it together","Present it"],
             "say":['"What can we find to make into a gift? Look around..."','"What would make this person smile?"','"You made a gift from nothing -- that is the best kind."'],
             "if_happens":"Child says they need special supplies and does not have them",
             "avoid":'"You have everything you need -- be creative."',
             "better":'"I know it feels like we do not have the right things. What is the ONE thing that would make it feel like a gift? Even just paper? Even just a ribbon?"',
             "why":"Resource-constrained creation develops creative resourcefulness -- the ability to make something meaningful from available materials. Research in creativity shows that constraints actually enhance creative output by forcing novel combinations and approaches. The altruistic frame (making for someone specific) also adds emotional depth to the creative process, producing work that is more meaningful than open-ended art.",
             "tool":"Create from What Is Here",
             "phrases":['"The best gifts come from what you already have."','"A made thing is more precious than a bought thing."'],
             "skills":"Creative resourcefulness, altruism, gift-giving."},
        27: {"title":"The Gallery Show","emoji":"🖼️","skill":"Ownership and Pride","materials":"This month's artwork",
             "milestone":"Milestone: Displaying and presenting one's own work builds creative pride, the ability to reflect on one's own creations, and the early understanding that made things have value and can be shared.",
             "setup":["Gather everything made this month","Tape works to a wall or lay them out"],
             "play":["Walk the gallery together","Child describes each piece","Parent asks curious questions","Invite another family member to view"],
             "say":['"Tell me about this one -- what was happening?"','"This is your gallery -- you made all of this."','"Which one are you most proud of?"'],
             "if_happens":"Child dismisses all their work as bad",
             "avoid":'"That is not bad -- it is lovely!"',
             "better":'"What do you see that bothers you? I am curious -- what would make it better for you?"',
             "why":"Presenting one's own work activates self-referential processing -- thinking about oneself as a creator. This is a form of metacognition (thinking about one's own thinking) and is associated with stronger creative development. The gallery format also communicates a powerful message: your work is worth displaying, worth looking at, worth discussing. Children who experience this develop stronger creative identities and higher creative self-efficacy.",
             "tool":"Creator Pride",
             "phrases":['"Your hands made all of this."','"Being proud of your work is allowed."'],
             "skills":"Creative pride, self-reflection, ownership."},
        28: "reflection",
        29: {"title":"Portfolio Review","emoji":"🗂️","skill":"Reflection + Memory","materials":"All month's work gathered",
             "milestone":"Milestone: Reviewing a month of work and noticing growth is an early form of self-assessment. Children who learn to evaluate their own progress develop stronger intrinsic motivation than those who only receive external evaluation.",
             "setup":["Collect all artwork and projects from the month","Lay them out chronologically"],
             "play":["Ask: which was hardest at the beginning?","Ask: which feels easier now?","Choose 3 favourites to keep","Reflect: what did your hands learn this month?"],
             "say":['"Look at all the things your hands made this month."','"Which one was the hardest? Which one felt easy by the end?"','"What can your hands do now that they could not do at the start of the month?"'],
             "if_happens":"Child cannot identify any growth",
             "avoid":'"Look how much better you got!"',
             "better":'"Compare Day 1 and today. Look at the lines. Is there any difference? Even small?"',
             "why":"Portfolio review is a form of self-directed metacognitive reflection -- the child is explicitly comparing their current performance to a past baseline. This builds growth mindset not through praise but through evidence: the child can see their own development in concrete form. Research by Carol Dweck shows that growth mindset is most strongly built not by telling children they improved but by showing them the evidence of their own growth.",
             "tool":"See Your Growth",
             "phrases":['"You can see your own growth right here."','"Past you and today you made different marks."'],
             "skills":"Self-assessment, growth mindset, metacognition."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 5 Complete: Maker's Medal!",
        "summary": "This month your child's hands learned to tear, squeeze, scribble, build, thread, and create. Fine motor skills built this month will underpin writing, dressing, and creative confidence for years.",
        "skills_built": ["Fine motor: tear, pinch, roll, press, thread", "Pre-writing: circles, faces, scribbles, lines", "Construction: towers, houses, connected structures", "Creative expression: stamps, finger paint, draw to music", "Altruism: cards, books, gifts for others"],
        "month_next_teaser": "Next month: Pretend and Story. Your child will build imaginative worlds, retell stories, act out characters, and begin creating their own narratives.",
    },
    "reflection_activities": {
        7:  {"activity": "Hand Strength Test", "desc": "Ask your child to squeeze your finger as hard as they can. Then squeeze theirs. Celebrate the grip."},
        14: {"activity": "Scribble Evolution", "desc": "Look at Day 1 scribbles and today's drawing. What changed? Even subtle differences are worth celebrating."},
        21: {"activity": "Best Build Challenge", "desc": "Build the tallest tower you can in 2 minutes. Photograph it. This is your Week 3 record."},
        28: {"activity": "Making Gallery", "desc": "Lay out everything made this month. Which piece took the most courage to make? Which one surprised you?"},
    },
}
