"""Month 6: Pretend & Story -- curriculum data"""
M6 = {
    "name": "Pretend & Story",
    "toolkit_label": "2--3 Years &middot; Month 6",
    "weeks": {
        1: {"title": "Let's Pretend", "subtitle": "When the world becomes whatever you imagine"},
        2: {"title": "Story Sequencing", "subtitle": "First, then, next -- the building blocks of narrative"},
        3: {"title": "Characters & Feelings", "subtitle": "Every character has an inner world"},
        4: {"title": "Our Own Story", "subtitle": "Creating something that did not exist before"},
    },
    "days": {
        1:  {"title":"I Am a...","emoji":"🦁","skill":"Imaginative Play","materials":"None",
             "milestone":"Milestone: Pretend play -- adopting a role or character -- emerges around 18 months and becomes rich and complex between 2 and 4 years. It is one of the primary mechanisms through which children develop theory of mind, emotional regulation, and narrative intelligence.",
             "setup":["Stand in an open area","Start by modelling"],
             "play":["You become a lion: ROAR! Walk on all fours","Child chooses: what animal or character?","Be your character fully for 5 minutes","Switch characters"],
             "say":['"I am a lion -- ROAR!"','"What are you? Show me how your character moves."','"My lion is hungry -- what does your character do?"'],
             "if_happens":"Child wants to be the same thing as you rather than choose",
             "avoid":'"You have to be something different."',
             "better":'"Two lions! Even better. OK -- are we the same pride or different? That changes everything."',
             "why":"Role adoption in pretend play requires the child to hold two realities simultaneously: their real identity and the character's identity. This dual representation is cognitively demanding and is one of the clearest early indicators of the theory of mind development that allows children to understand that others have different perspectives, beliefs, and experiences. It is the same cognitive capacity needed to understand story characters.",
             "tool":"Who Are You Today?",
             "phrases":['"You can be anyone you imagine."','"Your pretend is real while we play."'],
             "skills":"Imaginative play, role adoption, theory of mind."},
        2:  {"title":"Play Shop","emoji":"🛒","skill":"Social Role Play","materials":"Household items as products, play money (optional)",
             "milestone":"Milestone: Playing shop introduces social roles (buyer/seller), transactional language (how much? here you go), and mathematical concepts (counting, exchange) within a meaningful social context.",
             "setup":["Arrange toys or household items on a shelf","Designate who is shopkeeper first"],
             "play":["Shopkeeper sets up -- child is customer (or reverse)","Browse, ask prices, pay","Swap roles","Add complexity: out of stock, wrong change"],
             "say":['"Welcome to my shop! What would you like today?"','"That costs 3 -- do you have 3?"','"We are out of that -- can I suggest this instead?"'],
             "if_happens":"Child wants to keep all items and not sell them",
             "avoid":'"You have to sell them -- that is the shop."',
             "better":'"Your shop has special items that are not for sale -- only for looking. I want to buy one that IS for sale. Which ones can I buy?"',
             "why":"Shopkeeper play is socially and cognitively rich because it requires negotiation of roles, turn-taking, transactional language (buying, selling, not enough, change), and the capacity to sustain a shared imaginative scenario. Research shows that the quality of pretend play at age 3 is one of the strongest predictors of social competence at school entry. The role-swap is particularly valuable as it builds flexibility.",
             "tool":"Different Role, Different View",
             "phrases":['"You see it differently when you are the shopkeeper."','"Both roles teach you something new."'],
             "skills":"Social role play, transactional language, perspective-taking."},
        3:  {"title":"Doctor and Patient","emoji":"🩺","skill":"Empathy Role Play","materials":"Toy stethoscope or ruler, small toy as patient",
             "milestone":"Milestone: Doctor-patient play allows children to safely rehearse both vulnerability (being the patient) and competence (being the doctor), processing fears about medical experiences through play.",
             "setup":["Set up a pretend clinic","Child is doctor, stuffed animal is patient (initially)"],
             "play":["Animal is sick: what is wrong?","Doctor examines, prescribes, reassures","Swap: child is now patient","Introduce: patient is scared -- what does the doctor say?"],
             "say":['"The bear has a sore tummy -- what do you think, Doctor?"','"What does the patient need to feel better?"','"The patient is scared. What would a kind doctor say?"'],
             "if_happens":"Child as doctor is rough with the patient",
             "avoid":'"Be gentle -- that hurts the patient."',
             "better":'"Oh, the patient said that hurt. A good doctor always asks: is this OK? And listens to the answer."',
             "why":"Doctor play processes medical anxiety through the safe container of pretend. Children who have had medical experiences benefit especially from playing doctor because the role reversal gives them power and control in a context where they previously felt powerless. The consent element -- asking the patient if something is OK -- also introduces early, embodied consent education in a medical context.",
             "tool":"Gentle Care",
             "phrases":['"Kind hands make patients feel safe."','"Asking is part of being a good doctor."'],
             "skills":"Empathy, processing experience, consent in care."},
        4:  {"title":"Cooking Pretend Food","emoji":"🍳","skill":"Imitation + Creativity","materials":"Play kitchen or pots and blocks as food",
             "milestone":"Milestone: Cooking pretend food requires object substitution -- using a block as food -- which is one of the most cognitively demanding forms of pretend play. It demonstrates that the child understands that objects can represent other objects.",
             "setup":["Any pots and objects","Blocks, stones, or lids as food ingredients"],
             "play":["Cook together -- what are we making?","Add imaginary ingredients","Stir, taste, serve","Have a pretend meal together"],
             "say":['"What are we cooking today?"','"I will add the imaginary pepper -- mmm!"','"Taste test! What does it need more of?"'],
             "if_happens":"Child insists on real food instead of pretend",
             "avoid":'"This is pretend -- just go along with it."',
             "better":'"OK -- let us get one real ingredient and the rest can be pretend. Which real thing makes it most fun?"',
             "why":"Object substitution -- using one object to represent another -- is a cognitive achievement that requires the child to hold dual representations: this block IS a carrot in our game, but it is also really a block. This dual representation is the same cognitive capacity used in reading (these marks represent words) and mathematics (this numeral represents a quantity). The emergence of object substitution marks a significant leap in symbolic thinking.",
             "tool":"This Becomes That",
             "phrases":['"In our game, this block is a carrot."','"Pretend makes anything into anything."'],
             "skills":"Object substitution, symbolic thinking, cooperative play."},
        5:  {"title":"Going on a Journey","emoji":"✈️","skill":"Narrative Imagination","materials":"Blankets, pillows -- make a vehicle",
             "milestone":"Milestone: Journey play combines narrative planning (where are we going?), spatial imagination (what does it look like there?), and role play (who are we in this story?). It develops narrative intelligence.",
             "setup":["Build a vehicle from cushions and blankets","Decide on a destination"],
             "play":["Get in the vehicle -- where are we going?","Describe the journey (narrate together)","Arrive and explore (imaginary)","Return home -- what did we bring back?"],
             "say":['"Buckle up -- we are going to the JUNGLE!"','"Look out the window -- what do you see?"','"We are landing! What do you hear?"'],
             "if_happens":"Child wants to go to a specific real place (not imaginative)",
             "avoid":'"This is pretend -- we cannot really go there."',
             "better":'"Let us go to the pretend version of that place -- where everything is bigger and better. What should we find there that is only in the pretend version?"',
             "why":"Journey narratives are among the oldest human story structures. Playing out journeys with a caregiver helps children develop narrative schemas -- the internal templates for how stories are structured (leaving, travelling, arriving, returning). These narrative schemas are the scaffolding that reading comprehension instruction later builds on. Children with richer pretend narrative experience understand story structure more easily.",
             "tool":"Journey Story",
             "phrases":['"Every story has a beginning, a journey, and a return."','"We left. We went. We came back. That is a story."'],
             "skills":"Narrative structure, spatial imagination, role play."},
        6:  {"title":"The Telephone","emoji":"📞","skill":"Conversation Role Play","materials":"Two toy phones or banana-shaped objects",
             "milestone":"Milestone: Telephone play rehearses the conversational turn-taking structure: speak, listen, respond, speak. This explicit practice of dialogue structure helps children develop conversational competence.",
             "setup":["Two objects as phones (bananas, blocks, anything)","Sit apart from each other"],
             "play":["Call each other -- ring ring!","Have a pretend conversation","Ask questions, respond, say goodbye","Try: calling a character (grandma, a bear, a rocket ship)"],
             "say":['"Ring ring! Hello? Who is this?"','"Hello! I am calling to say I love you."','"What shall we talk about? I have some very important news."'],
             "if_happens":"Child just holds the phone and says nothing",
             "avoid":'"Say something -- I am waiting."',
             "better":'"I will talk enough for both of us until you are ready. So anyway, I just saw the most amazing thing -- a purple elephant on the street. Did you see it too?"',
             "why":"Telephone play exaggerates the turn-taking structure of conversation by physically separating the speakers and removing visual cues. This forces reliance on verbal communication alone, building verbal expression. The structured constraint (one speaks, other listens) models the conversation scaffold that many children need made explicit. The absurdist content (purple elephant) also reduces performance anxiety.",
             "tool":"Speaking and Listening",
             "phrases":['"Conversations go back and forth -- like a ball."','"It is your turn to speak -- I am listening."'],
             "skills":"Conversational turn-taking, verbal expression, listening."},
        7:  "reflection",
        8:  {"title":"What Happened First?","emoji":"1️⃣","skill":"Story Sequencing","materials":"3 pictures from a simple book or drawn by adult",
             "milestone":"Milestone: Sequencing events in correct order develops narrative comprehension and temporal reasoning -- understanding that events have a before and after. This is foundational for reading comprehension and historical thinking.",
             "setup":["Draw or find 3 simple pictures showing beginning, middle, end","Mix them up"],
             "play":["Look at the pictures together","Ask: which one happened first?","Put them in order -- first, then, finally","Tell the story using the ordered pictures"],
             "say":['"Which one happened FIRST?"','"What comes next?"','"Now tell me the story from the beginning."'],
             "if_happens":"Child puts them in wrong order confidently",
             "avoid":'"That is wrong -- look again."',
             "better":'"Interesting order! Tell me the story in YOUR order -- why did you put it this way?"',
             "why":"Sequencing requires the child to understand temporal relationships (before/after) and causal relationships (this happened because of that). These logical structures underpin all narrative comprehension and are a primary reason why young children who cannot sequence struggle with reading comprehension later. The tell-me-the-story-in-your-order approach respects creative retelling while also developing logical sequential reasoning.",
             "tool":"First Then Finally",
             "phrases":['"First... then... finally. That is a story."','"Every story has a direction."'],
             "skills":"Sequencing, temporal reasoning, narrative structure."},
        9:  {"title":"Retell a Book","emoji":"📖","skill":"Story Retelling","materials":"A picture book you have read before",
             "milestone":"Milestone: Retelling a known story from memory builds narrative memory consolidation, vocabulary, and the confidence of knowing a story -- which is one of the most important literacy readiness skills.",
             "setup":["A familiar book the child knows well","Set it down -- do not open it yet"],
             "play":["Ask: can you tell me the story without opening the book?","Let them lead -- no corrections","Open the book after and compare","Celebrate what they remembered"],
             "say":['"Tell me this story -- you know it."','"I will just listen -- go!"','"You remembered [detail]! I did not even remember that."'],
             "if_happens":"Child says they cannot remember",
             "avoid":'"Try -- you know this story."',
             "better":'"OK -- I will start. Once upon a time there was [first character]... now you go."',
             "why":"Story retelling activates and strengthens episodic memory for narrative content. Research shows that children who retell stories to their parents show significantly better reading comprehension in school than those who are only read to. The process of retrieval -- pulling the story from memory -- is itself a powerful memory consolidation technique. Celebrating what was remembered (not correcting what was forgotten) builds retelling confidence.",
             "tool":"Your Memory of the Story",
             "phrases":['"The story lives in your memory now."','"You carry this story inside you."'],
             "skills":"Story retelling, narrative memory, oral language."},
        10: {"title":"First Then Finally","emoji":"📋","skill":"Narrative Grammar","materials":"None",
             "milestone":"Milestone: The first-then-finally story grammar is one of the simplest and most powerful narrative structures. Children who internalise this three-part structure understand the majority of picture books they encounter.",
             "setup":["Think of a simple 3-part story together","Use something that really happened today"],
             "play":["Tell the story in 3 parts: FIRST... THEN... FINALLY...","Child fills in the parts","Try a real event and a made-up event","Help child notice: all stories have this shape"],
             "say":['"FIRST: this morning we... THEN: we... FINALLY: we..."','"Now you tell one. FIRST..."','"Does your made-up story have a finally?"'],
             "if_happens":"Child adds more and more parts and cannot stop",
             "avoid":'"That is enough -- stop now."',
             "better":'"This is an epic story! It has so many parts. Let us find the FINALLY -- the last thing that happens. What ends your story?"',
             "why":"Story grammar -- the internal structure of narratives -- is one of the most important pre-literacy concepts. Stories that follow first-then-finally are easier to comprehend and remember because they match the temporal-causal structure of episodic memory. Children who internalise story grammar before reading instruction begin reading comprehension from a strong cognitive foundation.",
             "tool":"Story Shape",
             "phrases":['"Every story needs a finally."','"First, then, finally -- the story skeleton."'],
             "skills":"Story grammar, temporal sequencing, narrative comprehension."},
        11: {"title":"What Comes Next?","emoji":"❓","skill":"Story Prediction","materials":"A picture book",
             "milestone":"Milestone: Story prediction -- inferring what will happen next before reading on -- builds the active reading comprehension habit that differentiates strong readers from weak ones.",
             "setup":["A familiar or new picture book","Stop at key moments"],
             "play":["Read, then STOP: what do you think happens next?","Accept all predictions -- they are all valid","Read on: what actually happened?","Talk about: was the prediction similar? Different?"],
             "say":['"What do you think is going to happen next?"','"Why do you think that?"','"Let us find out -- was your prediction right?"'],
             "if_happens":"Child says I do not know to every prediction",
             "avoid":'"Just guess -- there is no wrong answer."',
             "better":'"What would YOU do if you were the character right now? What do you want to happen?"',
             "why":"Prediction during reading activates the brain's default mode network -- the narrative simulation system that builds causal models of story events. Research shows that readers who make and check predictions show significantly stronger comprehension retention than passive readers. The habit of prediction is the single most teachable reading comprehension strategy and begins to develop in the second year of life during shared reading.",
             "tool":"What Comes Next?",
             "phrases":['"I wonder what happens next."','"Predict before you peek."'],
             "skills":"Story prediction, active comprehension, causal reasoning."},
        12: {"title":"Make Up an Ending","emoji":"✍️","skill":"Narrative Creativity","materials":"A picture book with the ending covered",
             "milestone":"Milestone: Creating an alternative ending to a known story requires understanding of story logic (the ending must follow from what came before) AND creative freedom. It develops both narrative intelligence and creative confidence.",
             "setup":["A book with the last page covered or folded","Read up to the last page"],
             "play":["Stop before the end: what ending do you choose?","Let child decide the ending -- no corrections","Reveal the real ending","Which ending do you prefer and why?"],
             "say":['"We are making our own ending -- what should happen?"','"Your ending is the only real ending for our story today."','"The book ending and your ending are both true -- in different versions."'],
             "if_happens":"Child's ending is chaotic or violent",
             "avoid":'"That is not a good ending -- try again."',
             "better":'"OK. After all of that chaos -- what happens AFTER? Everyone is in a mess. Now what?"',
             "why":"Alternative ending creation requires the child to hold the story context in mind while generating novel content that fits within that context. This constrained creativity is more cognitively demanding than open-ended story creation. Research shows that children who practise alternative narrative creation develop stronger reading comprehension because they understand that stories could have been different -- which means they understand the choices authors make.",
             "tool":"Your Ending is Valid",
             "phrases":['"Your ending is the real one for our story."','"Authors choose endings -- so can you."'],
             "skills":"Narrative creativity, story logic, authorial agency."},
        13: {"title":"Act Out a Story","emoji":"🎭","skill":"Embodied Narrative","materials":"A simple story you know",
             "milestone":"Milestone: Acting out a story -- embodying characters through movement and voice -- deepens comprehension and emotional engagement with narrative. It is the most ancient form of human storytelling.",
             "setup":["Choose a known story with 2+ characters","Assign roles"],
             "play":["Act out the story -- move, use voices, use props","Stay in character","When it is finished, swap roles and act again","Talk about: what was different in each version?"],
             "say":['"You are the bear -- what does the bear say?"','"How does the bear MOVE? Show me."','"Now I am the bear -- watch how I do it."'],
             "if_happens":"Child breaks character to direct you instead",
             "avoid":'"Stay in character -- you are the bear, not the director."',
             "better":'"Oh, you want to direct? Great -- you direct me. Tell me exactly what to do."',
             "why":"Story embodiment -- acting out rather than watching or telling -- activates motor memory, emotional memory, and narrative memory simultaneously. Research shows that children who physically enact stories comprehend and retain them significantly better than those who only hear or read them. The role-swap reveals how the same story looks different from different characters' perspectives -- building theory of mind.",
             "tool":"Be the Story",
             "phrases":['"When you ARE the character, you understand them better."','"Your body knows the story too."'],
             "skills":"Embodied narrative, comprehension, character perspective."},
        14: "reflection",
        15: {"title":"Who Is the Character?","emoji":"👤","skill":"Character Analysis","materials":"Picture book",
             "milestone":"Milestone: Identifying and describing characters -- who they are, what they want, what they feel -- builds the literary analysis skills that underpin all future language arts education.",
             "setup":["Any picture book with a clear main character","Focus on the character, not the plot"],
             "play":["Ask: who is this character?","What does this character want?","What does this character feel on this page?","Is this character like you in any way?"],
             "say":['"Tell me about this character -- who are they?"','"What does this character want more than anything?"','"Are they like you? How? How not?"'],
             "if_happens":"Child can only say the character's name, no deeper description",
             "avoid":'"Tell me more -- what are they like?"',
             "better":'"OK, I know their name. Now -- if I met this character at the park, what would I notice about them first?"',
             "why":"Character analysis builds theory of mind -- the capacity to model another person's mental states, desires, and intentions. The question 'what does this character want?' is particularly powerful because it requires the child to enter the character's motivational world. Research shows that children who are regularly asked character motivation questions during reading develop significantly stronger empathy and social competence.",
             "tool":"Character Lens",
             "phrases":['"Understanding the character means understanding their heart."','"What does this character want most?"'],
             "skills":"Character analysis, theory of mind, empathy."},
        16: {"title":"How Does the Character Feel?","emoji":"❤️","skill":"Emotional Reading","materials":"Picture book",
             "milestone":"Milestone: Identifying characters' emotions from facial expressions, body language, and story context develops the multi-modal emotional reading that is essential for social intelligence.",
             "setup":["Picture book with expressive illustrations","Focus on facial expressions and body language"],
             "play":["Turn to an emotional moment in the book","Cover the words -- read only the picture","Ask: what is this character feeling? How do you know?","Check: what do the words say? Did you read it right?"],
             "say":['"I covered the words -- what do the pictures tell you?"','"How can you tell that is how they feel?"','"Your eyes read the feeling before the words."'],
             "if_happens":"Child names the surface action, not the feeling (they are running)",
             "avoid":'"But HOW do they feel -- happy or sad?"',
             "better":'"They are running! Fast or slow running? What kind of running looks like scared running versus excited running?"',
             "why":"Picture books are designed to carry emotional information in two parallel channels: the words and the illustrations. Teaching children to read the illustration channel independently builds visual emotional literacy -- the ability to read body language and facial expression without verbal cues. This skill directly transfers to social situations where people's words and bodies communicate different things.",
             "tool":"Read the Picture",
             "phrases":['"The pictures carry the feelings."','"What does the body say even before the words?"'],
             "skills":"Visual emotional reading, multi-modal literacy, social perception."},
        17: {"title":"The Villain Has Feelings Too","emoji":"😈","skill":"Complex Empathy","materials":"A story with a villain or antagonist",
             "milestone":"Milestone: Understanding that even antagonists have inner worlds and motivations -- that no one is simply bad -- is a significant development in moral and social reasoning. It is foundational for conflict resolution.",
             "setup":["A story with a clear antagonist (wolf, witch, etc.)","Approach with curiosity"],
             "play":["Ask: why does the wolf/witch do what they do?","Invent a backstory: maybe they are hungry, lonely, scared","Does having a reason change how you feel about them?","Can you feel sorry for AND disagree with someone?"],
             "say":['"Why do you think the wolf is so mean?"','"What if the wolf is just very hungry and no one will share?"','"You can understand someone AND still think what they did was wrong."'],
             "if_happens":"Child insists the villain is just bad",
             "avoid":'"No -- everyone has a reason."',
             "better":'"What made them start being bad, do you think? They were not born bad -- what happened?"',
             "why":"Attribution of inner states to antagonists is a sophisticated theory of mind task because it requires extending empathy beyond likeable characters to those who act harmfully. Children who develop this capacity show stronger moral reasoning -- they can distinguish between a person and their actions. Research shows this is a protective factor against both victimisation (understanding bullies) and bullying behaviour.",
             "tool":"Inside the Villain",
             "phrases":['"Even the villain has feelings."','"Understanding someone is not the same as agreeing with them."'],
             "skills":"Complex empathy, moral reasoning, perspective-taking."},
        18: {"title":"Be the Character","emoji":"🎭","skill":"Character Embodiment","materials":"None",
             "milestone":"Milestone: Fully embodying a character -- speaking, moving, and making decisions as that character -- deepens theory of mind by requiring the child to sustain a different perspective continuously.",
             "setup":["Choose a character from a known story","Both characters are from the same story (ideally)"],
             "play":["Stay in character for 5-10 minutes","Make decisions as the character would","React to events as the character would","Come out of character -- what was it like in there?"],
             "say":['"I am the giant. I live in my castle and I am very lonely."','"What does your character think about MY character?"','"Coming out of character now -- what was it like being them?"'],
             "if_happens":"Child breaks character to comment as themselves",
             "avoid":'"Stay in character."',
             "better":'"Oh, you stepped out -- sometimes we need to. Tell me what you noticed from outside. Then step back in."',
             "why":"Sustained character embodiment is one of the most demanding theory of mind tasks available to young children because it requires continuous perspective maintenance rather than the brief, discrete perspective shifts of simpler pretend play. Children who engage in sustained role play show significantly more advanced mentalising on standardised tasks. The post-play debrief (what was it like in there?) adds metacognitive processing.",
             "tool":"Step Inside",
             "phrases":['"Being someone else for a while teaches you things about them."','"What was it like looking out through their eyes?"'],
             "skills":"Theory of mind, sustained perspective-taking, character embodiment."},
        19: {"title":"Talk Like the Character","emoji":"🗣️","skill":"Voice and Register","materials":"None",
             "milestone":"Milestone: Adopting a character's voice -- changing pitch, pace, and vocabulary -- develops register awareness: the understanding that people use language differently in different contexts and roles.",
             "setup":["Choose a character with a distinctive voice","Practise the voice together first"],
             "play":["Speak only as the character for 5 minutes","Use the character's vocabulary and speech patterns","Interview each other as characters","What does the character say when surprised? Angry? Happy?"],
             "say":['"This character speaks slowly and very carefully -- like this..."','"What would this character say if they saw a rainbow?"','"Interview me -- I am the giant -- ask me anything."'],
             "if_happens":"Child cannot maintain a different voice consistently",
             "avoid":'"You keep using YOUR voice."',
             "better":'"Voices are hard to hold. Just one word: how would the giant say HELLO? Just that one word. Giant hello."',
             "why":"Register flexibility -- the ability to shift vocabulary, tone, and speech pattern according to context and role -- is one of the most sophisticated linguistic skills. It is the same capacity used in social code-switching (speaking differently at home versus school) and empathy (choosing words that fit the listener). Starting with just one word (how does the giant say hello?) reduces the task to a manageable increment.",
             "tool":"Character Voice",
             "phrases":['"Every character has their own way of speaking."','"Try just one word in the character voice."'],
             "skills":"Register awareness, voice modulation, linguistic flexibility."},
        20: {"title":"What Would the Character Do?","emoji":"🔮","skill":"Character Decision-Making","materials":"A picture book or scenario cards",
             "milestone":"Milestone: Predicting character decisions based on personality and values builds the logical inference skills that are the core of reading comprehension and moral reasoning.",
             "setup":["A known character from a book or film","Present a new scenario they have never faced"],
             "play":["Scenario: the character finds a bag of gold. What do they do?","Give reasons: why would they do that?","What would a different character do?","What would YOU do?"],
             "say":['"If [character] found the gold -- what would they do with it?"','"Why? What is it about them that makes you think that?"','"What would you do -- the same or different?"'],
             "if_happens":"Child just says what they themselves would do",
             "avoid":'"But what would the CHARACTER do -- not you."',
             "better":'"What you would do and what they would do -- are they the same? What is different about you and them?"',
             "why":"Predicting character decisions from character traits is a form of logical inference -- if character X has quality Y, then in situation Z, they will probably do A. This syllogistic reasoning in narrative context is the earliest form of deductive reasoning accessible to young children. Research shows it is one of the most powerful predictors of reading comprehension in formal schooling.",
             "tool":"Character Logic",
             "phrases":['"The character would do that because of who they are."','"Character decides action."'],
             "skills":"Character inference, deductive reasoning, moral comparison."},
        21: "reflection",
        22: {"title":"Our Family Story","emoji":"👨‍👩‍👧","skill":"Personal Narrative","materials":"Family photos (optional)",
             "milestone":"Milestone: Creating a personal family narrative -- the story of our family -- builds autobiographical memory, family identity, and the child's sense of belonging within a larger story.",
             "setup":["Look at a few family photos or just talk from memory","Start with how the family started"],
             "play":["Tell the story: how did our family begin?","What are the important chapters of our family's story?","What is the best part of our story?","What chapter are we in right now?"],
             "say":['"Our family story started when..."','"What is the best chapter of our family story so far?"','"Right now we are in the chapter called..."'],
             "if_happens":"Child does not know the family's earlier story",
             "avoid":'"You should know this."',
             "better":'"You were not born yet for that chapter -- let me tell you it. Then you can tell ME the chapter that started when you arrived."',
             "why":"Family narrative -- knowing and being able to tell the story of one's family -- is one of the strongest predictors of resilience in children and adolescents. Research by Marshall Duke and Robyn Fivush showed that children who know more of their family story show significantly better outcomes across domains including self-esteem, emotional regulation, and academic achievement. The oscillating narrative (ups and downs) is particularly associated with resilience.",
             "tool":"Our Story",
             "phrases":['"You are a chapter in our family story."','"Knowing our story helps you know yourself."'],
             "skills":"Personal narrative, family identity, autobiographical memory."},
        23: {"title":"Make Your Own Book","emoji":"📗","skill":"Authorship","materials":"Paper, stapler, crayons",
             "milestone":"Milestone: Creating an original book -- not retelling a known story but inventing a new one -- develops creative authorship, narrative planning, and the identity of author.",
             "setup":["Fold and staple 5-6 pages","Declare: today we make a book that has never existed before"],
             "play":["Child dictates -- parent writes","Child illustrates each page","Give the book a title","Put author name on the cover"],
             "say":['"What is the name of your book?"','"Who is the main character?"','"What happens in the end?"'],
             "if_happens":"Child's story has no ending or goes in circles",
             "avoid":'"You need a proper ending."',
             "better":'"This story keeps going! It could go on forever. Let us choose an ending -- just for this version. We can make another version with a different ending."',
             "why":"Original authorship is a fundamentally different cognitive task from retelling: it requires building a narrative from scratch, making character and plot decisions, and maintaining internal consistency. The act of seeing one's story written down and illustrated creates a powerful externalization of the inner world. Research on early literacy shows that children who create their own books before formal reading instruction develop stronger reading motivation and comprehension.",
             "tool":"You Are the Author",
             "phrases":['"Your story has never existed before."','"You decided everything in this book."'],
             "skills":"Creative authorship, narrative planning, literacy identity."},
        24: {"title":"The Problem and Solution","emoji":"🔑","skill":"Story Structure","materials":"None",
             "milestone":"Milestone: Problem-solution is the fundamental structure of most narratives. Children who internalise this structure understand virtually all the stories they encounter in books, films, and life.",
             "setup":["Choose a real problem from today or a made-up one","Set up as a storytelling task"],
             "play":["Present the problem: the bear cannot find his lunch","Ask: what could the bear try?","Try 3 different solutions -- which works?","Tell the story: problem, attempts, solution"],
             "say":['"The problem is: [X]. What should the character try first?"','"That did not work -- what next?"','"FINALLY: that worked! Tell me the whole story now."'],
             "if_happens":"Child jumps to the solution without the journey",
             "avoid":'"The character needs to try more things first."',
             "better":'"That was fast -- the quickest solution! Now make it harder. What if that did not work? What then?"',
             "why":"Problem-solution story structure maps onto the real-world problem-solving cycle: identify problem, generate solutions, test, fail, adjust, succeed. Children who understand this narrative structure also apply it to real problem-solving more effectively. Research in educational psychology shows that story-mediated problem-solving instruction is more effective than abstract instruction because the narrative scaffolds the problem-solving sequence.",
             "tool":"Problem Path",
             "phrases":['"Every problem has a path to its solution."','"The journey to the solution is the story."'],
             "skills":"Problem-solution structure, narrative logic, persistence."},
        25: {"title":"Puppet Show","emoji":"🎪","skill":"Performance Narrative","materials":"Socks or paper bags as puppets",
             "milestone":"Milestone: Putting on a puppet show for an audience develops narrative performance skills, voice projection, audience awareness, and the confidence of sharing creative work publicly.",
             "setup":["Make simple sock puppets","Set up a stage: table with a blanket draped"],
             "play":["Plan a short 2-3 scene show","Perform for each other or another family member","Puppets speak and move -- they are characters","Take a bow at the end"],
             "say":['"What story will our puppets tell?"','"Are you ready? Curtain up!"','"Take a bow -- the audience is clapping."'],
             "if_happens":"Child is too shy to perform and hides behind the stage",
             "avoid":'"Come out -- people want to see you."',
             "better":'"Your puppet can perform while you stay behind the stage. No one needs to see you -- just the puppet."',
             "why":"The puppet-as-proxy allows children to perform while maintaining psychological safety: the puppet speaks, not me. This graduated exposure to audience-facing performance builds confidence incrementally. Research on performance anxiety shows that children who begin with proxies (puppets, roles, costumes) develop stronger public speaking confidence than those pushed to perform directly before they are ready.",
             "tool":"The Puppet Speaks for You",
             "phrases":['"The puppet can say things you are not ready to say yet."','"You gave the puppet a voice."'],
             "skills":"Performance narrative, audience awareness, creative confidence."},
        26: {"title":"Record Our Story","emoji":"🎙️","skill":"Oral Story Recording","materials":"Phone or tablet for audio or video recording",
             "milestone":"Milestone: Recording and playing back a story creates an externalised narrative memory that children can revisit, share, and build identity from. The experience of hearing one's own voice tells the story is powerful.",
             "setup":["Set up a voice or video recording","Warm up: what story are we telling?"],
             "play":["Record a 2-3 minute story -- real or made up","Play it back immediately","Listen together -- notice voice, detail, expression","Keep it for the future"],
             "say":['"We are recording -- this is your story to keep."','"Listen to yourself -- that is YOUR storytelling voice."','"One day we will play this and remember right now."'],
             "if_happens":"Child is self-conscious hearing their own voice",
             "avoid":'"Do not be embarrassed -- it sounds fine."',
             "better":'"I get shy hearing my own voice too. Want to hear mine first? I will record me, then you."',
             "why":"Oral history traditions across cultures use story recording as a way of creating and preserving identity. When children hear their own voice telling a story, they experience themselves as the author of their own narrative -- a powerful identity experience. The playback also allows children to experience their own story from the outside, which builds both narrative revision skills and the metacognitive awareness of audience.",
             "tool":"Keeper of Stories",
             "phrases":['"Your story is worth keeping."','"One day you will listen to this and remember."'],
             "skills":"Oral storytelling, narrative identity, self-awareness."},
        27: {"title":"Share the Story","emoji":"📤","skill":"Social Storytelling","materials":"A story prepared to share",
             "milestone":"Milestone: Telling a story to someone outside the immediate relationship -- a grandparent, a friend -- develops audience awareness and the social dimension of narrative. Stories are fundamentally social acts.",
             "setup":["Choose a story made this month: a book, an original story, a recording","Choose an audience: call grandma, tell a neighbour"],
             "play":["Prepare: rehearse once","Tell the story to the audience","Receive the response: questions, reactions","Celebrate: you shared something you made"],
             "say":['"You are going to tell your story to Grandma -- she has never heard it."','"Tell her everything -- she is listening."','"Look at her face -- she loves your story."'],
             "if_happens":"Child refuses at the last minute",
             "avoid":'"You have to -- you said you would."',
             "better":'"That is OK -- can I tell it and you help me when I forget the important parts?"',
             "why":"Sharing a personally created story with a non-parental audience is one of the most significant social storytelling milestones. The child experiences their narrative as something of value to others -- not just tolerated by a loving parent but genuinely interesting to a third party. This validation of their narrative identity builds creative confidence and the motivation to continue creating and sharing stories.",
             "tool":"Your Story Has an Audience",
             "phrases":['"Your story is interesting to people who love you."','"You shared something that came from inside you."'],
             "skills":"Social storytelling, audience awareness, creative sharing."},
        28: "reflection",
        29: {"title":"Story Festival Prep","emoji":"✨","skill":"Celebration Planning","materials":"All stories and books made this month",
             "milestone":"Milestone: Preparing to celebrate and share one's creative work builds the habit of reflection and presentation that is foundational for all future creative endeavours.",
             "setup":["Gather all stories, books, and recordings from the month","Plan a mini presentation together"],
             "play":["Choose a favourite story to tell or perform","Practise once","Decide who the audience will be","Plan: what order? Any costumes?"],
             "say":['"Tomorrow we celebrate everything you made and told this month."','"Which story do you most want to share?"','"Let us practise one more time -- it will be perfect."'],
             "if_happens":"Child says nothing is good enough to share",
             "avoid":'"Everything is good enough."',
             "better":'"Which is your LEAST bad one? Start there. We only need one."',
             "why":"Pre-performance preparation -- choosing, rehearsing, and planning -- mirrors the full creative process that professional creators use. Children who experience this full cycle (creation, reflection, selection, rehearsal, presentation) develop a more sophisticated understanding of creative work than those who only create without reflecting. The decision of what to share requires self-evaluation and prioritisation.",
             "tool":"Ready to Share",
             "phrases":['"Choosing what to share is part of being a creator."','"You made it -- now you decide what the world sees."'],
             "skills":"Self-evaluation, performance preparation, creative reflection."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 6 Complete: Storyteller's Trophy!",
        "summary": "Six months in. Your child has spent half a year building, moving, feeling, making, and now creating stories. This month they became a storyteller. That is a skill that will never leave them.",
        "skills_built": ["Imaginative play and role adoption", "Story structure: first, then, finally", "Character empathy and perspective-taking", "Oral storytelling and narrative performance", "Authorship: creating original stories"],
        "month_next_teaser": "Next month: Friends and Sharing. Everything built in these 6 months comes together in learning to be a friend: turn-taking, empathy, sharing, and the social skills that make communities work.",
    },
    "reflection_activities": {
        7:  {"activity": "Favourite Character", "desc": "Who was your favourite character to be this week? Draw them. Give them a name if they do not have one."},
        14: {"activity": "Three-Part Story", "desc": "Tell a 3-part story about something that happened this week. First... then... finally."},
        21: {"activity": "Character Interview", "desc": "One of you becomes a character from a book. The other interviews them. Then swap."},
        28: {"activity": "Story of This Month", "desc": "Tell the story of Month 6. First (Day 1)... then (what happened in the middle)... finally (what you learned)."},
    },
}
