"""Month 7: Friends & Sharing -- curriculum data"""
M7 = {
    "name": "Friends & Sharing",
    "toolkit_label": "2--3 Years &middot; Month 7",
    "weeks": {
        1: {"title": "What Is a Friend?", "subtitle": "Learning the language of friendship"},
        2: {"title": "Taking Turns", "subtitle": "The heartbeat of all play together"},
        3: {"title": "When It Is Hard to Share", "subtitle": "Honest practice for real moments"},
        4: {"title": "Playing Together", "subtitle": "The joy of shared imagination"},
    },
    "days": {
        1:  {"title":"Friend Is a Person Who...","emoji":"👫","skill":"Social Concepts","materials":"None",
             "milestone":"Milestone: Understanding what a friend is -- someone who plays with you, is kind, makes you feel safe -- builds the social schemas that guide friendship-seeking behaviour throughout childhood.",
             "setup":["Sit together comfortably"],
             "play":["Ask: what is a friend?","Build a list together: a friend plays with you, is kind, makes you smile","Think of one friend -- real or imaginary","What makes THAT person a friend?"],
             "say":['"What is a friend? What does a friend do?"','"Is [name] a friend? How do you know?"','"What do you do for a friend that you do not do for everyone?"'],
             "if_happens":"Child says everyone is their friend",
             "avoid":'"No -- a friend is someone special, not everyone."',
             "better":'"Wow -- you have a lot of love to give everyone. Who feels extra special? Like your heart knows them?"',
             "why":"Children who develop an explicit, articulated concept of friendship -- as distinct from acquaintance -- navigate social situations more successfully than those for whom friendship is undefined. The concept of friendship includes reciprocity (they choose you AND you choose them), warmth (positive feeling), and reliability (they are the same tomorrow as today). Articulating these qualities before age 4 supports school transition.",
             "tool":"Friendship Words",
             "phrases":['"A friend makes your heart feel warm."','"Friends choose each other."'],
             "skills":"Social concept formation, friendship vocabulary, relationship thinking."},
        2:  {"title":"Greet a Friend","emoji":"👋","skill":"Social Initiation","materials":"None",
             "milestone":"Milestone: Knowing how to initiate social contact -- making eye contact, greeting, offering to play -- is a specific skill that many children need to be explicitly taught.",
             "setup":["Role play: parent is a friend at the park","Child approaches"],
             "play":["Demonstrate: walk up, make eye contact, say hi, ask to play","Practise together 3 times","Try different scenarios: playground, classroom, neighbour","Discuss: what if they say no?"],
             "say":['"Walk up and say: Hi, I am [name]. Do you want to play?"','"Look at them when you say it -- eyes help people know you mean it."','"What do you do if they say no? We practise that too."'],
             "if_happens":"Child is too shy to approach and hides behind parent",
             "avoid":'"Just go -- say hi."',
             "better":'"I know it feels scary. You can stand next to them first and not say anything. Sometimes being near someone is the start."',
             "why":"Social initiation -- the ability to approach and engage a potential playmate -- is a specific skill that is different from general sociability. Research shows that children who receive explicit instruction and practice in social initiation scripts show significantly higher peer acceptance and fewer social rejections at school entry. The standing-near approach is a validated graduated exposure strategy.",
             "tool":"Brave Start",
             "phrases":['"Saying hi is the bravest first step."','"Being near someone is already a beginning."'],
             "skills":"Social initiation, eye contact, greeting scripts."},
        3:  {"title":"Play Together","emoji":"🤝","skill":"Cooperative Play","materials":"Any toy",
             "milestone":"Milestone: Cooperative play -- where two children build or create something together toward a shared goal -- emerges between 2.5 and 4 years and is a significant developmental milestone beyond parallel play.",
             "setup":["A shared toy or activity: blocks, drawing, play dough","Both working on the same thing"],
             "play":["Build one thing together -- not two separate things","Negotiate: you add this, I add that","When you disagree: talk it out (practise words)","Celebrate the finished thing: WE made this"],
             "say":['"We are both working on the SAME thing."','"What should we add next? You decide -- then I decide."','"WE made that. Together."'],
             "if_happens":"Child takes over and does not let parent contribute",
             "avoid":'"Let me do some -- you are doing it all."',
             "better":'"You are the chief builder! I am your helper. Tell me what to build next."',
             "why":"Cooperative play requires joint attention, shared goal representation, and negotiation -- three of the most sophisticated social cognitive skills that develop in early childhood. Moving from parallel play (playing side by side) to cooperative play (playing together toward a shared goal) is one of the most significant social milestones of ages 2-4 and a strong predictor of school-age peer competence.",
             "tool":"Together We Build",
             "phrases":['"We both put something into this."','"Together is more powerful than alone."'],
             "skills":"Cooperative play, joint attention, shared goal, negotiation."},
        4:  {"title":"Kind Words to a Friend","emoji":"💬","skill":"Prosocial Language","materials":"None",
             "milestone":"Milestone: Learning a repertoire of kind phrases -- I like playing with you, you are good at that, are you OK? -- gives children social tools that increase peer acceptance.",
             "setup":["Role play: parent is a friend doing something","Child practises kind responses"],
             "play":["Friend finishes a drawing: you say something kind","Friend looks sad: you ask are you OK?","Friend shares a toy: you say thank you -- but more than that","Build a list of kind things to say"],
             "say":['"What kind thing could you say right now?"','"Try: that was really good. Or: I like playing with you."','"Kind words make friends want to stay."'],
             "if_happens":"Child says mean or teasing things during role play",
             "avoid":'"That is mean -- do not say that."',
             "better":'"What do you think [friend] would feel if you said that? Let us try a different version."',
             "why":"Prosocial language -- specific verbal behaviours that acknowledge, encourage, and support peers -- is one of the strongest predictors of peer acceptance in pre-school. Children who have a repertoire of kind phrases use them in natural social settings, which triggers positive responses from peers, which reinforces the prosocial behaviour. The entire prosocial vocabulary needs to be explicitly taught at this age.",
             "tool":"Kind Word Bank",
             "phrases":['"You have kind words in your word bank."','"Choose one kind word for a friend today."'],
             "skills":"Prosocial language, peer acceptance, verbal kindness."},
        5:  {"title":"Be a Good Listener","emoji":"👂","skill":"Active Listening","materials":"None",
             "milestone":"Milestone: Active listening -- looking at the speaker, waiting to speak, responding to what was said -- is a specific social skill that many children need explicit practice in. It is foundational for friendship quality.",
             "setup":["Face each other","Establish the listening rules"],
             "play":["Parent tells a 2-sentence story about today","Child must: look at parent, wait, then respond to what was said","Swap: child tells, parent models listening","Practise the hardest part: waiting to speak"],
             "say":['"When someone talks to you, look at them -- it says I hear you."','"Wait until they stop before you start."','"Did you hear what I said? Tell me back."'],
             "if_happens":"Child interrupts constantly",
             "avoid":'"Stop interrupting -- let me finish."',
             "better":'"I love that you have so much to say! Hold your thought -- I am almost done. Then you go."',
             "why":"Active listening is not a passive act -- it requires sustained attention, suppression of the impulse to speak, and enough comprehension to respond relevantly. These are executive function skills. Research shows that children taught active listening skills in pre-school show stronger academic performance because the same skills (attend, hold attention, respond relevantly) underpin classroom learning.",
             "tool":"Whole Body Listening",
             "phrases":['"Eyes on the speaker -- that is whole body listening."','"Waiting to speak is hard and important."'],
             "skills":"Active listening, sustained attention, impulse suppression, social responsiveness."},
        6:  {"title":"Friend or Not a Friend?","emoji":"🤔","skill":"Social Discernment","materials":"None",
             "milestone":"Milestone: Learning to distinguish between friendly and unfriendly behaviour -- without labelling children as good or bad -- builds the social discernment that protects children from harmful relationships.",
             "setup":["Scenario cards (describe with words)","Role play each one"],
             "play":["Scenario: someone pushes you. Friend behaviour?","Scenario: someone shares a snack. Friend behaviour?","Scenario: someone says your drawing is bad. Friend behaviour?","Key: the BEHAVIOUR is not friendly, not necessarily the person"],
             "say":['"Was that friendly behaviour or not friendly behaviour?"','"Can someone do an unfriendly thing AND still be your friend?"','"What could you say or do?"'],
             "if_happens":"Child says someone who pushed them is still their best friend",
             "avoid":'"They are not a good friend if they push you."',
             "better":'"Yes, they can still be your friend. And the pushing was not friendly. Both things can be true."',
             "why":"Social discernment -- the ability to evaluate specific behaviours as friendly or unfriendly without globally judging the person -- is a protective factor for social wellbeing. Children who learn to distinguish behaviour from person (the push was wrong, but they are not a bad person) develop healthier conflict resolution patterns and are less likely to either stay in harmful relationships or cut people off at the first sign of conflict.",
             "tool":"Friendly Behaviour Detector",
             "phrases":['"That behaviour was not friendly."','"The behaviour and the person are separate."'],
             "skills":"Social discernment, behaviour evaluation, conflict literacy."},
        7:  "reflection",
        8:  {"title":"Whose Turn Is It?","emoji":"⏱️","skill":"Turn-Taking Concept","materials":"Any shared toy or game",
             "milestone":"Milestone: Understanding turn-taking -- that waiting is temporary and fair -- is one of the first social contracts children need to internalise. It is the foundation of all group play and classroom participation.",
             "setup":["One toy between two people","Establish the turn-taking structure"],
             "play":["Clearly establish: MY turn / YOUR turn","Use a visual timer if helpful (sand timer or counting)","Praise the waiting: that is SO hard and you did it","Celebrate both turns equally"],
             "say":['"It is YOUR turn now. Then it is mine."','"While you wait, count to 10 with me."','"You waited! That was the hardest part."'],
             "if_happens":"Child grabs before their turn",
             "avoid":'"You grabbed -- give it back."',
             "better":'"The grab happened -- the toy goes back. Now: your turn is coming. 5 more seconds. Count with me: 5, 4, 3, 2, 1 -- your turn!"',
             "why":"Turn-taking requires the child to simultaneously hold a mental queue (my turn is coming), inhibit the impulse to grab (executive function), and trust the social contract (parent will actually give the turn when promised). Research shows that children develop turn-taking more reliably when turns are predictable, short, and preceded by countdown cues rather than arbitrary verbal reminders.",
             "tool":"My Turn is Coming",
             "phrases":['"Your turn is coming -- it is not gone, just waiting."','"Waiting is a skill. You are getting better at it."'],
             "skills":"Turn-taking, impulse control, trust in social contracts."},
        9:  {"title":"The Waiting Game","emoji":"⏳","skill":"Delay of Gratification","materials":"Sand timer or count-to-10",
             "milestone":"Milestone: The ability to delay gratification -- to wait for something wanted -- is one of the strongest predictors of life outcomes including academic success, social competence, and emotional health.",
             "setup":["A desired object or activity","Establish a waiting period: 30 seconds, then a minute"],
             "play":["I want [thing] -- but I have to wait 30 seconds","Count together, use a timer","When the time is up: you can have it","Celebrate the waiting: you waited! That is incredible at your age."],
             "say":['"You want it -- and you have to wait 30 seconds. Ready?"','"Count with me: 1, 2, 3... you are doing it!"','"YOU WAITED. That is one of the hardest things any human does."'],
             "if_happens":"Child melts down before the time is up",
             "avoid":'"You have to wait -- I said wait."',
             "better":'"Too long this time. Let us try 5 seconds. FIVE. You can do 5."',
             "why":"Delay of gratification activates the anterior cingulate cortex -- the brain region responsible for conflict monitoring (I want it now vs I should wait). The famous marshmallow studies and subsequent research confirm that early delay of gratification ability predicts outcomes across a remarkably wide range of domains. The key developmental tool is not willpower but strategy: redirecting attention, counting, self-talk.",
             "tool":"The Wait Strategy",
             "phrases":['"Look away from it -- count to 10 instead."','"The waiting makes the getting sweeter."'],
             "skills":"Delay of gratification, impulse control, self-talk strategy."},
        10: {"title":"You Go First","emoji":"🥇","skill":"Generosity","materials":"A desirable first turn",
             "milestone":"Milestone: Voluntarily offering someone else the first turn -- against your own immediate interest -- is a genuine act of generosity that requires perspective-taking, emotional regulation, and altruistic motivation.",
             "setup":["Set up a situation where first turn is clearly desirable","Let child naturally want to go first"],
             "play":["Point out that someone else could go first","Ask: how would THEY feel if you let them go first?","Offer the first turn -- see what happens","After: how did that feel? Different from going first?"],
             "say":['"Would you like to let [person] go first this time?"','"How do you think they would feel if you did that?"','"How do YOU feel now that you let them go first?"'],
             "if_happens":"Child refuses and insists on going first",
             "avoid":'"You should let them go first -- be generous."',
             "better":'"OK -- you go first. After your turn, let us talk about what it would feel like to give someone else the first turn."',
             "why":"Generosity -- giving something of value that costs you something -- is distinct from sharing (which may be required) and from giving when you have enough anyway. Voluntary first-turn offering is particularly valuable because the child genuinely wants the first turn, which means giving it away is a meaningful sacrifice. Research shows that children who experience the positive internal feeling of generous acts are more likely to repeat them.",
             "tool":"First for You",
             "phrases":['"When you give someone else first, something warm happens inside you."','"Generosity is not losing -- it is choosing."'],
             "skills":"Generosity, altruism, perspective-taking, delayed self-interest."},
        11: {"title":"Taking Turns with Feelings","emoji":"💛","skill":"Emotional Turn-Taking","materials":"None",
             "milestone":"Milestone: Emotional turn-taking -- each person expresses their feeling and the other listens -- is the structure of all healthy emotional communication. Teaching it early builds lifelong relationship skills.",
             "setup":["Sit together -- establish the structure","One speaks, one listens -- then swap"],
             "play":["Parent shares one feeling from today","Child listens -- no interruption","Child shares one feeling","Parent listens completely","Reflect back what you heard"],
             "say":['"My turn: I felt frustrated today when... I am finished."','"Your turn: how did YOU feel today?"','"What I heard you say is... Did I get it right?"'],
             "if_happens":"Child uses the turn to play or changes subject",
             "avoid":'"Focus -- this is the feelings game."',
             "better":'"What you said about [topic] sounds like there is a feeling in it. What is the feeling part of that?"',
             "why":"Emotional turn-taking establishes the most fundamental structure of healthy relationships: I speak, you hear; you speak, I hear. Many adult relationship problems stem from the absence of this basic structure during communication. Teaching children the explicit turn-taking structure for emotional sharing before age 3 builds the habit that will sustain their intimate relationships decades later.",
             "tool":"Your Feeling, My Feeling",
             "phrases":['"I hear what you feel."','"Now your turn -- I am listening."'],
             "skills":"Emotional turn-taking, active listening, relational communication."},
        12: {"title":"The Turn-Taking Tower","emoji":"🏗️","skill":"Turn-Taking Practice","materials":"Blocks",
             "milestone":"Milestone: Strict alternating turns with a concrete activity makes the abstract concept of turn-taking tangible and practisable. Each block added is one complete turn cycle.",
             "setup":["A pile of blocks","Two people, one tower"],
             "play":["Strictly alternate: I add one block, you add one block","Go slow enough to make the waiting real","Count how many turns it takes before it falls","Rebuild -- more turns"],
             "say":['"My turn -- one block."','"Your turn -- one block."','"We are BOTH building this tower."'],
             "if_happens":"Child adds multiple blocks on their turn",
             "avoid":'"Only one block -- you broke the rules."',
             "better":'"Oh! Two blocks at once. Now I get two too -- that makes it fair. Or we go back to one each?"',
             "why":"The tower game makes turn-taking concrete, visual, and fair. Each turn is exactly equal in scope (one block), which removes the ambiguity that makes turn-taking disputes so common. The shared product (the tower) gives both participants investment in the cooperative structure. Watching the tower grow is a visual reinforcement that taking turns produces something neither could have built alone.",
             "tool":"Equal Turns",
             "phrases":['"One block each -- completely fair."','"We built something neither of us could build alone."'],
             "skills":"Turn-taking, fair play, cooperative construction."},
        13: {"title":"Sorry and Making It Right","emoji":"🙏","skill":"Repair Behaviour","materials":"None",
             "milestone":"Milestone: Learning that sorry is the start, not the end -- and that making it right is possible -- builds the repair skills that sustain relationships through inevitable conflict.",
             "setup":["Role play a small mistake scenario","Keep it light -- not real conflict"],
             "play":["I accidentally knocked over your tower","I say: I am sorry -- I did not mean to","Together: how can I make it right?","We rebuild together -- that is the repair"],
             "say":['"I am sorry -- I knocked your tower."','"How can I make it right?"','"The sorry opens the door. The repair walks through it."'],
             "if_happens":"Child says sorry but immediately does the same thing again",
             "avoid":'"You keep doing it -- your sorry does not mean anything."',
             "better":'"I hear your sorry. I think the hard part is knowing how to make it right. Let us figure that out together."',
             "why":"Repair behaviour -- the actions taken after causing harm to restore the relationship -- is more important for long-term relationship quality than the apology itself. Research on relationship repair shows that children who learn to make-it-right after conflict have significantly stronger peer relationships than those who only apologise verbally. The question how can I make it right? is more relationship-building than the statement I am sorry.",
             "tool":"Make It Right",
             "phrases":['"Sorry opens the door. Repair walks through it."','"How can we make it right -- together?"'],
             "skills":"Repair behaviour, relational accountability, conflict resolution."},
        14: "reflection",
        15: {"title":"I Want That Toy","emoji":"🧸","skill":"Sharing Language","materials":"One desirable toy",
             "milestone":"Milestone: Having explicit language for the moment of wanting what someone else has -- and both asserting need AND hearing the other -- is the specific skill gap most often behind sharing conflicts.",
             "setup":["One toy -- both people want it","Role play the negotiation"],
             "play":["Practice the words: I want that when you are done","Practice the answer: I will finish soon -- 2 more minutes","Practise both sides equally","Try: trading instead of waiting"],
             "say":['"Try saying: can I have a turn when you are done?"','"Try saying: I will be done soon -- 2 minutes."','"What else could work? Trade? Timer?"'],
             "if_happens":"Child grabs every time regardless of practice",
             "avoid":'"You know the words -- use them."',
             "better":'"The grab happened again -- the body moved faster than the words. Let us practise the words when the want feeling is not there. Then the next time, the words will be closer."',
             "why":"Sharing conflicts are most often not about selfishness but about the absence of the specific language needed to negotiate. Research shows that children who have the verbal scripts for sharing situations (requesting, granting, trading, waiting) navigate toy conflicts dramatically more successfully than those without them. The script I will be done soon is one of the most valuable social phrases a toddler can learn.",
             "tool":"Sharing Words",
             "phrases":['"I will have a turn when you are done."','"Can I trade you this for that?"'],
             "skills":"Sharing language, negotiation scripts, conflict vocabulary."},
        16: {"title":"Your Turn with My Favourite","emoji":"💎","skill":"Generous Sharing","materials":"Child's most prized toy",
             "milestone":"Milestone: Sharing something precious -- not just any toy but the favourite one -- is a genuinely difficult emotional challenge. Practising with a trusted adult before facing it with peers reduces the distress of the real moment.",
             "setup":["Child's favourite toy","Explicitly acknowledge: this is your MOST special one"],
             "play":["Parent asks to borrow the favourite toy","Child lends it for a short, defined time (30 seconds)","Parent cares for it carefully -- demonstrates trustworthiness","Returns it on time: it comes back"],
             "say":['"This is your most special toy. Can I hold it for 30 seconds?"','"I will be very careful -- I know it is precious."','"Here it is back -- safe and sound, right on time."'],
             "if_happens":"Child cannot do it and clutches the toy",
             "avoid":'"You have to practise sharing even the favourite."',
             "better":'"That toy is too precious right now. OK. Let us practise with the SECOND most special one. That still counts."',
             "why":"Starting sharing practice with high-value objects is counterproductive. The research principle is to build the sharing schema with low-stakes objects first and gradually increase value as the child builds trust in the return. The parent demonstrating careful handling and on-time return is critical -- it builds the trust infrastructure that makes all sharing emotionally sustainable.",
             "tool":"Trust Return",
             "phrases":['"I returned it -- you can trust me."','"Things you share with trustworthy people come back."'],
             "skills":"Generous sharing, trust-building, emotional risk tolerance."},
        17: {"title":"Too Much Together","emoji":"😤","skill":"Conflict Language","materials":"None",
             "milestone":"Milestone: Having language for the moment when play becomes overwhelming -- I need a break, that is too much -- prevents escalation to hitting or shutting down. It is one of the most practical social-emotional tools.",
             "setup":["Role play a too-intense play scenario","Where is the point of too much?"],
             "play":["Play together -- escalate gently","Reach a too-much moment -- model the words: I need a pause","Pause, breathe, return","Practise the exit and return together"],
             "say":['"I need a pause -- too much right now."','"I am going to sit quietly for one minute. I will be back."','"I am back. Let us play again -- calmer this time."'],
             "if_happens":"Child shuts down or hits when overwhelmed",
             "avoid":'"You hit again -- use your words."',
             "better":'"Your body said too much before your words could. Next time: I will watch for the signs. And you practise: I need a pause."',
             "why":"Many social conflicts at this age are the result of sensory or emotional overwhelm that escalates to aggression or shutdown because the child does not have exit language. Teaching the I need a pause phrase with a clear, socially acceptable withdrawal and return sequence provides an emotional release valve. Research shows that children taught explicit exit and return scripts show dramatically lower rates of conflict escalation.",
             "tool":"Pause and Return",
             "phrases":['"I need a pause -- I will be back."','"Taking a break is not quitting."'],
             "skills":"Conflict de-escalation, exit language, self-regulation in social context."},
        18: {"title":"When Someone Plays Differently","emoji":"🔄","skill":"Flexibility","materials":"Any activity",
             "milestone":"Milestone: Accepting that another person plays differently -- not wrongly, just differently -- is the foundation of social flexibility and the ability to sustain diverse friendships.",
             "setup":["Parent plays with a toy or game differently than child expects","Watch child's reaction"],
             "play":["Play in an unexpected way","If child corrects: there is more than one right way","Try playing THEIR way","Try playing YOUR way","Both ways are the game"],
             "say":['"I am going to play it my way -- it might look different."','"Your way is one right way. My way is another."','"What happens if we put BOTH ways in the same game?"'],
             "if_happens":"Child insists there is only one right way",
             "avoid":'"There is no right way -- stop saying that."',
             "better":'"You have learned one right way really well. A second right way exists too. Want to see it? You do not have to use it."',
             "why":"Rigidity in play (insisting on one way) can be developmentally normal at 2-3 years because children are consolidating schemas and prefer confirmation to novelty. However, social play requires flexibility. The best approach is to validate their way completely while gently introducing the existence of alternatives -- not forcing adoption but building the concept that multiplicity is possible.",
             "tool":"More Than One Way",
             "phrases":['"Your way is real. Other ways are also real."','"Both ways can exist in the same game."'],
             "skills":"Flexibility, multiplicity tolerance, social adaptability."},
        19: {"title":"I Did Not Like That","emoji":"🙅","skill":"Assertiveness","materials":"None",
             "milestone":"Milestone: Saying I did not like that -- asserting one's preferences and boundaries verbally -- is a foundational social skill that protects children from both being victimised and from swallowing resentment silently.",
             "setup":["Role play: parent does something child would not like"],
             "play":["Parent: takes your toy without asking","Child practises: I do not like that -- please ask first","Parent responds positively to the assertion","Celebrate the assertion: you said what you needed"],
             "say":['"You can say: I do not like that. I want you to try it."','"When I took the toy without asking: what did you want to say?"','"You said it! And now I know. That is how it works."'],
             "if_happens":"Child goes silent instead of asserting",
             "avoid":'"Say something -- you have to use your words."',
             "better":'"Silence is one way to say it -- and sometimes words work better. Let us practise until the words feel available."',
             "why":"Assertiveness -- verbally stating one's preferences and boundaries -- is distinct from aggression (acting on the preference forcibly) and passivity (saying nothing). Children who develop assertiveness are less likely to be socially victimised because potential aggressors encounter verbal resistance, and less likely to become resentful or aggressive themselves because they have a functional channel for expressing displeasure.",
             "tool":"I Did Not Like That",
             "phrases":['"I did not like that. Please ask next time."','"Your words protect your boundaries."'],
             "skills":"Assertiveness, boundary language, self-advocacy."},
        20: {"title":"Solving It Together","emoji":"🔧","skill":"Collaborative Problem-Solving","materials":"A small disagreement or puzzle",
             "milestone":"Milestone: Collaborative problem-solving -- working together on a shared obstacle -- builds both friendship and the practical skills for all future team situations.",
             "setup":["Create a small problem neither can solve alone","Or use a real disagreement as the material"],
             "play":["Name the problem clearly: we both want [X]","Brainstorm solutions together: what could work?","Test one solution","If it did not work: try another"],
             "say":['"We have a problem: what should we do?"','"Your idea AND my idea -- which one should we try first?"','"That did not work -- what else?"'],
             "if_happens":"Child wants to solve it alone",
             "avoid":'"You have to let me help."',
             "better":'"OK, you solve it first. If it does not work, I am here as backup. And if it DOES work, that means you knew how."',
             "why":"Collaborative problem-solving -- a two-person process of generating options, testing them, and adapting -- is the cognitive and social foundation of all future teamwork. The research of Paul Ginsburg shows that children who engage in collaborative problem-solving with caregivers develop stronger metacognitive skills (awareness of their own problem-solving process) than those who solve problems alone or are given solutions.",
             "tool":"Two Minds, One Problem",
             "phrases":['"Two heads are better than one."','"Your idea made my idea better."'],
             "skills":"Collaborative problem-solving, negotiation, creative solution generation."},
        21: "reflection",
        22: {"title":"Side-by-Side Play","emoji":"👣","skill":"Parallel and Cooperative Play", "materials":"Same materials for both",
             "milestone":"Milestone: Playing side-by-side with awareness of what the other person is doing -- parallel play with attention -- is a bridge between solitary play and full cooperative play.",
             "setup":["Same activity for both: both drawing, both building","Sit close together"],
             "play":["Each working on their own thing","Comment on each other's work with interest","Borrow an idea from each other","Eventually merge: make one thing together"],
             "say":['"What are you making? I will make mine inspired by yours."','"I borrowed your idea -- I hope that is OK."','"Should we combine ours into one big one?"'],
             "if_happens":"Child copies exactly and says they made the same thing",
             "avoid":'"Make something different -- yours, not mine."',
             "better":'"We made the same thing! Now let us make them talk to each other -- they can be best friends."',
             "why":"The progression from parallel play (awareness of the other) to cooperative play is gradual and not linear. Merging two parallel works into a shared project is a natural bridge that the child initiates rather than is directed to. This child-led merger is developmentally important: it means the child has chosen cooperative play, which produces stronger social learning than cooperation that is imposed.",
             "tool":"Inspired By You",
             "phrases":['"I got the idea from watching you."','"Our things can know each other."'],
             "skills":"Parallel-to-cooperative play, idea borrowing, collaborative merging."},
        23: {"title":"Our Secret Signal","emoji":"🤫","skill":"Friendship Intimacy","materials":"None",
             "milestone":"Milestone: Creating a private shared signal -- a handshake, a word, a gesture -- creates the experience of exclusive friendship intimacy that is deeply bonding for young children.",
             "setup":["Explain: we are going to make something only we know"],
             "play":["Create a secret handshake (pat, snap, bump)","Or a secret word for when you are happy to see each other","Practise it together","Try using it in a normal day moment"],
             "say":['"We are making something only we share -- nobody else knows it."','"Let us practise -- is this the right one?"','"When you use it, I will know: we are friends."'],
             "if_happens":"Child wants to tell everyone the secret",
             "avoid":'"No -- it has to be a secret."',
             "better":'"A secret that stays secret is powerful. But if you want to teach it to [sibling], we can have TWO special signals."',
             "why":"Private shared rituals -- secret handshakes, special words, shared jokes -- are among the most powerful friendship bonding mechanisms at all ages. For toddlers, the experience of having something that belongs only to their friendship creates the experience of exclusivity and intimacy that is qualitatively different from general positive social interaction. This experience teaches children what deep friendship feels like.",
             "tool":"Our Thing",
             "phrases":['"This is our thing -- just ours."','"When we do it, we are saying: we are friends."'],
             "skills":"Friendship intimacy, shared ritual, bonding."},
        24: {"title":"When a Friend Is Upset","emoji":"🫂","skill":"Empathic Support","materials":"None",
             "milestone":"Milestone: Knowing what to do when a friend is upset -- and having the courage to approach rather than avoid -- is one of the most practically valuable social skills a child can develop.",
             "setup":["Role play: parent pretends to be sad or frustrated"],
             "play":["Parent shows clear distress","Child: what could you do? (Brainstorm without directing)","Try: sit near, ask are you OK, offer a hug, offer to help","Role swap: child is upset, parent models support"],
             "say":['"Your friend looks upset. What could you do?"','"Sometimes just being there is enough."','"Ask: are you OK? And then just listen."'],
             "if_happens":"Child ignores or runs away from the upset friend",
             "avoid":'"You should go and help them."',
             "better":'"It is hard to know what to do when someone is sad. Even I do not always know. What would YOU want someone to do if YOU were sad?"',
             "why":"Approach behaviour in response to a distressed peer -- rather than avoidance -- is a specific prosocial skill that predicts friendship quality throughout childhood. Many children avoid distressed peers not from indifference but from social uncertainty (I do not know what to do). Providing specific action options and role-playing them builds the competence that makes approach possible.",
             "tool":"Show Up",
             "phrases":['"Just being there is already helping."','"You do not have to fix it -- just be with them."'],
             "skills":"Empathic support, prosocial approach, comfort giving."},
        25: {"title":"Different Friends, Same Love","emoji":"🌍","skill":"Inclusive Friendship","materials":"Diverse pictures or dolls",
             "milestone":"Milestone: Learning that friends can look different, speak differently, and play differently -- and still be your friend -- builds inclusive social attitudes at the age when they are most naturally formed.",
             "setup":["Look at pictures of children of different backgrounds","Or use diverse toys"],
             "play":["Notice differences: different skin, different clothes, different languages","Ask: could this person be your friend?","What would you play together?","What could YOU learn from this friend?"],
             "say":['"This child looks different from you. Could they be your friend?"','"What would you want to know about them?"','"Different on the outside -- same feelings inside."'],
             "if_happens":"Child says they only want friends who look like them",
             "avoid":'"That is wrong -- you should like everyone."',
             "better":'"It is normal to feel most comfortable with what we know. A different friend is an adventure -- you get to learn something brand new."',
             "why":"Social attitudes toward outgroup members are most malleable before age 5. Research consistently shows that cross-group friendship exposure at this age produces the strongest and most durable positive intergroup attitudes. The framing of different friends as adventure (something to gain) rather than challenge (something to overcome) activates approach motivation rather than threat response.",
             "tool":"All Kinds of Friends",
             "phrases":['"A different friend teaches you something new about the world."','"All feelings are the same underneath."'],
             "skills":"Inclusive friendship, diversity attitudes, social openness."},
        26: {"title":"Making Up After a Fight","emoji":"🌈","skill":"Conflict Resolution","materials":"None",
             "milestone":"Milestone: Understanding that conflict and friendship can coexist -- that a fight does not end a friendship -- is one of the most important concepts for long-term relational wellbeing.",
             "setup":["Role play a minor conflict and repair"],
             "play":["Two characters: fight over a toy","Pause: how do they both feel?","Brainstorm: how could they make up?","Act out the repair -- both characters feel better"],
             "say":['"They had a fight. That happens between friends."','"How are they both feeling right now?"','"What could they do to be OK again?"'],
             "if_happens":"Child says they would never fight with their friend",
             "avoid":'"Everyone fights sometimes."',
             "better":'"Wow -- you have such a strong friendship in your heart! And even the best friends bump into each other sometimes. That is just part of knowing someone really well."',
             "why":"Children who understand the repair-after-conflict cycle maintain friendships through inevitable difficulties rather than abandoning them. Research shows that children with low conflict resolution skills are more likely to either avoid conflict (leading to social withdrawal) or stay in conflict (leading to chronic social stress). Understanding that conflict is repairable transforms it from a friendship-ending event to a relationship-strengthening one.",
             "tool":"Friends Fight and Repair",
             "phrases":['"A fight does not end a friendship."','"Making up is how friendships get stronger."'],
             "skills":"Conflict resolution, relational repair, friendship resilience."},
        27: {"title":"My Best Memory with a Friend","emoji":"⭐","skill":"Friendship Appreciation","materials":"Paper, crayons (optional)",
             "milestone":"Milestone: Actively recalling and appreciating positive friendship memories builds the neural representation of friendship as a positive, valued experience -- which motivates continued social engagement.",
             "setup":["Think about a real friend or family member"],
             "play":["Ask: what is your favourite memory with [friend]?","Draw it or tell the story","What made that time special?","Could you recreate it or create a new memory?"],
             "say":['"Tell me your best memory with [friend]."','"What made it special? What did you love about it?"','"Could you make another memory like that?"'],
             "if_happens":"Child cannot name a specific memory",
             "avoid":'"Think harder -- you must remember something."',
             "better":'"Let me start -- my best memory of a friend is when... Now you: even a small one. Even from yesterday."',
             "why":"Reminiscing about positive experiences with friends strengthens the episodic memory encoding for those experiences AND builds the future-motivation to create more such experiences. Research on relationship quality shows that people who actively recall and appreciate positive shared memories report significantly higher relationship satisfaction and longer-lasting friendships.",
             "tool":"Friendship Memory Jar",
             "phrases":['"Good memories are worth keeping on purpose."','"Remembering together makes the memory bigger."'],
             "skills":"Friendship appreciation, episodic memory, relational motivation."},
        28: "reflection",
        29: {"title":"Letter to a Friend","emoji":"✉️","skill":"Social Expression","materials":"Paper, crayons",
             "milestone":"Milestone: Communicating feelings and appreciation to a friend in a tangible form -- a letter, a drawing, a gift -- teaches children that relationships are actively maintained through acts of care.",
             "setup":["Think of a friend or family member","Paper and crayons"],
             "play":["Dictate or draw a letter to the friend","Tell them: what you love about them, a memory, a wish","Draw their face or a picture of you both","Prepare to deliver it"],
             "say":['"What do you want to say to [friend]?"','"What do you love about them? I will write it."','"Imagine their face when they get this."'],
             "if_happens":"Child runs out of things to say quickly",
             "avoid":'"Think of more -- you must have more to say."',
             "better":'"One thing is enough for a letter. The best letters are short and true."',
             "why":"Communicating appreciation and affection to others -- expressing positive regard in a tangible form -- is a relationship maintenance behaviour that both strengthens the relationship and increases the well-being of the person giving. Research on gratitude and positive relationship communication consistently shows that expressing appreciation (even to people who will never read the letter) increases positive emotion and social connection.",
             "tool":"Put the Love in Words",
             "phrases":['"Your words can travel to people who are not here."','"Telling someone you love them is a gift."'],
             "skills":"Social expression, relationship maintenance, gratitude."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 7 Complete: Friendship Star!",
        "summary": "This month your child learned what a friend is, how to greet, take turns, share, handle conflict, and show empathy. These are the social skills that will define the quality of every relationship they ever have.",
        "skills_built": ["Friendship concept and vocabulary", "Turn-taking and sharing scripts", "Conflict language: exit, repair, and assertiveness", "Empathic support: showing up when someone is sad", "Inclusive friendship: openness to different people"],
        "month_next_teaser": "Next month: Numbers and Patterns. Your child will count everything, sort by colour and shape, find patterns in the world, and begin the mathematical thinking that underpins all future learning.",
    },
    "reflection_activities": {
        7:  {"activity": "Friend Portrait", "desc": "Draw a picture of your best friend (real or imaginary). What do you love about them?"},
        14: {"activity": "Turn-Taking Count", "desc": "Play the tower game again. How many turns can you take before it falls? Is it more than Day 8?"},
        21: {"activity": "Sharing Story", "desc": "Tell the story of a time this week when sharing was hard. What happened? What did you do?"},
        28: {"activity": "Friendship Letter Prep", "desc": "Who deserves a thank-you this week? Start thinking about your Day 29 letter."},
    },
}
