"""Month 8: Numbers & Patterns -- curriculum data"""
M8 = {
    "name": "Numbers & Patterns",
    "toolkit_label": "2--3 Years &middot; Month 8",
    "weeks": {
        1: {"title": "Counting Everything", "subtitle": "The world is full of numbers waiting to be named"},
        2: {"title": "Sorting & Matching", "subtitle": "Same and different -- the first logic"},
        3: {"title": "Patterns in the World", "subtitle": "Seeing the repeat that runs through everything"},
        4: {"title": "More and Less", "subtitle": "Quantity comparison -- the heart of early mathematics"},
    },
    "days": {
        1:  {"title":"Count Your Fingers","emoji":"🖐️","skill":"Rote Counting","materials":"Hands",
             "milestone":"Milestone: Rote counting to 5 and then 10 is typically achieved between 2 and 3 years. The sequence of number words must be memorised before number-quantity relationships can be understood.",
             "setup":["Sit facing each other","Hold up your hands"],
             "play":["Count 1-5 on your fingers together","Count 1-10","Try counting backward: 5, 4, 3, 2, 1, BLAST OFF","Count again -- faster"],
             "say":['"One finger... two fingers... all the way to five!"','"Now backward: 5, 4, 3, 2, 1 -- BLAST OFF!"','"You know all the numbers to ten!"'],
             "if_happens":"Child skips numbers or gets stuck at 4",
             "avoid":'"No -- five comes after four."',
             "better":'"Four... and then... (pause)... five! Four and five are best friends. Try again."',
             "why":"Rote counting -- memorising the sequence of number words -- precedes conceptual counting (understanding that 5 corresponds to 5 objects) by months. The sequence must be automatic before it can carry meaning. Counting backward is particularly valuable because it builds the mental number line in both directions, which is crucial for later subtraction. Counting from a higher start also builds sequence flexibility.",
             "tool":"Number Friends",
             "phrases":['"Four and five are always together."','"Numbers live in a line -- in the same order every time."'],
             "skills":"Rote counting, number sequence, number line awareness."},
        2:  {"title":"Count the Stairs","emoji":"🪜","skill":"Applied Counting","materials":"Stairs",
             "milestone":"Milestone: Counting objects in the environment -- applied counting -- builds the one-to-one correspondence principle: one word for each object, no object counted twice.",
             "setup":["Find any set of stairs or steps"],
             "play":["Count each stair as you step on it: 1, 2, 3...","Count going up AND going down","Try counting other things: cushions, spoons, windows","One tap per count"],
             "say":['"Ready to count stairs? Step and count!"','"Touch and count -- one tap for each number."','"How many were there? Let us count again to check."'],
             "if_happens":"Child counts too fast and touches wrong number of objects",
             "avoid":'"Slow down -- you miscounted."',
             "better":'"You are counting so fast! This time: touch each one and say the number -- they have to match."',
             "why":"One-to-one correspondence -- the understanding that each count word corresponds to exactly one object -- is the most fundamental conceptual achievement in early number development. Children often know number words but assign them arbitrarily (counting the same object twice or skipping one). Slowing down and requiring a physical touch per count makes the correspondence concrete and enforceable.",
             "tool":"Touch and Count",
             "phrases":['"One touch, one number -- they match."','"Count the tap, not just the air."'],
             "skills":"One-to-one correspondence, applied counting, cardinality."},
        3:  {"title":"How Many Grapes?","emoji":"🍇","skill":"Cardinality","materials":"A snack with countable items",
             "milestone":"Milestone: Understanding cardinality -- that the last number counted is the total amount -- is a major conceptual step that typically emerges between 2.5 and 3.5 years.",
             "setup":["Put 3-5 of a snack on a plate","Ask: how many grapes (or raisins, etc.)?"],
             "play":["Child counts: 1, 2, 3, 4","Ask: so how many are there?","If they say 4: they understand cardinality","If they recount: gently help them see: you already know -- you counted!"],
             "say":['"How many grapes are there? Count and tell me."','"You said... 4! So how MANY is there? How many altogether?"','"The last number you said is the answer!"'],
             "if_happens":"Child recounts every time instead of naming the total",
             "avoid":'"You already counted -- stop recounting."',
             "better":'"Count them -- and when you finish, tell me the last number you said. That is the magic answer."',
             "why":"Cardinality -- the understanding that the final counting word represents the quantity of the whole set -- is one of the most conceptually rich milestones in early number development. Many children can count but do not understand cardinality: they recount rather than name the total. The magic last number framing draws attention to the linguistic-conceptual link between counting and total.",
             "tool":"The Last Number Wins",
             "phrases":['"The last number you say is the total."','"Count once and know forever."'],
             "skills":"Cardinality, counting accuracy, number meaning."},
        4:  {"title":"Count by Clapping","emoji":"👏","skill":"Rhythmic Counting","materials":"None",
             "milestone":"Milestone: Counting with rhythm -- clapping, tapping, stomping -- encodes numbers with motor memory, making them more durable and accessible under cognitive load (like social situations).",
             "setup":["Stand or sit ready to clap"],
             "play":["Clap 1-5 counting with each clap","Clap a number -- child says how many: (clap clap clap) = 3","Stomp-count: stomp and say each number","Rhythmic counting songs: 1, 2, 3, 4, 5 -- Once I caught a fish alive"],
             "say":['"Clap and count -- one clap, one number."','"How many claps did I do? Count the sound."','"Stomp and count -- big stomps!"'],
             "if_happens":"Child counts the claps after they stop instead of during",
             "avoid":'"Count as I clap -- not after."',
             "better":'"OK, count after -- tell me the total. That works too. Now try counting as it happens."',
             "why":"Rhythmic counting encodes number sequences through the motor system, which produces a qualitatively different kind of memory -- procedural memory -- that is more automatic and resistant to forgetting than declarative memory. Children who have strong rhythmic counting skills show better arithmetic speed in early primary school because the number sequence retrieval is partially handled by the motor system.",
             "tool":"Clap Count",
             "phrases":['"Your hands count for you."','"When the rhythm and the number match, counting gets easy."'],
             "skills":"Rhythmic counting, auditory-motor integration, number automaticity."},
        5:  {"title":"More or Fewer?","emoji":"⚖️","skill":"Quantity Comparison","materials":"Two groups of objects",
             "milestone":"Milestone: Understanding more and fewer -- comparing quantities without counting -- is an innate numerical sense (numerosity) that is the first mathematical perception. It is present at birth and develops throughout early childhood.",
             "setup":["Two groups of objects (5 vs 2, clearly different)"],
             "play":["Which group has more?","Which group has fewer?","Move from big differences (5 vs 2) to smaller (4 vs 3)","Add one: now which has more?"],
             "say":['"Which pile has more? Which has fewer?"','"How do you know?"','"I added one -- now which has more?"'],
             "if_happens":"Child guesses randomly",
             "avoid":'"Look carefully -- count them."',
             "better":'"Which pile LOOKS bigger? Just looking -- no counting yet. Your eye has a feeling."',
             "why":"Numerosity -- the intuitive sense of quantity size without counting -- is supported by the Approximate Number System (ANS), a core neural system present from birth. ANS acuity in toddlerhood is a strong predictor of later mathematical achievement. The instruction to look before counting activates the ANS rather than bypassing it with counting, which is more developmentally valuable at this age.",
             "tool":"Eye Estimate",
             "phrases":['"Your eyes can feel the difference."','"More and fewer are the first math."'],
             "skills":"Numerosity, quantity comparison, approximate number system."},
        6:  {"title":"Count on a Walk","emoji":"🚶","skill":"Environmental Counting","materials":"Outdoor or indoor walk",
             "milestone":"Milestone: Finding and counting things in the environment builds the mathematical disposition -- the habit of noticing quantity in the world -- that is more foundational than any specific counting skill.",
             "setup":["Take a walk indoors or outdoors","Pick a counting target"],
             "play":["Count: doors, trees, red things, cars, birds","Make it a challenge: can we find 10 dogs today?","Count together and remember the total","Record (verbally) how many you found"],
             "say":['"How many red cars can we count on this walk?"','"We found 6! Can we beat 6 next time?"','"Mathematics is hiding everywhere -- we just have to look."'],
             "if_happens":"Child loses count and starts over repeatedly",
             "avoid":'"Keep up -- you lost the count."',
             "better":'"We lost the count -- let us use fingers as a tracker. Each time we see one, I hold up a finger. Then we count the fingers at the end."',
             "why":"Environmental counting builds what mathematics educators call the mathematical disposition -- an orientation toward noticing and quantifying the world. Children who habitually count things they encounter develop mathematical fluency not through instruction but through practice integrated into daily life. The finger-tracking strategy provides an external working memory support that reduces cognitive load.",
             "tool":"Math Is Everywhere",
             "phrases":['"Mathematics is hiding in plain sight."','"Every collection of things is a counting opportunity."'],
             "skills":"Environmental counting, mathematical disposition, working memory strategy."},
        7:  "reflection",
        8:  {"title":"Sort by Colour","emoji":"🔴","skill":"Categorical Thinking","materials":"Mixed-colour objects (blocks, socks, buttons)",
             "milestone":"Milestone: Sorting by a single attribute -- colour, shape, size -- is the first logical classification operation and the foundation of all categorical thinking in science and mathematics.",
             "setup":["A mixed pile of objects with 2-3 clear colour groups"],
             "play":["Sort: all the reds together, all the blues together","Name each group as you sort","Mix them up and sort again -- try size next","Try: can an object go in TWO groups?"],
             "say":['"Let us put all the red ones here -- they are the same."','"What is the same about all the ones in this group?"','"Could this one go in two groups? How?"'],
             "if_happens":"Child sorts randomly or by personal preference (keeps favourites together)",
             "avoid":'"Sort by colour -- not by which ones you like."',
             "better":'"Oh interesting! You are sorting by your favourites -- that is a rule too. What IS your rule?"',
             "why":"Sorting reveals the sorting rule the child is using -- which may be colour, shape, size, or something idiosyncratic. Asking what is your rule? rather than imposing the adult's rule teaches children that sorting is a rule-based activity and that the thinker chooses the rule. This metacognitive framing transforms sorting from a compliance task into a logical reasoning exercise.",
             "tool":"What Is Your Rule?",
             "phrases":['"What is your rule for this group?"','"Sorting is just making a decision about what goes together."'],
             "skills":"Categorical classification, rule-based sorting, logical reasoning."},
        9:  {"title":"Match the Shape","emoji":"⬜","skill":"Shape Recognition","materials":"Shape sorter or drawn shapes",
             "milestone":"Milestone: Recognising and naming basic 2D shapes -- circle, square, triangle, rectangle -- builds the geometric vocabulary and spatial reasoning that underpin both reading (letter shapes) and mathematics.",
             "setup":["Shape sorter toy or cut-out paper shapes"],
             "play":["Name each shape: circle, square, triangle, rectangle","Match shapes that are the same","Find shapes in the room: windows are rectangles, plates are circles","Draw shapes together"],
             "say":['"This is a circle -- round all the way around."','"Where do you see a rectangle in this room?"','"Three sides -- that makes a triangle."'],
             "if_happens":"Child confuses square and rectangle",
             "avoid":'"No -- that is a rectangle, not a square."',
             "better":'"A square is a special rectangle where all 4 sides are the same length. So a square is ALSO a rectangle! Tricky, right?"',
             "why":"Shape recognition at this age builds the visual spatial schemas that are foundational for letter recognition (b and d differ only in spatial orientation), number recognition (6 and 9 differ only in orientation), and geometric reasoning. The square-rectangle relationship is actually an important early mathematical concept: the relationship between a general category (rectangle) and a specific case (square).",
             "tool":"Shape Spotter",
             "phrases":['"Shapes are everywhere -- look for them."','"Every shape has rules about its sides and corners."'],
             "skills":"Shape recognition, geometric vocabulary, spatial reasoning."},
        10: {"title":"Same and Different","emoji":"🔍","skill":"Comparison","materials":"Two similar objects",
             "milestone":"Milestone: Finding what is same AND what is different about two objects simultaneously is the cognitive operation of comparison -- the foundation of all scientific observation and mathematical reasoning.",
             "setup":["Two objects that are similar but not identical (two spoons, two shoes)"],
             "play":["Put both objects side by side","Find everything that is the same: colour, shape, material","Find everything that is different: size, handle, age","How many sames? How many differents?"],
             "say":['"What is the same about these two? List everything."','"Now: what is different?"','"More sames or more differents?"'],
             "if_happens":"Child only finds differences or only sames",
             "avoid":'"Look for the OTHER ones too."',
             "better":'"You found all the differences -- you are a difference expert! Now I challenge you: find just ONE same. Just one."',
             "why":"The Venn diagram concept -- things that are the same AND different at the same time -- is one of the most important logical structures in mathematics, science, and language. The game of finding both sames and differences simultaneously builds the intellectual flexibility to hold two analytical frameworks in mind concurrently. This is the foundation of analogy, metaphor, and classification.",
             "tool":"Same Different Both",
             "phrases":['"Things can be the same AND different at the same time."','"A same and a different can live in the same object."'],
             "skills":"Comparison, analogical reasoning, dual perspective."},
        11: {"title":"Sort by Size","emoji":"📏","skill":"Ordinal Thinking","materials":"Objects of varying sizes",
             "milestone":"Milestone: Ordering objects from smallest to largest (or tallest to shortest) introduces ordinal relationships -- the idea that numbers and quantities have an order, not just discrete values.",
             "setup":["5-7 objects of clearly different sizes: nesting cups, toys, blocks"],
             "play":["Line them up: smallest to biggest","Then biggest to smallest","Ask: which is second smallest?","Add one and re-sort"],
             "say":['"Line them up from the smallest to the biggest."','"Where does this new one go? In the right order."','"Which one is the third biggest?"'],
             "if_happens":"Child places them randomly",
             "avoid":'"That is not in order -- try again."',
             "better":'"Let us find the very smallest first. Just that one. Now the very biggest. Now the middle one. One at a time."',
             "why":"Ordinal reasoning -- understanding that things can be placed in a rank order -- is the conceptual bridge between cardinal numbers (how many) and ordinal numbers (which position in a sequence). Seriation (ordering objects by size) is one of Piaget's key preoperational operations. The one-at-a-time strategy reduces working memory load by converting a multi-comparison problem into a series of binary comparisons.",
             "tool":"Order From Small to Big",
             "phrases":['"Smallest first. Biggest last. Everything in between has its place."','"Numbers are in order -- so are sizes."'],
             "skills":"Ordinal thinking, seriation, spatial ordering."},
        12: {"title":"My Special Collection","emoji":"🪣","skill":"Classification + Ownership","materials":"Child chooses objects to collect",
             "milestone":"Milestone: Creating and explaining a personal collection develops the ability to articulate sorting rules, which is an early form of mathematical definition-making.",
             "setup":["Give a bag or container","Child collects 10 things of their choice"],
             "play":["Walk around -- child collects whatever they want","Back together: lay out the collection","Ask: what is the rule? What do these have in common?","Child explains their collection principle"],
             "say":['"Collect anything you want -- 10 things."','"Why did you choose these? What is the same about them?"','"That is YOUR collection rule -- you made it."'],
             "if_happens":"Child chooses randomly with no apparent rule",
             "avoid":'"What do these have in common? There must be something."',
             "better":'"OK -- let us look for a rule together. Are any of them the same colour? Size? Feeling? Even one connection?"',
             "why":"Child-generated collections are more cognitively demanding than adult-assigned sorting tasks because the child must generate their own category criterion. This is definition-making: the child implicitly defines a set by choosing which elements belong and which do not. Even idiosyncratic rules (I like them) are valid and can be articulated and examined. Articulating any sorting rule builds mathematical language.",
             "tool":"Your Collection Rule",
             "phrases":['"You invented this category -- you made the rule."','"A collection needs a reason to stick together."'],
             "skills":"Self-generated classification, definition-making, mathematical language."},
        13: {"title":"Sort in Two Ways","emoji":"🔀","skill":"Multi-Attribute Sorting","materials":"Objects with multiple attributes",
             "milestone":"Milestone: Sorting the same objects in two different ways demonstrates cognitive flexibility -- the ability to shift criteria -- which is a key executive function and mathematical thinking skill.",
             "setup":["Objects that have 2 sortable attributes: colour AND size"],
             "play":["Sort by colour first","Mix them up","Sort by size","Ask: same objects, different groups -- how?","Can we sort them in 3 ways?"],
             "say":['"First sort: by colour."','"Now mix and sort again: by size."','"Same objects -- different groups. How did that happen?"'],
             "if_happens":"Child cannot shift criteria after the first sort",
             "avoid":'"No -- now by SIZE, not colour."',
             "better":'"The colour sort is done -- you are a colour expert. Now forget colour. Pretend the objects have no colour. What else is there?"',
             "why":"Cognitive flexibility -- the ability to shift perspective or criterion on a task -- is one of the core executive functions and is directly related to mathematical abstraction. Children who can sort the same objects in multiple ways understand that categories are chosen frameworks, not inherent properties of objects. This is a foundational insight for understanding variables in later algebra.",
             "tool":"Change the Rule",
             "phrases":['"Same things, different rule, different groups."','"You can always look at things with new eyes."'],
             "skills":"Cognitive flexibility, multi-attribute classification, executive function."},
        14: "reflection",
        15: {"title":"Find the Pattern","emoji":"🟥","skill":"Pattern Recognition","materials":"Coloured blocks or objects",
             "milestone":"Milestone: Recognising and extending a repeating pattern (ABABAB, AABBAABB) is one of the most foundational algebraic thinking skills that develops between ages 2 and 4.",
             "setup":["Lay out a simple AB pattern: red, blue, red, blue, red...","Leave a gap at the end"],
             "play":["Ask: what comes next?","Extend the pattern together","Create a new pattern: AABB or ABC","Find patterns in the world: stripes, tiles, clothing"],
             "say":['"What comes next in this pattern?"','"Why? What is the rule?"','"Make your own pattern -- I will extend it."'],
             "if_happens":"Child breaks the pattern with a random choice",
             "avoid":'"That breaks the pattern -- it should be blue."',
             "better":'"Interesting choice! What pattern would that create? Let us follow YOUR rule now -- what comes next in YOUR version?"',
             "why":"Pattern recognition and extension is the entry point of algebraic thinking because it requires identifying an abstract rule (the pattern) and applying it prospectively (what comes next). Research shows that early pattern competence strongly predicts later algebra performance. Following the child's accidental pattern -- making it intentional and correct on its own terms -- teaches that patterns are created by rules.",
             "tool":"The Rule Behind the Pattern",
             "phrases":['"Every pattern has a hidden rule."','"What is the rule? Can you say it in words?"'],
             "skills":"Pattern recognition, algebraic thinking, rule articulation."},
        16: {"title":"Body Pattern","emoji":"🎵","skill":"Movement Patterns","materials":"None",
             "milestone":"Milestone: Performing a body movement pattern -- clap, stomp, clap, stomp -- integrates motor, rhythmic, and mathematical pattern thinking simultaneously, encoding the concept in multiple memory systems.",
             "setup":["Stand up with space to move"],
             "play":["Create a body pattern: clap, stomp, clap, stomp","Add complexity: clap, clap, stomp, stomp","Child creates their own body pattern","Record it: describe the pattern in words"],
             "say":['"Clap... stomp... clap... stomp... what comes next?"','"Now you make a body pattern and I will join."','"Can you say the pattern in words? Clap-stomp-clap-stomp?"'],
             "if_happens":"Child makes a random sequence",
             "avoid":'"That is not a pattern -- it needs to repeat."',
             "better":'"Let me name what you did: stomp-clap-stomp-clap! That IS a pattern -- you made it! Now do the same thing again."',
             "why":"Body pattern activities build mathematical pattern recognition through kinesthetic encoding, which produces a different and complementary type of learning from visual pattern work. The verbal labelling of the pattern (clap-stomp-clap-stomp) translates the motor experience into mathematical language, creating a cross-format pattern representation that is more robust than either alone.",
             "tool":"Body Math",
             "phrases":['"Your body can do math."','"Name the pattern with words -- then it is yours forever."'],
             "skills":"Movement patterns, kinesthetic mathematical encoding, pattern language."},
        17: {"title":"Nature Patterns","emoji":"🌿","skill":"Mathematical Observation","materials":"Outdoor or indoor nature items",
             "milestone":"Milestone: Finding mathematical patterns in nature -- symmetry in leaves, stripes in shells, spirals in sunflowers -- builds the habit of seeing mathematics as woven into the real world.",
             "setup":["Walk outdoors or collect nature items","Look for patterns and symmetry"],
             "play":["Find a striped leaf or shell","Find a symmetrical flower","Look for spirals: snail, sunflower","Collect 3 pattern examples"],
             "say":['"Look -- this leaf has stripes. That is a pattern."','"This flower -- is the same on both sides? That is called symmetry."','"Nature loves patterns -- why do you think?"'],
             "if_happens":"Child cannot find patterns",
             "avoid":'"Look harder -- there are patterns everywhere."',
             "better":'"Let me find one first -- look at this leaf. See the stripes? Now you look for something striped."',
             "why":"Biological structures frequently exhibit mathematical patterns because patterns (symmetry, spirals, branching) are solutions to evolutionary problems (efficient growth, stability, resource distribution). Teaching children to see these patterns builds mathematical aesthetics -- the sense that mathematics is beautiful and natural -- which is a powerful motivator for continued mathematical engagement. This is the affective foundation of mathematical learning.",
             "tool":"Nature's Math",
             "phrases":['"Nature uses math to build beautiful things."','"A pattern in nature has a job to do."'],
             "skills":"Pattern observation, natural mathematics, mathematical aesthetics."},
        18: {"title":"Build a Pattern Train","emoji":"🚂","skill":"Pattern Extension","materials":"Blocks, beads, or coloured objects",
             "milestone":"Milestone: Extending a pattern without prompting -- adding to a series independently -- demonstrates pattern internalisation: the child has the rule and applies it autonomously.",
             "setup":["Start a pattern train: red block, blue block, red block, blue block","Provide more blocks"],
             "play":["Ask: keep going -- what comes next?","Child extends as far as blocks allow","Introduce a new pattern for child to start","Parent extends their pattern"],
             "say":['"Keep the train going -- add the next one."','"Tell me the rule before you add the next one."','"Now YOU start a pattern and I will add to yours."'],
             "if_happens":"Child adds correctly but cannot explain the rule",
             "avoid":'"Tell me the rule before you add."',
             "better":'"You added correctly -- your brain knows the rule even if the words are not ready. Let us say it together: red, blue, red, blue, so next is..."',
             "why":"Pattern extension without prompting demonstrates that the child has internalised the pattern rule rather than responding to visual cues. Being able to articulate the rule -- even partially -- begins the translation of implicit pattern knowledge into explicit mathematical language. This verbalization is the bridge between intuitive pattern sense and formal mathematical reasoning.",
             "tool":"Extend and Explain",
             "phrases":['"You knew the rule -- your hand added correctly."','"Now teach the rule to me in words."'],
             "skills":"Pattern internalisation, autonomous extension, mathematical verbalization."},
        19: {"title":"What Is Missing?","emoji":"❓","skill":"Number Sense and Gaps","materials":"Objects in a sequence with one removed",
             "milestone":"Milestone: Identifying what is missing from a pattern or sequence requires holding the complete sequence in working memory and detecting the gap -- a foundational skill for reading (letters), music (notes), and mathematics (number gaps).",
             "setup":["Lay out a pattern or sequence: 1-2-3-?-5","Cover or remove one item"],
             "play":["What is missing?","What comes before and after the gap?","Try with objects, then numbers","Try with a story: what is missing from this sequence?"],
             "say":['"Something is missing -- what should go here?"','"What was before it? What comes after? So what is it?"','"Good detective work!"'],
             "if_happens":"Child guesses randomly",
             "avoid":'"Think -- look at what comes before and after."',
             "better":'"Let us go really slowly. What is the one before the gap? Name it. What is the one after? Name it. Now, what fits between them?"',
             "why":"Gap detection in sequences activates the same neural mechanism as reading missing letters in words (c_t = cat) and solving for unknowns in algebra (2 + ? = 5). Teaching this skill early with physical objects builds the mental representation of gaps and unknowns that formal mathematics instruction will later work with. It also develops the inference habit: use what you know to figure out what you do not know.",
             "tool":"Fill the Gap",
             "phrases":['"Use what you know to find what you do not know."','"The gap has exactly one answer."'],
             "skills":"Gap detection, inference, working memory, unknown-finding."},
        20: {"title":"Pattern All Around","emoji":"🌀","skill":"Pattern in Daily Life","materials":"The house itself",
             "milestone":"Milestone: Noticing patterns in everyday environments -- tiles, wallpaper, clothing, music, routines -- builds the automatic pattern-seeking orientation that makes mathematics feel natural.",
             "setup":["Walk through your home together","Pattern-spotting mission"],
             "play":["Find 10 patterns: floor tiles, window blinds, clothing stripes, music rhythms","Photograph or draw each one","Sort them: visual vs sound vs touch patterns","Which pattern is your favourite?"],
             "say":['"We are on a pattern hunt -- find everything with a repeat."','"There is a pattern in the floor -- name the rule."','"Even your daily routine is a pattern: wake, eat, play, sleep, repeat."'],
             "if_happens":"Child confuses pattern with decoration",
             "avoid":'"That is not a pattern -- it has to repeat."',
             "better":'"Does this repeat? If I kept going -- would the same thing come back? If yes, it is a pattern."',
             "why":"The habit of noticing patterns in the environment is a mathematical disposition -- an orientation toward the world that finds mathematics in everyday experience. Children who develop this disposition early have fundamentally different mathematical learning trajectories than those who associate mathematics only with school and worksheets. The repeat criterion is the correct mathematical definition and worth teaching precisely.",
             "tool":"Pattern Hunter",
             "phrases":['"A pattern needs a repeat."','"When something repeats, there is a rule."'],
             "skills":"Pattern in environment, mathematical disposition, pattern definition."},
        21: "reflection",
        22: {"title":"Give Me More","emoji":"➕","skill":"Addition Sense","materials":"Small objects",
             "milestone":"Milestone: Informal addition -- adding one more and seeing that the group grew -- is the earliest form of additive reasoning that precedes formal addition by years.",
             "setup":["3 objects in a group"],
             "play":["Count the group: 3","Add one more","Count again: 4","Add one more: 5","Say: we ADDED one, the number GOT BIGGER"],
             "say":['"We have 3. I am adding one more."','"Count again -- what do we have now?"','"We added -- the number grew!"'],
             "if_happens":"Child cannot connect the adding action to the number change",
             "avoid":'"When you add, the number goes up."',
             "better":'"Watch my hand: (add one) -- I put one in. Now count. Did it change? That is what add means."',
             "why":"Informal addition -- the experiential understanding that adding an object increases the total -- precedes and supports formal arithmetic. Research shows that children with strong informal arithmetic intuitions (more after adding, fewer after taking away) master formal arithmetic more quickly and with less procedural confusion than those who learn formal operations without the underlying concept.",
             "tool":"Add and Count Again",
             "phrases":['"When you add, count again -- the number grows."','"More things, bigger number."'],
             "skills":"Informal addition, additive reasoning, number change."},
        23: {"title":"Take One Away","emoji":"➖","skill":"Subtraction Sense","materials":"Small objects",
             "milestone":"Milestone: Informal subtraction -- removing an object and seeing that the group shrank -- builds the intuitive subtraction concept that formal arithmetic instruction will later formalise.",
             "setup":["5 objects in a group"],
             "play":["Count the group: 5","Take one away","Count again: 4","Take one away: 3","Say: we TOOK AWAY one, the number got SMALLER"],
             "say":['"We have 5. I am taking one away."','"Count again -- what now?"','"We subtracted -- the number got smaller!"'],
             "if_happens":"Child wants to add back immediately",
             "avoid":'"No -- we are taking away, not adding back."',
             "better":'"You want to give it back! OK -- let us count before and after: 3 before, 4 after. Adding made it bigger again. See?"',
             "why":"Informal subtraction is the intuitive complement to informal addition. Research shows that children grasp the concepts of more-after-adding and fewer-after-removing well before they can perform formal arithmetic operations. Allowing the child to spontaneously re-add the removed object provides a perfect opportunity to explore the inverse relationship between addition and subtraction -- one of the deepest mathematical concepts.",
             "tool":"Take and Count Again",
             "phrases":['"When you take away, count again -- the number shrinks."','"Fewer things, smaller number."'],
             "skills":"Informal subtraction, subtractive reasoning, number change."},
        24: {"title":"Fair Share","emoji":"🍕","skill":"Division Concept","materials":"Snack to divide",
             "milestone":"Milestone: Fair sharing -- dividing a quantity into equal groups -- is the earliest form of division reasoning and also a social justice concept. It introduces the mathematical equality that formal fractions will later build on.",
             "setup":["4-6 of a snack","2 people to share"],
             "play":["How can we share these so we each get the same?","Distribute: one for you, one for me...","Count each person's share: are they equal?","What if we have one left over? What do we do?"],
             "say":['"How do we share these fairly? Same for each of us."','"Count yours, count mine -- are they the same?"','"There is one left over -- what should we do?"'],
             "if_happens":"Child wants all the food",
             "avoid":'"You have to share -- half is mine."',
             "better":'"If you keep all, I have zero. And if I have zero, I get sad. How could we each have some?"',
             "why":"Fair sharing introduces the concept of equal distribution, which is the foundational intuition behind division and fractions. The one-for-you-one-for-me dealing strategy is a natural algorithm that children discover independently and represents one of the earliest forms of mathematical reasoning. The remainder problem (what if there is one left over?) introduces the concept of indivisibility, which is foundational for understanding fractions.",
             "tool":"Same for Both",
             "phrases":['"Fair means the same amount for each person."','"The leftover is the hardest part of sharing."'],
             "skills":"Fair sharing, division concept, equality, remainder."},
        25: {"title":"Big Number, Small Number","emoji":"🔢","skill":"Number Magnitude","materials":"Number cards 1-10 (or written numbers)",
             "milestone":"Milestone: Understanding that some numbers are bigger than others and being able to place numbers in order of magnitude is a key bridge between counting and arithmetic.",
             "setup":["Cards or written numbers 1-5","Mix them up"],
             "play":["Put them in order: 1, 2, 3, 4, 5","Which is biggest? Which is smallest?","Point to 3 -- is that big or small?","If I have 5 and you have 2, who has more?"],
             "say":['"Put the numbers in order -- smallest first."','"Which number is bigger: 3 or 5?"','"Five is bigger than three -- 5 is further along in the number line."'],
             "if_happens":"Child confuses which number is bigger",
             "avoid":'"No -- 5 is bigger, not 3."',
             "better":'"Let us count to each one: 1, 2, 3 -- and 1, 2, 3, 4, 5. Which took longer to get to? The longer count means bigger number."',
             "why":"Number magnitude -- understanding the relative size of numbers -- is distinct from counting and requires the child to understand numbers as quantities on a mental number line. This mental number line representation is one of the strongest predictors of mathematical achievement and is directly built by activities that require magnitude comparison. The further-along-the-count explanation makes the magnitude-count relationship explicit.",
             "tool":"Further Means Bigger",
             "phrases":['"The higher you count to get there, the bigger it is."','"5 is further along than 3."'],
             "skills":"Number magnitude, mental number line, magnitude comparison."},
        26: {"title":"Measure With Hands","emoji":"📐","skill":"Non-Standard Measurement","materials":"Objects to measure, hands as units",
             "milestone":"Milestone: Measuring with non-standard units (hands, feet, blocks) introduces the concept of measurement as repeated application of a unit, and the relationship between unit size and count.",
             "setup":["Measure the table: how many hand-widths?","Lay hands side by side"],
             "play":["Measure the table in hand-widths: 6 hands","Measure the same table in YOUR hands: is the number different?","Try foot-lengths: how many feet is the sofa?","Different unit, different number -- but same length"],
             "say":['"How many hand-widths is the table?"','"Now measure with YOUR hands -- same or different number?"','"The table did not change -- why is the number different?"'],
             "if_happens":"Child does not understand why different hands give different numbers",
             "avoid":'"Because your hand is smaller."',
             "better":'"Let us lay our hands next to each other -- see the size difference? Bigger unit means fewer needed. Smaller unit means more needed."',
             "why":"Non-standard measurement activities are foundational for understanding the unit concept in measurement -- the idea that a measurement is always a count of units, and that changing the unit changes the count while leaving the measured quantity unchanged. This is one of the most conceptually important insights in measurement mathematics and takes years to develop fully.",
             "tool":"Unit and Count",
             "phrases":['"The same length -- different units, different counts."','"When you change the ruler, the number changes but the table stays the same."'],
             "skills":"Non-standard measurement, unit concept, proportional reasoning."},
        27: {"title":"Number Story","emoji":"📖","skill":"Mathematical Narrative","materials":"None",
             "milestone":"Milestone: Number stories -- verbal problems embedded in narratives -- are the bridge between informal mathematical intuition and formal arithmetic. Children who hear number stories before age 4 show stronger arithmetic.",
             "setup":["Make up a simple number story together"],
             "play":["Tell a story with numbers: 3 bears were walking. 2 more joined them. How many bears?","Act it out with toys or fingers","Make up more stories together","Try a story where bears LEAVE: how many now?"],
             "say":['"3 bears were walking. 2 more joined them. How many bears altogether?"','"Let us act it out -- get the bears."','"Now YOU make a bear story."'],
             "if_happens":"Child does not know how to answer",
             "avoid":'"Count them -- how many bears?"',
             "better":'"Let us use fingers. Show me 3 fingers for the first bears. Now 2 more. How many fingers are up?"',
             "why":"Word problems embedded in narratives activate both the narrative comprehension system and the mathematical reasoning system simultaneously. Research shows that children who learn arithmetic through narrative word problems develop stronger problem representation skills -- the ability to model the mathematical structure of a situation -- than those who learn only through abstract number operations.",
             "tool":"Math Story",
             "phrases":['"Stories can have math hidden inside them."','"Show the math with your fingers -- then count."'],
             "skills":"Arithmetic story problems, addition and subtraction, mathematical narrative."},
        28: "reflection",
        29: {"title":"Our Number Book","emoji":"📗","skill":"Mathematical Documentation","materials":"Paper, crayons, stapler",
             "milestone":"Milestone: Creating a personal number book -- a child-authored mathematical document -- integrates counting, quantity, and representation into a self-referential artefact that builds mathematical identity.",
             "setup":["Fold 5 pages, staple","Number each page 1-5"],
             "play":["Page 1: draw 1 thing they love","Page 2: draw 2 things","Up to page 5","Write the number on each page","Count together at the end"],
             "say":['"Page 1: draw exactly ONE thing you love."','"Count the things on page 3 -- are there exactly 3?"','"You made a number book. You are a mathematician."'],
             "if_happens":"Child draws too many on one page",
             "avoid":'"Too many -- you drew 4 on page 2."',
             "better":'"Count them -- 4! So which page does this one belong on? Let us move it to page 4."',
             "why":"A child-authored number book requires the child to deliberately represent specific quantities -- to intentionally draw exactly 3 things. This intentional quantity representation is a higher-order task than counting presented objects. It requires the child to hold the target number in mind and generate elements to reach it, building the active number concept that arithmetic requires.",
             "tool":"Draw the Number",
             "phrases":['"Draw exactly that many -- count as you draw."','"You are the author of this number story."'],
             "skills":"Intentional quantity representation, cardinality, mathematical authorship."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 8 Complete: Little Mathematician!",
        "summary": "This month your child counted, sorted, matched, found patterns, compared quantities, added, subtracted, and shared fairly. The mathematical mind is alive and growing.",
        "skills_built": ["Counting to 10 with one-to-one correspondence", "Sorting by colour, size, and shape", "Pattern recognition and extension", "Informal addition and subtraction", "Fair sharing and early division sense"],
        "month_next_teaser": "Next month: Nature and Curiosity. Your child will become a scientist -- looking closely, asking questions, exploring water and earth, and wondering about the living world.",
    },
    "reflection_activities": {
        7:  {"activity": "Count the House", "desc": "How many doors in your home? How many windows? How many chairs? Count everything."},
        14: {"activity": "Sort the Toy Box", "desc": "Sort your toys three different ways: by colour, by size, by type. Which sort works best?"},
        21: {"activity": "Pattern Creator", "desc": "Create the most complex pattern you can using anything in the house. Photograph it. Write the rule."},
        28: {"activity": "Math in the Day", "desc": "Count something you use every day. More at breakfast or dinner? Compare the numbers."},
    },
}
