"""Month 9: Nature & Curiosity -- curriculum data"""
M9 = {
    "name": "Nature & Curiosity",
    "toolkit_label": "2--3 Years &middot; Month 9",
    "weeks": {
        1: {"title": "Looking Closely", "subtitle": "The world is bigger when you look smaller"},
        2: {"title": "Water & Earth", "subtitle": "The elements your child was born to explore"},
        3: {"title": "Plants & Growing", "subtitle": "Life that takes time to reveal itself"},
        4: {"title": "Animals & Wondering", "subtitle": "The creatures we share this world with"},
    },
    "days": {
        1:  {"title":"The Wonder Walk","emoji":"🔍","skill":"Scientific Observation","materials":"Walk outside",
             "milestone":"Milestone: Scientific observation -- slowing down to notice details -- is the first scientific skill and the basis of all empirical inquiry. Children who develop the habit of careful looking become better problem-solvers.",
             "setup":["Go outside or look out a window","Move slowly -- slower than usual"],
             "play":["Walk 10 paces -- find 3 things to observe closely","Look at one thing for 30 full seconds","Describe what you see: colour, texture, shape","Ask: what question does this thing make you have?"],
             "say":['"Stop. Look at this -- really look. What do you see?"','"30 seconds -- stay with it. What else do you notice?"','"What question does this thing make you have?"'],
             "if_happens":"Child wants to rush ahead",
             "avoid":'"Stop running -- we are observing."',
             "better":'"You found something 10 steps ahead! Great -- run to it. NOW stop and look for 30 seconds."',
             "why":"Sustained visual attention to natural objects -- holding gaze for 30 full seconds -- is the developmental precursor of scientific observation. Research by Megan Bang shows that Indigenous and nature-connected children develop stronger ecological reasoning and systems thinking than those with less nature contact. The practice of asking what question does this make you have? builds the inquiry habit that drives scientific thinking.",
             "tool":"Wonder Eyes",
             "phrases":['"Look until you see something you almost missed."','"Every question you have is a scientist starting."'],
             "skills":"Scientific observation, sustained attention, inquiry habit."},
        2:  {"title":"Tiny World","emoji":"🐜","skill":"Scale Perspective","materials":"Magnifying glass if available",
             "milestone":"Milestone: Understanding that the world looks different at different scales -- that tiny things have complex structure -- develops spatial reasoning and the scientific concept of scale.",
             "setup":["Any outdoor surface: grass, bark, soil","Magnifying glass optional"],
             "play":["Lie on the ground and look at grass level","What tiny things live there?","Look at bark up close: what do you see?","Try looking at your own hand magnified"],
             "say":['"Lie down and look at the tiny world -- what lives there?"','"These tiny things -- they have a whole world."','"What would it be like to be this small?"'],
             "if_happens":"Child is worried about getting dirty or bugs touching them",
             "avoid":'"Just lie down -- it is fine."',
             "better":'"We can look from a little higher -- just closer than usual. As close as you are comfortable. Even 10cm closer counts."',
             "why":"Changing perspective to observe at a different scale requires a fundamental cognitive operation: re-mapping the spatial framework. At 2-3 years, children are building their understanding of scale and relative size. Lying at ground level and looking upward is a genuinely disorienting experience that re-calibrates spatial awareness and builds the cognitive flexibility needed for understanding relative size in mathematics and science.",
             "tool":"Tiny World View",
             "phrases":['"The world looks different from down here."','"Tiny things have big lives."'],
             "skills":"Scale perspective, spatial re-orientation, observation depth."},
        3:  {"title":"What Is the Weather?","emoji":"🌦️","skill":"Weather Observation","materials":"Window or outdoor access",
             "milestone":"Milestone: Daily weather observation introduces the concept of measurable, changeable environmental conditions -- the foundation of meteorology and climate science.",
             "setup":["Look outside together each day","Create a weather journal (or just describe verbally)"],
             "play":["What is the weather today: sunny, cloudy, rainy, windy, cold, warm?","How does the sky look? What colour?","Compare to yesterday: the same or different?","Predict: what will it be tomorrow?"],
             "say":['"What is the weather today? Let us look at the sky."','"Yesterday was [X]. Today is [Y]. What changed?"','"What do you think tomorrow will bring?"'],
             "if_happens":"Child says the same thing every day regardless",
             "avoid":'"Look again -- it changed from yesterday."',
             "better":'"Yesterday you said sunny. Today -- look carefully -- is it exactly the same sunny? Look at the clouds."',
             "why":"Daily weather observation is one of the earliest scientific measurement activities because it requires comparison of a changeable variable across time -- the same method used in all longitudinal scientific study. The prediction component builds hypothesis formation: using past patterns to anticipate future states. These habits of mind are the practical foundation of scientific reasoning.",
             "tool":"Sky Scientist",
             "phrases":['"A scientist notices change over time."','"Yesterday and today are your two data points."'],
             "skills":"Weather observation, temporal comparison, prediction, scientific measurement."},
        4:  {"title":"Feel the Texture","emoji":"🪨","skill":"Tactile Science","materials":"Natural objects: smooth stone, rough bark, soft moss",
             "milestone":"Milestone: Systematic tactile comparison -- this is rougher than that, this is colder than that -- develops the observation and comparison skills that underpin all empirical science.",
             "setup":["Gather 4-5 natural objects with clearly different textures"],
             "play":["Touch each one without looking","Describe in one word: rough, smooth, prickly, soft, cold, warm","Order them from smoothest to roughest","Which texture do you like best and why?"],
             "say":['"Touch without looking -- what word comes to your mind?"','"Line them up from smoothest to roughest."','"Which feels most interesting? Why?"'],
             "if_happens":"Child refuses to touch rough or prickly things",
             "avoid":'"It will not hurt you -- just touch it."',
             "better":'"Touch with just one fingertip -- you can pull it back immediately if you want to. Just one second of touch."',
             "why":"Systematic tactile comparison develops haptic discrimination -- the ability to distinguish fine differences in surface texture through touch. This is a foundational sensory skill. The vocabulary development (rough, smooth, prickly) and the ordering task (ranking by roughness) add linguistic and mathematical dimensions to the sensory exploration, making it a genuinely multi-domain scientific activity.",
             "tool":"Touch Scientist",
             "phrases":['"Your skin is a science instrument."','"Describe exactly what your fingers feel."'],
             "skills":"Tactile discrimination, scientific vocabulary, comparison ordering."},
        5:  {"title":"Shadow Play","emoji":"🌞","skill":"Light Science","materials":"Sunny day or torch",
             "milestone":"Milestone: Understanding shadows -- that they are caused by blocking light and move with the light source -- is an early physics understanding that builds spatial reasoning and causal thinking.",
             "setup":["Sunny day outdoors or torch indoors","Look for shadows"],
             "play":["Find your own shadow -- where is it?","Jump: does the shadow jump?","Make hand shadows on a wall","Chase your shadow -- can you step on it?"],
             "say":['"What is a shadow? Where does it come from?"','"Jump! Did the shadow jump with you?"','"Can you make your shadow bigger? How?"'],
             "if_happens":"Child is scared of their shadow",
             "avoid":'"It is just a shadow -- do not be scared."',
             "better":'"Your shadow is made BY you -- it follows you. Everywhere you go, it comes. It is like your shape drawn in darkness."',
             "why":"Shadow science introduces children to optics -- specifically, the relationship between a light source, an opaque object, and the shadow cast. Understanding that shadows are connected to the child (they move with you) while also being separate (you cannot pick them up) is a genuinely puzzling observation that drives inquiry. The causal relationship (blocking light makes shadow) is among the first causal science concepts children grasp.",
             "tool":"Shadow Follower",
             "phrases":['"Your shadow is your shape, drawn by the sun."','"The shadow tells you where the light is coming from."'],
             "skills":"Light and shadow, causal reasoning, optics intuition."},
        6:  {"title":"Clouds and Shapes","emoji":"☁️","skill":"Imaginative Science","materials":"Cloudy day or pictures",
             "milestone":"Milestone: Looking at clouds and seeing shapes in them develops the cognitive flexibility to see multiple interpretations of ambiguous visual stimuli -- a creativity and pattern-recognition skill.",
             "setup":["Lie on the ground or sit outside looking up","Cloudy day works best"],
             "play":["What shape is that cloud?","Do different people see different things in the same cloud?","Watch one cloud change over 5 minutes","If the clouds are animals, what is the sky?"],
             "say":['"What do you see in that cloud?"','"I see a rabbit -- do you see the same thing? What else could it be?"','"Watch that cloud for 5 minutes -- does it change?"'],
             "if_happens":"Child says clouds are just clouds",
             "avoid":'"Use your imagination."',
             "better":'"OK -- clouds are clouds. What do they LOOK like? Not what they are -- what they look like."',
             "why":"Pareidolia -- the perception of meaningful shapes in ambiguous stimuli (clouds, patterns) -- is a feature of the human visual system that drives both creativity and pattern recognition. Accepting multiple interpretations of the same cloud teaches that perception is constructed, not simply received -- a proto-philosophical insight that underpins scientific understanding of observation bias and perspectives.",
             "tool":"See More Than One Thing",
             "phrases":['"The same thing can look like many different things."','"What you see and what I see can both be true."'],
             "skills":"Visual imagination, perceptual flexibility, creative observation."},
        7:  "reflection",
        8:  {"title":"Water Pour","emoji":"💧","skill":"Liquid Science","materials":"Two containers, water",
             "milestone":"Milestone: Pouring water between containers of different shapes introduces conservation of volume -- the foundational understanding that the same amount of water looks different in different containers.",
             "setup":["Two differently shaped containers","A tub for spills"],
             "play":["Pour water from one container to another","Same water -- different shape container","Which has more? (Trick question: same)","Keep pouring and observing"],
             "say":['"Pour all the water from here into there."','"Now which one has more water?"','"Is it the same water or different water?"'],
             "if_happens":"Child says the taller one has more water",
             "avoid":'"No -- it is the same amount."',
             "better":'"It looks like more! Let us pour it back... see? Same water, same amount. The tall container just spreads it out less."',
             "why":"Volume conservation -- understanding that quantity is constant even when shape changes -- is one of Piaget's classical conservation tasks. Children typically cannot pass this at 2-3 years and should not be expected to. However, providing the experience of pouring and repour builds the intuitive foundation that the formal conservation concept will later crystallise on. The experience is more important than the correct answer.",
             "tool":"Same Water",
             "phrases":['"The water is the same water -- it just changed shape."','"Shape can trick your eyes but not the amount."'],
             "skills":"Volume intuition, conservation foundation, scientific observation."},
        9:  {"title":"Sink or Float","emoji":"🛁","skill":"Density Intuition","materials":"Bathtub or basin, various objects",
             "milestone":"Milestone: Observing which objects sink and which float -- and trying to predict before testing -- builds the scientific method habit: predict, test, observe, conclude.",
             "setup":["Basin or bath with water","10 mixed objects: some that sink, some that float"],
             "play":["Predict: will this sink or float?","Test","Was the prediction right?","What do the floaters have in common? The sinkers?"],
             "say":['"Before we drop it -- predict: sink or float?"','"Was your prediction right? Why?"','"What do all the floaters have in common?"'],
             "if_happens":"Child just drops everything without predicting",
             "avoid":'"Predict first -- before you drop."',
             "better":'"Drop it! Great. Was that expected? What is your guess for the next one -- based on what you just saw?"',
             "why":"The sink-or-float activity is the most accessible introduction to the scientific method for toddlers: observe, predict, test, confirm or revise. It also builds an intuitive understanding of density (without the word), as children begin to notice that light-for-their-size objects float and heavy-for-their-size objects sink. This intuitive density understanding is a foundation for later physics.",
             "tool":"Predict and Test",
             "phrases":['"A guess before the test is a scientific prediction."','"What changed your prediction?"'],
             "skills":"Scientific method, prediction, density intuition."},
        10: {"title":"Mud Kitchen","emoji":"🟫","skill":"Sensory Science","materials":"Soil, water, sticks, leaves",
             "milestone":"Milestone: Open-ended mud play develops the scientific disposition -- willingness to investigate messy unknowns -- and builds sensory tolerance that supports emotional regulation.",
             "setup":["Outdoor space","Soil, water access, containers, sticks"],
             "play":["Dig, mix, pour, stir","Make potions and mixtures","Bury and find objects","Make mud pies, rivers, mountains"],
             "say":['"What happens when you add water to the soil?"','"How much water do you need to make it stick together?"','"Build a mountain! Make a river!"'],
             "if_happens":"Child refuses to touch mud",
             "avoid":'"It is just mud -- get your hands in."',
             "better":'"You can use a stick as a tool -- you do not have to touch it with hands. See what the stick can do."',
             "why":"Mud play is extraordinarily rich: it involves sensory processing, fine and gross motor skill, spatial reasoning, causal investigation (how much water makes it runny?), and creative construction. Research on outdoor, messy play shows that children who engage in it regularly show stronger problem-solving, creative thinking, and resilience than those restricted to clean, structured activities.",
             "tool":"Messy Scientist",
             "phrases":['"Scientists get their hands dirty."','"Mud is just earth that has met water."'],
             "skills":"Sensory processing, causal investigation, fine motor, scientific curiosity."},
        11: {"title":"Puddle Science","emoji":"🌊","skill":"Evaporation","materials":"A puddle after rain (or water on pavement)",
             "milestone":"Milestone: Observing that water disappears over time -- evaporation -- introduces the concept of reversible change and the idea that substances can change state.",
             "setup":["Find a puddle or pour water on pavement","Mark the edge with chalk"],
             "play":["Trace the puddle edge with chalk","Come back in 30 minutes: what changed?","Come back again: smaller?","Where did the water go?"],
             "say":['"We are marking the edge of the puddle -- right here."','"We came back -- did it change?"','"Where did the water go? It did not run away."'],
             "if_happens":"Child says someone drank it or it ran away",
             "avoid":'"No -- water evaporates."',
             "better":'"Interesting idea! Let us check -- there is no trail of running water. Where could it have gone without leaving a trail?"',
             "why":"Evaporation is one of the most counterintuitive physical changes young children encounter: the water simply disappears. Observing the process over time (marking and revisiting) makes the change measurable and concrete. The concept that matter can transform (liquid to gas) is deeply foundational for chemistry. The investigation of where the water went builds the disposition of seeking explanations for surprising observations.",
             "tool":"Disappearing Water",
             "phrases":['"The water went into the air -- we call that evaporation."','"Matter changes but does not disappear."'],
             "skills":"Evaporation concept, change over time, matter transformation."},
        12: {"title":"Mixing Colours","emoji":"🎨","skill":"Chemical Change","materials":"Food colouring, water, jars",
             "milestone":"Milestone: Observing that mixing two colours creates a new colour that cannot easily be un-mixed introduces the concept of irreversible change -- one of the most important distinctions in chemistry.",
             "setup":["Three jars of water","Red, yellow, and blue food colouring"],
             "play":["Make red water, yellow water, blue water","Mix red and yellow: what happens?","Try blue and yellow, red and blue","Can you un-mix them?"],
             "say":['"Mix these two -- what do you predict will happen?"','"Orange! You mixed red and yellow and made something new."','"Can we un-mix it? How would we try?"'],
             "if_happens":"Child wants to make brown by mixing everything",
             "avoid":'"Do not mix all of them."',
             "better":'"Let us predict: what colour will all three make? Then mix. Then see if you were right."',
             "why":"Colour mixing introduces the concept of irreversible chemical change: once mixed, the colours cannot be easily separated. This is conceptually different from physical changes (you can re-separate sand and water). The prediction before mixing builds the scientific hypothesis habit, and the attempt to un-mix builds understanding of irreversibility -- one of the deepest concepts in chemistry and also in life.",
             "tool":"Mix and Create",
             "phrases":['"You made something that did not exist before."','"Some things cannot be un-made."'],
             "skills":"Irreversible change, colour theory, chemical intuition."},
        13: {"title":"Garden Diary","emoji":"📔","skill":"Scientific Documentation","materials":"Paper, crayons, seeds or a plant",
             "milestone":"Milestone: Keeping a simple observation diary -- drawing a plant at intervals and comparing -- builds the scientific habit of systematic documentation that is the basis of all empirical research.",
             "setup":["Start growing something: a bean in a wet cloth, a seed in soil","Paper to draw observations"],
             "play":["Draw the plant today","Come back in 3 days: draw again","Compare the two drawings","What changed? What stayed the same?"],
             "say":['"Draw exactly what you see -- how tall, what colour, how many leaves."','"We come back in 3 days and draw again."','"Look at both drawings -- what changed?"'],
             "if_happens":"Child draws an imaginary elaborate plant rather than what is real",
             "avoid":'"Draw what is really there."',
             "better":'"That is a beautiful imaginary plant! Let us do one for the book: imaginary plant page. Now one more page: the real plant as it actually is right now."',
             "why":"Scientific observation drawing requires intentional representation of reality -- drawing what is actually there rather than what is known or imagined. This is different from expressive art and builds the observational accuracy that science requires. Comparing two observations across time introduces the concept of measurement and change over time -- the fundamental data type of biological science.",
             "tool":"Draw What Is Real",
             "phrases":['"Science drawing is different -- it has to match reality."','"The difference between drawing 1 and drawing 2 is your data."'],
             "skills":"Scientific documentation, observational drawing, temporal comparison."},
        14: "reflection",
        15: {"title":"Plant a Seed","emoji":"🌱","skill":"Life Science","materials":"Seed, soil, small pot",
             "milestone":"Milestone: Planting a seed and caring for it -- watering, observing, waiting -- introduces the concept of living things, growth cycles, and the responsibility of caring for another living organism.",
             "setup":["Pot with soil","Seed (fast-germinating: bean, radish, sunflower)"],
             "play":["Plant the seed together: hole, seed, cover, water","Ask: what does it need to grow?","Agree on a watering schedule","Make a prediction: how tall in one week?"],
             "say":['"Plant the seed -- push it in gently, not too deep."','"What does a seed need to grow? Sun, water, soil."','"We are the caregivers now."'],
             "if_happens":"Child wants to dig the seed up to see if it is growing",
             "avoid":'"No -- leave it alone."',
             "better":'"I know the waiting is SO hard. Let us mark today on the calendar. We come back in 7 days and THEN we look."',
             "why":"Plant growing is one of the most complete science experiences available to young children because it encompasses living things, growth, change over time, cause and effect (water and sun cause growth), and responsibility. The frustrating wait for germination also builds the scientific virtue of patience -- the willingness to wait for evidence before drawing conclusions. It also teaches that life has its own timeline.",
             "tool":"Patient Grower",
             "phrases":['"Growing things take their own time."','"Waiting is part of being a caregiver."'],
             "skills":"Life science, growth cycles, caretaking, patience."},
        16: {"title":"Parts of a Flower","emoji":"🌸","skill":"Biological Vocabulary","materials":"A flower (real or picture)",
             "milestone":"Milestone: Learning the parts of a flower -- petals, stem, leaves, roots -- builds biological vocabulary and the concept that living things have parts that do specific jobs.",
             "setup":["A real flower or a clear picture","Examine together"],
             "play":["Name the parts: petal, stem, leaf, root","What does each part do?","Carefully pull apart a flower -- see the inside","Draw and label"],
             "say":['"What are all the parts of this flower?"','"What does the stem do? The root? The petal?"','"All the parts have a job."'],
             "if_happens":"Child pulls it apart too quickly",
             "avoid":'"Careful -- you are destroying it."',
             "better":'"Yes! Scientists take things apart to understand them. That is what you are doing. Tell me what you see inside."',
             "why":"Learning biological vocabulary -- the names of plant parts and their functions -- builds the scientific concept of function: that each part of a living thing has a specific job. This function concept (structure determines function) is one of the deepest organising principles of biology. Dismantling a flower is a legitimate scientific method (dissection) and should be reframed as such rather than discouraged.",
             "tool":"Parts and Jobs",
             "phrases":['"Every part has a job."','"Name the part and guess its job."'],
             "skills":"Biological vocabulary, structure-function concept, scientific dissection."},
        17: {"title":"Water a Plant","emoji":"🚿","skill":"Caretaking Science","materials":"A plant, watering can",
             "milestone":"Milestone: Caring for a living thing -- observing it, noticing what it needs, and responding -- builds ecological responsibility and the care-giving capacities that transfer to all relationships.",
             "setup":["The plant you have been growing","Discuss what it needs"],
             "play":["Check the soil: dry or wet?","If dry: water","Observe the plant: any new growth?","Record: draw what you see today"],
             "say":['"Check the soil first -- does it need water today?"','"Look carefully -- do you see anything new since last time?"','"You are a plant scientist AND a plant caregiver."'],
             "if_happens":"Child overwaters enthusiastically",
             "avoid":'"Too much -- stop watering."',
             "better":'"So much water! I wonder what happens when a plant gets too much water. Let us watch and find out."',
             "why":"Overwatering is actually a valuable scientific learning opportunity because it allows the child to observe a cause-and-effect relationship that they caused. Saying I wonder what happens converts their mistake into a scientific experiment. This models the scientific mindset of treating unexpected outcomes as information rather than errors -- one of the most important scientific attitudes.",
             "tool":"Caring Scientist",
             "phrases":['"Every time you care for it, you are doing science."','"What does your plant need today?"'],
             "skills":"Caretaking, ecological responsibility, observation, scientific attitude."},
        18: {"title":"Seed to Table","emoji":"🥗","skill":"Food Systems","materials":"Vegetable from garden or shop",
             "milestone":"Milestone: Understanding that food comes from plants, and plants come from seeds, and seeds need soil and sun and water -- builds ecological literacy and the concept of food systems.",
             "setup":["A vegetable: ideally one you grew or can trace to a plant"],
             "play":["Where did this come from? Work backward","From table to shop to farm to plant to seed to soil","Draw the journey","Which step needed the sun?"],
             "say":['"This carrot -- where was it before the shop?"','"Before the farm -- where did the carrot start? As a seed!"','"The sun helped make this food. Do you feel the sun in it?"'],
             "if_happens":"Child says food comes from the shop",
             "avoid":'"No -- it comes from a farm first."',
             "better":'"The shop is right! And before the shop -- where do shops get their carrots? Let us trace it all the way back."',
             "why":"Understanding food systems -- the chain from soil to table -- is ecological literacy: the knowledge that humans are embedded in biological cycles, not independent of them. This is both a scientific and an ethical concept. Children who develop food system understanding show stronger environmental attitudes and more thoughtful consumption patterns in later childhood.",
             "tool":"Food Journey",
             "phrases":['"Your food has a story that started in the soil."','"The sun, the rain, the soil -- all in that bite."'],
             "skills":"Food systems, ecological literacy, biological cycles."},
        19: {"title":"Leaf Rubbings","emoji":"🍃","skill":"Botanical Art-Science","materials":"Leaves, paper, crayons",
             "milestone":"Milestone: Leaf rubbings reveal the internal structure of leaves -- veins, midrib, margin -- that is invisible to casual observation, building close observation skills through an artistic medium.",
             "setup":["Collect leaves of different shapes","Place under paper, rub crayon over top"],
             "play":["Rub the crayon and watch the leaf appear","Notice the veins appearing","Try different leaves: what is different?","Name the parts you can see"],
             "say":['"Rub the crayon -- see what appears!"','"Those lines are the leaf veins -- they carry water."','"Different leaf, different pattern."'],
             "if_happens":"Child presses too hard and tears the paper",
             "avoid":'"Lighter -- you are pressing too hard."',
             "better":'"Light and slow -- like you are colouring the air just above the paper."',
             "why":"Leaf rubbings are a scientifically productive art technique because the texture transfer reveals biological structure that is not visible to the naked eye (the vein network). This makes the invisible visible -- a key scientific method. The comparative element (different leaf, different pattern) builds systematic observation. The art-science integration also demonstrates that creativity and empirical investigation are not in opposition.",
             "tool":"Hidden Structure Revealed",
             "phrases":['"The rubbing shows what is inside the leaf."','"Art can do what eyes alone cannot."'],
             "skills":"Botanical observation, comparative analysis, art-science integration."},
        20: {"title":"Night Sky Wonder","emoji":"🌙","skill":"Astronomy","materials":"Clear night outdoors",
             "milestone":"Milestone: Observing the night sky -- stars, moon, darkness -- introduces children to the concept of scale (stars are huge but far away) and the rhythmic patterns of day and night.",
             "setup":["A clear night","Go outside or look from a window"],
             "play":["Count stars together (first 10)","Find the moon: what shape is it tonight?","Look for one thing that is not a star (a planet, a satellite)","Tell a story about what is up there"],
             "say":['"Count 10 stars -- which is the brightest?"','"The moon is a shape tonight -- what shape?"','"Every one of those lights is a sun. Like our sun. But very, very far away."'],
             "if_happens":"Child is afraid of the dark",
             "avoid":'"The dark is safe -- there is nothing to be scared of."',
             "better":'"We stay right here -- I am holding you. The dark is just the world with the lights off. And look -- the stars are tiny lights."',
             "why":"Astronomy is one of the oldest human sciences and connects children to the universal scale of reality. Understanding that stars are distant suns introduces the concept of light travel time -- we see things as they were. The darkness anxiety is best addressed by staying at the edge of the comfort zone (looking from a lit doorway) rather than forcing full exposure. The story about what is up there activates the narrative intelligence alongside scientific curiosity.",
             "tool":"Big Universe, Small Me",
             "phrases":['"Those are suns -- just very, very far away."','"The sky is a science that has no bottom."'],
             "skills":"Astronomy, scale concept, pattern observation, wonder."},
        21: "reflection",
        22: {"title":"Bug Hunt","emoji":"🐛","skill":"Entomology","materials":"Outdoor space, jar with holes",
             "milestone":"Milestone: Observing small animals in their habitat -- without harming them -- builds empathy for non-human life and the observation skills of field biology.",
             "setup":["Garden or park","Clear jar with lid punched with holes"],
             "play":["Look under rocks, in bark, in soil","Observe: how many legs? Wings? Colour?","Catch gently, observe, release","What were they doing when you found them?"],
             "say":['"What was this bug doing when you found it?"','"Count its legs -- 6 legs means an insect."','"We watch and release -- it has a life to live."'],
             "if_happens":"Child wants to keep the bug or squash it",
             "avoid":'"Do not squash it -- that is mean."',
             "better":'"This bug has a family too -- a job in the garden. Let us watch it do its job, and then let it go back to work."',
             "why":"Ethical treatment of small animals is a moral-ecological education that begins with the framing of insects as subjects with their own lives and purposes rather than objects for manipulation. Research shows that children who learn to treat small animals with care develop stronger general empathy. The taxonomy clue (6 legs = insect) provides scientific structure to what could otherwise be undifferentiated curiosity.",
             "tool":"Gentle Scientist",
             "phrases":['"Observe without harming."','"Every creature has a life you interrupted to have a look."'],
             "skills":"Entomology, ethical observation, gentle handling, taxonomy."},
        23: {"title":"Animal Homes","emoji":"🏠","skill":"Ecology","materials":"Outdoor walk",
             "milestone":"Milestone: Understanding that animals have specific habitats -- that a spider lives in a web, a bird in a nest, a bee in a hive -- builds the ecological concept of habitat as the environment that meets an organism's needs.",
             "setup":["Walk in a garden or park","Look for animal homes"],
             "play":["Find a spider web: what makes this a good home?","Find a bird nest: what is it made of?","Find a bee or wasp nest: how is it built?","What does each home provide: shelter, safety, food access?"],
             "say":['"This web is a spider home AND a food trap -- two jobs at once."','"The nest is made of what? Look closely."','"What would you need in YOUR home? The animal needs the same things."'],
             "if_happens":"Child destroys a web or nest",
             "avoid":'"You destroyed their home -- that was wrong."',
             "better":'"The spider will have to rebuild now -- they are good builders. Let us watch if we can. They build fast."',
             "why":"Habitat concept -- the understanding that organisms are adapted to specific environments that meet specific needs -- is a cornerstone of ecology. At this age, the approach is concrete: the web catches food (so it is in a good spot for that) and provides shelter. Connecting animal homes to the child own needs (you need shelter, warmth, food too) creates the empathic bridge that builds ecological caring.",
             "tool":"Home Has a Job",
             "phrases":['"Every home is designed for the creature that lives in it."','"What job does this home do for the animal?"'],
             "skills":"Ecology, habitat concept, comparative observation."},
        24: {"title":"Birds and Seeds","emoji":"🐦","skill":"Food Webs","materials":"Bird seed, shallow tray",
             "milestone":"Milestone: Observing birds feeding and connecting seeds to birds to the tree that made the seeds introduces the concept of food chains -- that all living things are connected through food.",
             "setup":["Shallow tray with bird seed","Place near a window"],
             "play":["Wait quietly for birds","Observe: what kinds? How many?","Where did the seeds come from? (Plants)","Where do birds go after eating? (Carry seeds far away)"],
             "say":['"We are watching quietly -- birds come to quiet gardens."','"Where did these seeds come from before we bought them?"','"The bird eats the seed -- and then flies far away and might drop a seed that grows a new plant."'],
             "if_happens":"No birds come",
             "avoid":'"We have to wait -- they will come."',
             "better":'"No birds yet -- scientists often wait a long time. Let us try a different spot and come back tomorrow."',
             "why":"Food chain observation -- connecting the seed to the plant to the bird to the spread of seeds -- introduces ecological connectivity. This is the ecological concept that all living things are connected through networks of energy and nutrients. At this age, the concept is introduced through one simple link (plant provides seed, bird eats seed and spreads it) rather than the full complexity of food webs.",
             "tool":"Connected",
             "phrases":['"Every living thing is connected to other living things."','"The bird and the tree are in a relationship."'],
             "skills":"Food chains, ecological connectivity, patient observation."},
        25: {"title":"Rock Collection","emoji":"🪨","skill":"Geology","materials":"Rocks gathered on a walk",
             "milestone":"Milestone: Collecting and comparing rocks -- by colour, texture, weight, shininess -- introduces geology and the concept that the Earth is made of materials with different properties.",
             "setup":["Gather 5-8 rocks of different types on a walk","Bring them home for close observation"],
             "play":["Lay them out: which is heaviest? Lightest?","Which is roughest? Smoothest?","Which has sparkle? Which has colour?","Sort and name them -- make up names if needed"],
             "say":['"Which rock is the heaviest? Pick up each one."','"This one has tiny sparkles -- those are minerals."','"Name your favourite rock. Give it a name."'],
             "if_happens":"Child loses interest quickly",
             "avoid":'"Keep looking -- we have more rocks to examine."',
             "better":'"Pick the ONE most interesting one. Just that one. Tell me everything you notice about that one."',
             "why":"Geology is introduced through the concrete and sensory properties of rocks (weight, texture, colour, lustre). The naming and sorting activities build classification and vocabulary. Naming a favourite rock builds a personal connection to the material world -- a form of animism that is normal and healthy at this age and actually supports long-term environmental caring by building emotional bonds with the physical Earth.",
             "tool":"Rock Story",
             "phrases":['"This rock is millions of years old."','"Every rock has a story of how it was made."'],
             "skills":"Geology, material properties, classification, sense of geological time."},
        26: {"title":"Weather Journal Review","emoji":"🌈","skill":"Data Science","materials":"Any weather notes from earlier this month",
             "milestone":"Milestone: Looking back at weather observations across the month and noticing patterns -- more sun, some rain -- introduces the concept of data: multiple observations that reveal trends.",
             "setup":["Any drawings or verbal notes from the month's weather","Even just memories are data"],
             "play":["How many sunny days this month? Estimate","How many rainy? How many cloudy?","Which was most common?","Was there a pattern -- rain usually followed by sun?"],
             "say":['"Looking back at all our weather -- what do you notice?"','"More sunny or more cloudy this month?"','"Is there a pattern -- what comes after the rain?"'],
             "if_happens":"Child cannot remember any specific days",
             "avoid":'"Think -- we talked about this."',
             "better":'"Let us just estimate -- how does this month feel: mostly sunny, mostly cloudy, a mix? Your feeling is data too."',
             "why":"Data analysis -- comparing multiple observations to identify trends -- is the highest cognitive level of the scientific process. At this age, the analysis is simple (more of X than Y) and memory-based rather than recorded. But the orientation -- using accumulated observations to reach a conclusion about the world -- is the disposition of a data scientist. Accepting feelings as data introduces the concept that subjective experience can be systematised.",
             "tool":"Data Detective",
             "phrases":['"Multiple observations tell you something one observation cannot."','"Your memory is data."'],
             "skills":"Data orientation, trend detection, scientific synthesis."},
        27: {"title":"Nature Art Gallery","emoji":"🖼️","skill":"Nature Appreciation","materials":"Natural objects collected this month",
             "milestone":"Milestone: Arranging natural objects aesthetically and sharing them with others builds both ecological appreciation and creative pride -- the integration of art and science that characterises deep nature connection.",
             "setup":["Gather natural items collected this month","A surface to arrange them on"],
             "play":["Arrange the objects in a pattern or composition","Step back: what do you see?","Explain your arrangement to someone","What is the title of this nature artwork?"],
             "say":['"Arrange your nature collection -- any way you want."','"Tell me why you put this here."','"What is the title of your nature gallery?"'],
             "if_happens":"Child arranges randomly and has no explanation",
             "avoid":'"Think about why you put them that way."',
             "better":'"Just tell me: what is your favourite thing in the collection? Put that in the middle. Now arrange the rest around the favourite."',
             "why":"Arranging natural objects as art integrates scientific observation (knowing what each object is and where it came from) with aesthetic decision-making (placing things in ways that feel visually satisfying). This integration reflects the deep historical connection between naturalism and art -- from cave paintings to botanical illustration. Children who find nature beautiful develop stronger environmental values than those taught only the intellectual content of ecology.",
             "tool":"Beautiful Nature",
             "phrases":['"Nature is already beautiful -- you are just revealing it."','"Noticing beauty is a kind of love."'],
             "skills":"Nature appreciation, aesthetic arrangement, ecological connection."},
        28: "reflection",
        29: {"title":"Science Questions Book","emoji":"📔","skill":"Inquiry","materials":"Paper, crayons, stapler",
             "milestone":"Milestone: A book of questions the child genuinely does not know the answer to is one of the most intellectually valuable artefacts of early childhood education -- it externalises scientific curiosity.",
             "setup":["Fold 4-5 pages, staple","Title: My Questions About Nature"],
             "play":["Each page: one question they have about nature","Draw a picture to go with it","Dictate the question -- parent writes","Questions can be unanswerable -- that is fine"],
             "say":['"What is something about nature you wonder about -- that you do not know?"','"Even a question you cannot answer is worth writing down."','"Scientists keep asking questions -- even when they do not know the answer."'],
             "if_happens":"Child only asks questions they already know the answer to",
             "avoid":'"You already know that -- ask something harder."',
             "better":'"What is something about nature that surprises you? Something that does not quite make sense?"',
             "why":"Generating genuine questions -- questions the child actually does not know the answer to -- is one of the most cognitively demanding and educationally powerful activities. It requires metacognition (knowing what you do not know), intellectual humility (admitting uncertainty), and curiosity (caring enough to want to find out). These are the three essential dispositions of a scientist and a lifelong learner.",
             "tool":"Question Keeper",
             "phrases":['"A question you cannot answer yet is a treasure."','"Scientists keep lists of things they do not understand."'],
             "skills":"Inquiry, metacognition, intellectual humility."},
        30: "celebration",
    },
    "celebration": {
        "title": "Month 9 Complete: Nature Scientist!",
        "summary": "Nine months of TotWise. This month your child looked closely, got dirty, grew something, observed bugs and birds, and built a list of genuine questions about the world. The scientist is alive.",
        "skills_built": ["Scientific observation and documentation", "Water and earth science (pouring, mixing, mud)", "Plant growing and caretaking", "Animal observation and ecological thinking", "Data orientation: noticing patterns over time"],
        "month_next_teaser": "Next month: Sounds and Songs. Your child will explore rhythm, rhyme, letter sounds, and the music that language makes -- building the pre-literacy skills that reading will need.",
    },
    "reflection_activities": {
        7:  {"activity": "Nature Collection", "desc": "Lay out everything collected this week. Sort it three ways. Which category is the biggest?"},
        14: {"activity": "Water Science Review", "desc": "What did you learn about water this week? Name 3 things water can do."},
        21: {"activity": "Plant Check", "desc": "How is your seed or plant doing? Draw it today. Compare to your Day 13 drawing."},
        28: {"activity": "Best Nature Moment", "desc": "What was your favourite nature moment this month? Act it out or draw it."},
    },
}
